-- hero-less-moba — a lane-pushing game with the heroes subtracted out
-- Copyright (C) 2026 gabrilend
--
-- This program is free software: you can redistribute it and/or modify it
-- under the terms of the GNU Affero General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or (at
-- your option) any later version.
--
-- This program is distributed in the hope that it will be useful, but
-- WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
-- General Public License for more details.
--
-- You should have received a copy of the GNU Affero General Public License
-- along with this program. If not, see <https://www.gnu.org/licenses/>.
--
-- SPDX-License-Identifier: AGPL-3.0-or-later

-- 064-the-documentation-becomes-html.lua
--
-- Every document, issue and companion, turned into pages you can browse.
--
-- ## The same separation, one level up
--
-- **The Markdown is the data and the HTML is a view of it**, generated by a tool
-- rather than maintained by hand. That is the same rule the simulation and the viewer
-- follow, applied to the project's own prose -- and for the same reason: a hand-kept
-- second copy of anything is a copy that will disagree with the first.
--
-- ## What it is for
--
-- This project is read far more than it is run. There are more words in it than code,
-- the words came first, and reconstructing the software means reading them. But they
-- reference each other constantly and a directory of files is a bad way to follow a
-- reference -- so: every page reachable from every other, a table of contents down
-- the side, and **every issue number a link**.
--
-- That last one matters more than it sounds. The documents mention issues by number
-- roughly two hundred times, and following one by hand means knowing the naming
-- convention, guessing the description, and listing a directory.

local M = {}

-- {{{ M.PALETTE
-- The game's own colours, so the documentation looks like the thing it describes.
-- Warm for one side, cold for the other, on the same cold ground the map is drawn on.
M.PALETTE = [[
:root {
  --ground:   #0d0f13;
  --panel:    #14171d;
  --edge:     #232833;
  --ink:      #c7ccd6;
  --dim:      #7d8492;
  --warm:     #f5a83d;
  --cold:     #5cc7ee;
  --bone:     #e0ded8;
  --blood:    #b81313;
  --green:    #78c96e;
}
]]

-- {{{ M.STYLE
M.STYLE = [[
* { box-sizing: border-box; }
body {
  margin: 0; background: var(--ground); color: var(--ink);
  font: 15.5px/1.65 "Iowan Old Style", "Palatino Linotype", Palatino, Georgia, serif;
}
a { color: var(--cold); text-decoration: none; border-bottom: 1px solid #2b4d5c; }
a:hover { color: var(--warm); border-bottom-color: var(--warm); }

#shell { display: flex; min-height: 100vh; }

#contents {
  width: 292px; flex: 0 0 292px; background: var(--panel);
  border-right: 1px solid var(--edge); padding: 20px 0 60px;
  position: sticky; top: 0; height: 100vh; overflow-y: auto;
}
#contents h1 {
  font-size: 15px; letter-spacing: .14em; text-transform: uppercase;
  color: var(--warm); margin: 0 20px 4px; font-weight: 600;
}
#contents .tagline { margin: 0 20px 18px; color: var(--dim); font-size: 12.5px; font-style: italic; }
#contents section { margin-bottom: 14px; }
#contents h2 {
  font-size: 11px; letter-spacing: .18em; text-transform: uppercase;
  color: var(--dim); margin: 14px 20px 5px; font-weight: 600;
}
#contents a {
  display: block; padding: 3px 20px 3px 20px; border: 0;
  font-size: 13.5px; color: var(--ink); line-height: 1.4;
}
#contents a:hover { background: #1b1f27; color: var(--warm); }
#contents a.here { background: #1b1f27; color: var(--warm); border-left: 3px solid var(--warm); padding-left: 17px; }
#contents .index { color: var(--dim); font-variant-numeric: tabular-nums; margin-right: 7px; }

#filter {
  margin: 0 20px 12px; width: calc(100% - 40px); background: var(--ground);
  border: 1px solid var(--edge); color: var(--ink); padding: 6px 9px;
  font: inherit; font-size: 13px; border-radius: 3px;
}
#filter:focus { outline: 0; border-color: var(--warm); }

#page { flex: 1; min-width: 0; padding: 42px 56px 120px; max-width: 900px; }
h1, h2, h3, h4 { font-family: "Inter", "Helvetica Neue", Arial, sans-serif; line-height: 1.25; }
h1 { font-size: 30px; color: var(--warm); margin: 0 0 26px; font-weight: 600; }
h2 { font-size: 21px; color: var(--bone); margin: 38px 0 12px; font-weight: 600;
     border-bottom: 1px solid var(--edge); padding-bottom: 7px; }
h3 { font-size: 16.5px; color: var(--cold); margin: 26px 0 8px; font-weight: 600; }
h4 { font-size: 14.5px; color: var(--dim); margin: 20px 0 6px;
     text-transform: uppercase; letter-spacing: .09em; }
p { margin: 0 0 15px; }
strong { color: var(--bone); font-weight: 600; }
em { color: var(--dim); }
hr { border: 0; border-top: 1px solid var(--edge); margin: 34px 0; }

blockquote {
  margin: 20px 0; padding: 3px 0 3px 20px; border-left: 3px solid var(--warm);
  color: var(--bone); font-style: italic;
}
blockquote p { margin: 0 0 8px; }
blockquote p:last-child { margin: 0; }

ul, ol { margin: 0 0 15px; padding-left: 24px; }
li { margin-bottom: 5px; }

table { border-collapse: collapse; margin: 20px 0; width: 100%; font-size: 14px; }
th, td { text-align: left; padding: 7px 12px; border-bottom: 1px solid var(--edge); vertical-align: top; }
th { color: var(--dim); font-weight: 600; text-transform: uppercase;
     letter-spacing: .08em; font-size: 11.5px; }
tr:hover td { background: #161a21; }

code {
  font-family: "Berkeley Mono", "SF Mono", Menlo, Consolas, monospace;
  font-size: 13px; background: #191d25; padding: 1.5px 5px; border-radius: 3px;
  color: var(--bone);
}
pre {
  background: #10131a; border: 1px solid var(--edge); border-left: 3px solid var(--cold);
  padding: 14px 17px; overflow-x: auto; border-radius: 3px; margin: 18px 0;
}
pre code { background: none; padding: 0; font-size: 12.5px; line-height: 1.6; }

.kw { color: #d68fd6; }
.str { color: var(--green); }
.num { color: var(--warm); }
.cmt { color: #5d6472; font-style: italic; }

.issue-link { border-bottom: 1px dotted var(--warm); color: var(--warm); }
.badge {
  display: inline-block; font-size: 11px; letter-spacing: .08em; text-transform: uppercase;
  padding: 2px 8px; border-radius: 10px; margin-left: 8px; vertical-align: middle;
  font-family: "Inter", sans-serif;
}
.badge.built { background: #1c3320; color: var(--green); }
.badge.part  { background: #33301c; color: var(--warm); }
.badge.none  { background: #22262e; color: var(--dim); }

figure { margin: 24px 0; }
figcaption { color: var(--dim); font-size: 13px; font-style: italic; margin-top: 8px; }
svg { max-width: 100%; }

#page > footer { margin-top: 60px; padding-top: 18px; border-top: 1px solid var(--edge);
                 color: var(--dim); font-size: 13px; }
]]
-- }}}
-- }}}

-- {{{ local function escape()
local function escape(text)
  text = text:gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;")
  return text
end
-- }}}

-- {{{ local function highlight_lua()
-- Syntax highlighting, for Lua, done by hand.
--
-- Three passes over a line rather than a real lexer, because the thing being
-- highlighted is already correct Lua that a real compiler has read -- this only has to
-- make it easier to look at. A lexer would be right and would be a second parser to
-- keep in step with the language.
local function highlight_lua(code)
  local out = {}
  for line in (code .. "\n"):gmatch("(.-)\n") do
    local comment = line:match("^(.-)%-%-")
    local body, tail = line, nil
    if comment ~= nil then
      body = comment
      tail = line:sub(#comment + 1)
    end

    body = escape(body)
    body = body:gsub("(&quot;[^&]-&quot;)", "<span class='str'>%1</span>")
    body = body:gsub('(".-")', "<span class='str'>%1</span>")
    body = body:gsub("(%f[%w])(%d+%.?%d*)(%f[%W])", "%1<span class='num'>%2</span>%3")
    for _, word in ipairs({"local", "function", "end", "if", "then", "else", "elseif",
                           "for", "while", "do", "return", "and", "or", "not", "nil",
                           "true", "false", "in", "break", "repeat", "until"}) do
      body = body:gsub("(%f[%w])(" .. word .. ")(%f[%W])", "%1<span class='kw'>%2</span>%3")
    end

    if tail ~= nil then
      out[#out + 1] = body .. "<span class='cmt'>" .. escape(tail) .. "</span>"
    else
      out[#out + 1] = body
    end
  end
  return table.concat(out, "\n")
end
-- }}}

-- {{{ local function inline()
-- The inline half of Markdown, plus the one thing this project needs that Markdown
-- has no syntax for: **an issue number is a link.**
--
-- The documents mention issues by number roughly two hundred times, and following one
-- by hand means knowing the naming convention, guessing the description, and listing a
-- directory. So `issue 206` becomes a link, and so does a bare three-digit number in
-- a table cell that is obviously an issue.
local function inline(text, links)
  text = escape(text)

  -- Code first, so nothing else formats inside it.
  local spans = {}
  text = text:gsub("`([^`]+)`", function(code)
    spans[#spans + 1] = "<code>" .. code .. "</code>"
    return "\1" .. #spans .. "\1"
  end)

  text = text:gsub("%*%*([^*]+)%*%*", "<strong>%1</strong>")
  text = text:gsub("%*([^*]+)%*", "<em>%1</em>")

  -- Markdown links, rewritten to the generated page names.
  text = text:gsub("%[([^%]]+)%]%(([^)]+)%)", function(label, target)
    local page = target:match("([^/]+)%.md$")
    if page ~= nil then
      return "<a href='" .. page .. ".html'>" .. label .. "</a>"
    end
    return "<a href='" .. target .. "'>" .. label .. "</a>"
  end)

  -- And the issue numbers.
  text = text:gsub("(issues?%s+)(%d%d%d)", function(word, number)
    local target = links[number]
    if target == nil then
      return word .. number
    end
    return word .. "<a class='issue-link' href='" .. target .. ".html'>" .. number .. "</a>"
  end)

  text = text:gsub("\1(%d+)\1", function(index)
    return spans[tonumber(index)]
  end)
  return text
end
-- }}}

-- {{{ local function render()
-- Markdown to HTML. The subset this project actually writes, and nothing else.
--
-- Deliberately not a complete implementation. A full Markdown parser is a large thing
-- with many decisions in it, and every one of those decisions is a way for the
-- generated page to differ from what the author meant. This handles headings, lists,
-- tables, quotes, fenced code and rules -- which is everything in every document here,
-- checked by reading them.
local function render(markdown, links)
  local out = {}
  local in_list, in_table, in_code = false, false, false
  local code_buffer, code_kind = {}, ""

  local function close_list()
    if in_list then out[#out + 1] = "</ul>" ; in_list = false end
  end
  local function close_table()
    if in_table then out[#out + 1] = "</tbody></table>" ; in_table = false end
  end

  for line in (markdown .. "\n"):gmatch("(.-)\n") do
    if in_code then
      if line:match("^```") then
        in_code = false
        local body = table.concat(code_buffer, "\n")
        out[#out + 1] = "<pre><code>" ..
          ((code_kind == "lua") and highlight_lua(body) or escape(body)) .. "</code></pre>"
        code_buffer = {}
      else
        code_buffer[#code_buffer + 1] = line
      end
    elseif line:match("^```") then
      close_list() ; close_table()
      in_code = true
      code_kind = line:match("^```(%w*)") or ""
    elseif line:match("^%s*$") then
      close_list() ; close_table()
    elseif line:match("^#+%s") then
      close_list() ; close_table()
      local hashes, rest = line:match("^(#+)%s+(.*)$")
      local level = #hashes
      out[#out + 1] = string.format("<h%d>%s</h%d>", level, inline(rest, links), level)
    elseif line:match("^%-%-%-+%s*$") then
      close_list() ; close_table()
      out[#out + 1] = "<hr>"
    elseif line:match("^>%s?") then
      close_list() ; close_table()
      out[#out + 1] = "<blockquote><p>" .. inline(line:gsub("^>%s?", ""), links) .. "</p></blockquote>"
    elseif line:match("^%s*[-*]%s+") then
      close_table()
      if not in_list then out[#out + 1] = "<ul>" ; in_list = true end
      out[#out + 1] = "<li>" .. inline(line:gsub("^%s*[-*]%s+", ""), links) .. "</li>"
    elseif line:match("^%s*%d+%.%s+") then
      close_table()
      if not in_list then out[#out + 1] = "<ul>" ; in_list = true end
      out[#out + 1] = "<li>" .. inline(line:gsub("^%s*%d+%.%s+", ""), links) .. "</li>"
    elseif line:match("^|") then
      close_list()
      -- A separator row opens the body rather than producing a row of dashes.
      if line:match("^|[%s|:%-]+|%s*$") and in_table then
        out[#out + 1] = "</thead><tbody>"
      else
        local cells = {}
        for cell in line:gmatch("|([^|]*)") do
          cells[#cells + 1] = cell:match("^%s*(.-)%s*$")
        end
        -- The trailing empty cell after the final pipe.
        if cells[#cells] == "" then cells[#cells] = nil end
        if not in_table then
          out[#out + 1] = "<table><thead>"
          in_table = true
          local row = {"<tr>"}
          for _, cell in ipairs(cells) do
            row[#row + 1] = "<th>" .. inline(cell, links) .. "</th>"
          end
          row[#row + 1] = "</tr>"
          out[#out + 1] = table.concat(row)
        else
          local row = {"<tr>"}
          for _, cell in ipairs(cells) do
            row[#row + 1] = "<td>" .. inline(cell, links) .. "</td>"
          end
          row[#row + 1] = "</tr>"
          out[#out + 1] = table.concat(row)
        end
      end
    else
      close_list() ; close_table()
      out[#out + 1] = "<p>" .. inline(line, links) .. "</p>"
    end
  end
  close_list() ; close_table()
  return table.concat(out, "\n")
end
-- }}}

M.render = render

-- {{{ local function list_files()
-- Every file matching a pattern in a directory, sorted, without shelling out for a
-- listing per directory.
local function list_files(directory, pattern)
  local names = {}
  local pipe = io.popen("ls -1 '" .. directory .. "' 2>/dev/null")
  if pipe == nil then
    return names
  end
  for name in pipe:lines() do
    if name:match(pattern) then
      names[#names + 1] = name
    end
  end
  pipe:close()
  table.sort(names)
  return names
end
-- }}}

-- {{{ local function map_drawing()
-- The map, as an SVG, on the front page.
--
-- Drawn from the map builder rather than from a picture of it, so it cannot go stale.
-- That is the same rule as everything else here: the thing is the data, the page is a
-- view of it, and a view nobody generates is a view that will be wrong.
local function map_drawing(map)
  local out = {}
  local size = 460
  local bounds = map.bounds
  local span = math.max(bounds.max_x - bounds.min_x, bounds.max_y - bounds.min_y)
  local function place(x, y)
    return (x - bounds.min_x) / span * size, (y - bounds.min_y) / span * size
  end

  out[#out + 1] = string.format(
    "<svg viewBox='-16 -16 %d %d' width='%d' height='%d'>", size + 32, size + 32, size, size)

  -- The connectors first, under everything: the ground the jungle used to occupy.
  for _, connector in ipairs(map.connector) do
    local points = {}
    for _, node_id in ipairs(connector.path) do
      local x, y = place(map.node[node_id].x, map.node[node_id].y)
      points[#points + 1] = string.format("%.1f,%.1f", x, y)
    end
    out[#out + 1] = "<polyline points='" .. table.concat(points, " ") ..
      "' fill='none' stroke='#2a2732' stroke-width='7'/>"
  end

  local lane_colour = {"#3a4150", "#46506a", "#3a4150"}
  for index, lane in ipairs(map.lane) do
    local points = {}
    for _, node_id in ipairs(lane.path) do
      local x, y = place(map.node[node_id].x, map.node[node_id].y)
      points[#points + 1] = string.format("%.1f,%.1f", x, y)
    end
    out[#out + 1] = string.format(
      "<polyline points='%s' fill='none' stroke='%s' stroke-width='%.1f' " ..
      "stroke-linejoin='round' stroke-linecap='round'/>",
      table.concat(points, " "), lane_colour[index],
      lane.width / span * size)
  end

  -- The stone, in each team's own colour.
  for _, site in ipairs(map.site) do
    local node = map.node[site.node]
    local x, y = place(node.x, node.y)
    local colour = (site.team == 1) and "#f5a83d" or "#5cc7ee"
    if site.kind == 3 then
      out[#out + 1] = string.format(
        "<circle cx='%.1f' cy='%.1f' r='9' fill='none' stroke='%s' stroke-width='2.5'/>",
        x, y, colour)
      out[#out + 1] = string.format(
        "<circle cx='%.1f' cy='%.1f' r='3.5' fill='%s'/>", x, y, colour)
    else
      out[#out + 1] = string.format(
        "<rect x='%.1f' y='%.1f' width='7' height='7' fill='%s' opacity='0.85'/>",
        x - 3.5, y - 3.5, colour)
    end
  end

  -- And the junctions, which are the only points on the map where anything chooses.
  for _, lane in ipairs(map.lane) do
    local node = map.node[lane.junction[1]]
    local x, y = place(node.x, node.y)
    out[#out + 1] = string.format(
      "<circle cx='%.1f' cy='%.1f' r='6' fill='none' stroke='#7d8492' " ..
      "stroke-width='1.5' stroke-dasharray='3 2'/>", x, y)
  end

  out[#out + 1] = "</svg>"
  return table.concat(out, "\n")
end
-- }}}

-- {{{ local function phase_drawing()
-- The shape of a match, as a bar. Read from the timing table rather than described.
local function phase_drawing(timing)
  local order = {
    {"normal", timing.first_normal, "#2b3140"},
    {"surge", timing.surge, "#8a5a1e"},
    {"challenge", timing.challenge or 1200, "#5a3a6e"},
    {"calm", timing.calm, "#25403a"},
    {"normal", timing.normal, "#2b3140"},
    {"surge", timing.surge, "#8a5a1e"},
    {"challenge", timing.challenge or 1200, "#5a3a6e"},
    {"calm", timing.calm, "#25403a"},
    {"normal", timing.normal, "#2b3140"},
    {"surge", timing.surge, "#8a5a1e"},
    {"the Golem", timing.challenge or 1800, "#7a1a1a"},
  }
  local total = 0
  for _, row in ipairs(order) do total = total + row[2] end

  local out = {"<svg viewBox='0 0 900 74' width='100%' height='74'>"}
  local x = 0
  for _, row in ipairs(order) do
    local width = row[2] / total * 900
    out[#out + 1] = string.format(
      "<rect x='%.1f' y='14' width='%.1f' height='26' fill='%s'/>", x, width, row[3])
    if width > 52 then
      out[#out + 1] = string.format(
        "<text x='%.1f' y='31' fill='#c7ccd6' font-size='10' text-anchor='middle' " ..
        "font-family='Inter,sans-serif'>%s</text>", x + width / 2, row[1])
    end
    x = x + width
  end
  out[#out + 1] = "<text x='0' y='60' fill='#7d8492' font-size='11' " ..
    "font-family='Inter,sans-serif'>a match, start to finish -- three surges, three " ..
    "challenges, and the last one does not end</text>"
  out[#out + 1] = "</svg>"
  return table.concat(out, "\n")
end
-- }}}

-- {{{ function M.build()
-- Walks every document and writes the site.
function M.build(root, modules)
  local out_dir = root .. "/docs/HTML"
  os.execute("mkdir -p '" .. out_dir .. "'")

  -- What there is to write, and where each thing came from.
  -- **The issue pattern allows a letter after the number**, because a large issue is
  -- broken into sub-issues named 211a, 211b and so on -- a convention this project has
  -- used for a while and which this page silently did not know about, so every
  -- sub-issue ever written was unreachable from the documentation it belongs to.
  --
  -- And the two un-numbered documents are named outright. The queue and the balance log
  -- are the two most-read files in the project and neither matches a numbered pattern,
  -- because neither is a numbered document -- they are ledgers, and a ledger does not
  -- have a place in a reading order. That is not a reason for them to be missing from
  -- the only browsable copy of everything.
  local sections = {
    {title = "start here", dir = "notes", pattern = "^[a-z].*$", plain = true},
    {title = "the queue", dir = "issues", pattern = "^work%-queue%.md$"},
    {title = "the design", dir = "docs", pattern = "^%d%d%d%-.*%.md$"},
    {title = "the ledger", dir = "docs", pattern = "^balance%-updates%.md$"},
    {title = "issues", dir = "issues", pattern = "^%d%d%d%a?%-.*%.md$"},
    {title = "progress", dir = "issues", pattern = "^phase%-%d%-progress%.md$"},
    {title = "the simulation", dir = "src", pattern = "^%d%d%d%-.*%.info%.md$"},
    {title = "the catalogues", dir = "assets", pattern = "^%d%d%d%-.*%.info%.md$"},
    {title = "the tests", dir = "tests", pattern = "^%d%d%d%-.*%.info%.md$"},
  }

  -- Every issue number, so a mention of one anywhere becomes a link.
  local links = {}
  for _, name in ipairs(list_files(root .. "/issues", "^%d%d%d%a?%-.*%.md$")) do
    -- Keyed by the number **and** by the number plus its letter, so that both "211" and
    -- "211c" in a sentence become links to the right pages. The bare number wins for
    -- itself because a parent issue is what "211" means; a sub-issue is only ever
    -- referred to with its letter attached.
    local lettered = name:match("^(%d%d%d%a)%-")
    if lettered ~= nil then
      links[lettered] = name:gsub("%.md$", "")
    else
      links[name:sub(1, 3)] = name:gsub("%.md$", "")
    end
  end

  local pages = {}
  for _, section in ipairs(sections) do
    local entries = {}
    for _, name in ipairs(list_files(root .. "/" .. section.dir, section.pattern)) do
      local handle = io.open(root .. "/" .. section.dir .. "/" .. name, "r")
      if handle ~= nil then
        local body = handle:read("*a")
        handle:close()
        local slug = name:gsub("%.md$", "")
        local title = body:match("^#%s+(.-)\n") or slug
        entries[#entries + 1] = {slug = slug, title = title, body = body,
                                 plain = section.plain}
      end
    end
    if #entries > 0 then
      pages[#pages + 1] = {title = section.title, entries = entries}
    end
  end

  -- The contents rail, identical on every page, with the current one marked.
  local function contents_for(current)
    local out = {"<nav id='contents'>",
      "<h1>hero-less-moba</h1>",
      "<p class='tagline'>a lane-pushing game with the heroes subtracted out</p>",
      "<input id='filter' placeholder='filter&hellip;' autocomplete='off'>",
      "<a href='index.html'" .. ((current == "index") and " class='here'" or "") ..
        ">the front page</a>"}
    for _, section in ipairs(pages) do
      out[#out + 1] = "<section><h2>" .. section.title .. "</h2>"
      for _, entry in ipairs(section.entries) do
        local index = entry.slug:match("^(%d%d%d)")
        -- Strip the leading index and dash from a title, so the rail reads as names
        -- rather than as numbered names.
        --
        -- **Not with a character class.** Lua patterns are bytes, so `[-—]` is a class
        -- containing the three separate bytes of an em-dash -- and it will happily
        -- match one of them and leave the other two, producing a file that is no
        -- longer valid UTF-8. Every generated page was corrupt in exactly that way
        -- before this comment existed.
        local label = entry.title:gsub("^%d%d%d%s*", "")
        label = label:gsub("^\226\128\148%s*", "")   -- an em-dash
        label = label:gsub("^%-%s*", "")
        out[#out + 1] = string.format(
          "<a href='%s.html'%s>%s%s</a>", entry.slug,
          (current == entry.slug) and " class='here'" or "",
          index and ("<span class='index'>" .. index .. "</span>") or "",
          escape(label))
      end
      out[#out + 1] = "</section>"
    end
    out[#out + 1] = "</nav>"
    return table.concat(out, "\n")
  end

  local FILTER_SCRIPT = [[
<script>
// Filtering the contents. The only script on the page, and it exists because there
// are more than eighty documents here and scrolling a list of eighty things to find
// one is not navigation.
var box = document.getElementById('filter');
box.addEventListener('input', function () {
  var want = box.value.toLowerCase();
  var rail = document.getElementById('contents');
  rail.querySelectorAll('section').forEach(function (section) {
    var shown = 0;
    section.querySelectorAll('a').forEach(function (link) {
      var match = link.textContent.toLowerCase().indexOf(want) !== -1;
      link.style.display = match ? '' : 'none';
      if (match) { shown++; }
    });
    section.style.display = shown ? '' : 'none';
  });
});
</script>
]]

  local function write_page(slug, title, body_html)
    local handle = io.open(out_dir .. "/" .. slug .. ".html", "w")
    handle:write("<!doctype html><html lang='en'><head><meta charset='utf-8'>")
    handle:write("<meta name='viewport' content='width=device-width,initial-scale=1'>")
    handle:write("<title>" .. escape(title) .. " -- hero-less-moba</title>")
    handle:write("<style>" .. M.PALETTE .. M.STYLE .. "</style></head><body>")
    handle:write("<div id='shell'>")
    handle:write(contents_for(slug))
    handle:write("<main id='page'>")
    handle:write(body_html)
    handle:write("<footer>Generated from the Markdown by <code>" ..
      "064-the-documentation-becomes-html.lua</code>. The Markdown is the data; " ..
      "this is a view of it. Do not edit these pages -- edit the documents and " ..
      "run <code>./build-documentation</code>.</footer>")
    handle:write("</main></div>" .. FILTER_SCRIPT .. "</body></html>")
    handle:close()
  end

  local written = 0
  for _, section in ipairs(pages) do
    for _, entry in ipairs(section.entries) do
      local html
      if entry.plain then
        -- notes/ holds the visions, which are prose rather than Markdown and whose
        -- line breaks are the author's. They are shown as written.
        html = "<h1>" .. escape(entry.slug) .. "</h1><pre><code>" ..
               escape(entry.body) .. "</code></pre>"
      else
        html = render(entry.body, links)
      end
      write_page(entry.slug, entry.title, html)
      written = written + 1
    end
  end

  -- The front page, which is the only one with pictures on it.
  local parameters = modules.match_parameters.load()
  local map = modules.map_builder.build(parameters)

  local front = {}
  front[#front + 1] = "<h1>hero-less-moba</h1>"
  front[#front + 1] = "<p>Picture a lane-pusher, and subtract the heroes, the jungle " ..
    "and the items. What is left is a great many small bodies walking at each other " ..
    "and grinding to a halt in the middle -- which is not a game. So the things taken " ..
    "out are replaced by <strong>one shared chest of upgrades that three people argue " ..
    "over</strong>, and the argument is the game.</p>"
  front[#front + 1] = "<h2>The ground</h2>"
  front[#front + 1] = "<figure>" .. map_drawing(map) ..
    "<figcaption>Two bases facing each other across one diagonal; the three junctions " ..
    "on the other. Drawn from the map builder, so it cannot go stale.</figcaption></figure>"
  front[#front + 1] = "<h2>The shape of a match</h2>"
  front[#front + 1] = "<figure>" .. phase_drawing(parameters.boon.timing) ..
    "<figcaption>Three times the board comes apart, and the third time nothing " ..
    "saves it.</figcaption></figure>"
  front[#front + 1] = "<h2>Where to start</h2>"
  front[#front + 1] = "<ul>" ..
    "<li><a href='vision.html'>The vision</a> -- where all of this came from, in the " ..
    "author's own words.</li>" ..
    "<li><a href='001-what-this-game-is.html'>What this game is</a> -- the subtraction, " ..
    "and the three layers that replace what was taken.</li>" ..
    "<li><a href='019-roadmap.html'>The roadmap</a> -- nine phases, which are clusters " ..
    "of functionality rather than a schedule.</li>" ..
    "<li><a href='020-open-questions.html'>Open questions</a> -- every unresolved " ..
    "decision, and the reasoning behind every resolved one.</li>" ..
    "</ul>"
  front[#front + 1] = "<h2>Everything else</h2>"
  front[#front + 1] = "<p>Down the left. Every page here is reachable from every " ..
    "other, every issue number is a link, and the filter at the top of the rail " ..
    "searches all of it.</p>"

  write_page("index", "hero-less-moba", table.concat(front, "\n"))
  written = written + 1

  return written, out_dir
end
-- }}}

return M
