-- hero-less-moba — a lane-pushing game with the heroes subtracted out
-- Copyright (C) 2026 gabrilend
--
-- This program is free software: you can redistribute it and/or modify it
-- under the terms of the GNU Affero General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or (at
-- your option) any later version.
--
-- This program is distributed in the hope that it will be useful, but
-- WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
-- General Public License for more details.
--
-- You should have received a copy of the GNU Affero General Public License
-- along with this program. If not, see <https://www.gnu.org/licenses/>.
--
-- SPDX-License-Identifier: AGPL-3.0-or-later

-- 069-the-proving-ground.lua
--
-- The window onto the arena: ground, bodies, a caption, and nothing that belongs to a
-- match.
--
-- The ordinary viewer draws a game. It has a chest panel, a hero roster, sign-posts,
-- push-depth bands along three lanes, upgrade badges, a wallet and a clock, and every
-- one of those is there because a player needs it. A person watching one rule needs
-- none of them, and each one is a thing on the screen that has to be visually
-- discounted before the thing being looked at can be seen.
--
-- So this draws four things: the ground, the bodies, what each body is doing, and the
-- sentence the scene came with. **What is absent is the feature.**
--
-- It also runs its own loop rather than the match tick. The scene says which mechanics
-- it wants, the arena hangs those and no others, and this advances them -- so the
-- picture on the screen is generated by exactly the machinery named in the scene file,
-- and anything moving is something the scene asked to have moving.

local M = {}

-- The palette, near enough to the real viewer's that a person moving between the two
-- is not relearning what a colour means, and its own table because the arena is not a
-- match and should not have to load a match's renderer to find out what blue is.
local COLOUR = {
  ground     = {0.145, 0.157, 0.184},
  ground_rim = {0.255, 0.275, 0.318},
  backdrop   = {0.075, 0.082, 0.098},
  team       = {
    [1] = {0.945, 0.647, 0.263},
    [2] = {0.365, 0.729, 0.925},
    [3] = {0.769, 0.612, 0.918},
  },
  stray      = {0.965, 0.925, 0.545},
  text       = {0.780, 0.800, 0.840},
  dim        = {0.470, 0.500, 0.550},
  blocked    = {0.880, 0.330, 0.290},
}

-- How large a body is drawn, in paces, by whether it has a reach. Two numbers rather
-- than the real viewer's table-per-archetype: the arena has no captains, heroes or
-- monsters, and a table indexed by archetype would be a thing to keep in step for no
-- benefit.
--
-- Drawn generously larger than the room a body keeps, which is the opposite of the
-- rule the match renderer follows. A match is a map and its bodies are weather; an
-- arena is a diagram of six soldiers and the reader has to be able to tell them apart
-- individually. The ring showing a body's personal space is drawn at its true size, so
-- the honest number is still on the screen next to the generous one.
local BODY_SIZE = {melee = 9.0, reach = 10.0}

-- {{{ local function fit()
-- The transform from arena paces to screen pixels.
--
-- The arena is small and fixed, so it is framed once and never panned or zoomed. That
-- is the whole camera. A pan-and-zoom camera is right for a map you are exploring and
-- is pure overhead for a rectangle that fits on the screen with room to spare.
local function fit(world)
  local lane = world.map.lane[1]
  local first = world.map.node[lane.path[1]]
  local last = world.map.node[lane.path[#lane.path]]
  local half = lane.width * 0.5

  -- Framed on **the road**, not on the arena's outer bounds. The bounds carry a wide
  -- margin so that a body stepping aside has somewhere to step, and framing that empty
  -- ground would spend a quarter of the window on nothing. The margin is still there
  -- and a body that walks into it is still drawn -- it is simply not what the window
  -- is sized around.
  local span_x = (last.x - first.x) + lane.width
  local span_y = lane.width * 2.2

  local width = love.graphics.getWidth()
  local height = love.graphics.getHeight()
  local scale = math.min((width - 60) / span_x, (height - 240) / span_y)

  local view = {
    scale = scale,
    offset_x = (width - span_x * scale) * 0.5 - (first.x - lane.width * 0.5) * scale,
    offset_y = 90 - (first.y - span_y * 0.5) * scale,
  }
  -- Where the ground ends, so the readout can sit under it rather than at the bottom
  -- of whatever shape the window happens to be. On a tall narrow display the two were
  -- a screen apart, and a caption you have to look away from the picture to read is a
  -- caption about a different picture.
  view.ground_bottom = view.offset_y + (first.y + half) * scale
  return view
end
-- }}}

-- {{{ local function to_screen()
local function to_screen(view, x, y)
  return view.offset_x + x * view.scale, view.offset_y + y * view.scale
end
-- }}}

-- {{{ function M.load()
-- Reads the scene, builds the arena it asks for, and puts the bodies on the ground.
--
-- The scene names the mechanics. Nothing here decides what a test needs, because the
-- thing that knows is the file describing the test -- and a viewer that quietly added
-- a module because a scene looked like it might want it would be exactly the coupling
-- this whole arrangement exists to remove.
function M.load(root, scene_name)
  local tick_module = loadfile(root .. "/src/042-the-tick.lua")()
  local modules = tick_module.load_cast(root)
  local arena = loadfile(root .. "/src/068-the-arena.lua")()

  local path = root .. "/scenes/" .. scene_name .. ".lua"
  local chunk, message = loadfile(path)
  if chunk == nil then
    error("no scene at " .. path .. ": " .. tostring(message))
  end
  local scene = chunk()

  local world = arena.assemble(modules, modules.match_parameters.load(),
                               scene.want, scene.arena)
  scene.setup(world, arena)

  M.root = root
  M.arena = arena
  M.world = world
  M.scene = scene
  -- Held, for the same reason a scenario is held: the most useful moment when
  -- something is going wrong is almost always the tick before it does, and a test that
  -- starts running the instant it loads cannot be looked at then.
  M.paused = true
  M.speed = 1
  M.accumulated = 0
  M.font = love.graphics.newFont(13)
  M.font_small = love.graphics.newFont(11)
  M.font_title = love.graphics.newFont(17)
  love.graphics.setBackgroundColor(COLOUR.backdrop)

  local into = os.getenv("HLM_CAPTURE")
  if into ~= nil and into ~= "" then
    M.capture = {into = into, at = tonumber(os.getenv("HLM_CAPTURE_AT") or "500") or 500}
    M.paused = false
  end
end
-- }}}

-- {{{ function M.update()
-- Advances the scene's own mechanics at the scene's own rate.
--
-- Ticks are whole and the clock is the simulation's, not the frame's: a body moves the
-- same distance per tick whatever the machine is doing, which is what makes two runs
-- of a scene comparable to each other.
function M.update(dt)
  -- **Photographing a scene.** Run this many ticks, take the picture, quit -- so that
  -- a scene can appear in a document, or in a message to somebody who is not sitting
  -- at this machine, without anybody having to be at the keyboard at the right moment.
  -- The tick is exact rather than a wall-clock delay, so the same request twice
  -- produces the same picture.
  if M.capture ~= nil then
    while M.world.tick < M.capture.at do
      M.arena.march_tick(M.world)
    end
    return
  end

  if M.paused then
    return
  end
  local per_second = M.world.parameters.unit.ticks_per_second * M.speed
  M.accumulated = M.accumulated + dt * per_second
  while M.accumulated >= 1 do
    M.accumulated = M.accumulated - 1
    M.arena.march_tick(M.world)
  end
end
-- }}}

-- {{{ local function draw_ground()
-- The lane, as a band across the arena, with its edges marked.
--
-- Drawn from the lane's own path and width rather than from the arena's numbers, so
-- that if the two ever disagree the picture shows the lane the bodies are walking
-- rather than the one the test thought it asked for.
local function draw_ground(world, view)
  local lane = world.map.lane[1]
  local first = world.map.node[lane.path[1]]
  local last = world.map.node[lane.path[#lane.path]]
  local half = lane.width * 0.5

  local x1, y1 = to_screen(view, first.x, first.y - half)
  local x2, y2 = to_screen(view, last.x, last.y + half)

  love.graphics.setColor(COLOUR.ground)
  love.graphics.rectangle("fill", x1, y1, x2 - x1, y2 - y1)
  love.graphics.setColor(COLOUR.ground_rim)
  love.graphics.setLineWidth(1)
  love.graphics.rectangle("line", x1, y1, x2 - x1, y2 - y1)

  -- The centre line, so that "how far across the road is that body" is a thing the eye
  -- can answer rather than a thing to measure.
  local cx1, cy = to_screen(view, first.x, first.y)
  local cx2 = to_screen(view, last.x, last.y)
  love.graphics.setColor(COLOUR.ground_rim[1], COLOUR.ground_rim[2],
                         COLOUR.ground_rim[3], 0.5)
  love.graphics.line(cx1, cy, cx2, cy)

  -- Milestone marks. The arena has the same nine a real lane has, and they are the
  -- only distance scale on the screen.
  for m = 0, world.parameters.shape.milestone_count - 1 do
    local node = world.map.node[lane.milestone_node[m]]
    local mx, top = to_screen(view, node.x, node.y - half)
    local _, bottom = to_screen(view, node.x, node.y + half)
    love.graphics.setColor(COLOUR.ground_rim[1], COLOUR.ground_rim[2],
                           COLOUR.ground_rim[3], 0.55)
    love.graphics.line(mx, top, mx, bottom)
  end
end
-- }}}

-- {{{ local function draw_bodies()
-- Every living body, and what it is doing.
--
-- Discs for melee and wedges for anything with a reach, the same distinction the real
-- renderer draws, because a person moving between the two windows should not have to
-- learn two vocabularies. A body the queue is currently stopping is ringed in red --
-- which the real viewer does not show and this one must, because "who is blocked" is
-- the entire question the first scene asks.
local function draw_bodies(world, view)
  local soldier = world.soldier
  local blocked_count = 0

  for id = 1, world.high_water do
    if soldier.alive[id] == 1 then
      local x, y = to_screen(view, soldier.x[id], soldier.y[id])
      local stray = (soldier.wave[id] == 0)
      local size = (soldier.reach[id] == 2 and BODY_SIZE.reach or BODY_SIZE.melee)
                   * view.scale
      if size < 2.5 then size = 2.5 end

      local colour = stray and COLOUR.stray or COLOUR.team[soldier.team[id]]
      love.graphics.setColor(colour)
      if soldier.reach[id] == 2 then
        love.graphics.polygon("fill",
          x, y - size, x + size * 0.9, y + size * 0.7, x - size * 0.9, y + size * 0.7)
      else
        love.graphics.circle("fill", x, y, size, 14)
      end

      -- A stray is what an army has to get past, so it is drawn as a thing in the way
      -- rather than as one more soldier: its own colour and a ring of the room it
      -- keeps around itself, which is the distance the queue rule actually measures.
      if stray then
        local space = world.parameters.shape.personal_space * view.scale
        love.graphics.setColor(colour[1], colour[2], colour[3], 0.28)
        love.graphics.circle("line", x, y, space, 28)
      end

      if world.frontline ~= nil and soldier.wave[id] ~= 0
         and world.frontline.blocked(world, id) then
        blocked_count = blocked_count + 1
        love.graphics.setColor(COLOUR.blocked)
        love.graphics.setLineWidth(1.5)
        love.graphics.circle("line", x, y, size + 3.5, 16)
      end
    end
  end

  return blocked_count
end
-- }}}

-- {{{ local function draw_readout()
-- The numbers the scene is about, under the ground rather than over it.
--
-- Deliberately few. A readout that printed everything would be a panel, and a panel is
-- the thing this window exists to not have.
local function draw_readout(world, view, blocked_count)
  local soldier = world.soldier
  -- Under the ground, wherever the ground turned out to end.
  local top = view.ground_bottom + 40
  local front, back, marching, total = -math.huge, math.huge, 0, 0

  for id = 1, world.high_water do
    if soldier.alive[id] == 1 and soldier.wave[id] ~= 0 then
      total = total + 1
      local along = soldier.lane_along[id]
      if along > front then front = along end
      if along < back then back = along end
      if world.frontline == nil or not world.frontline.blocked(world, id) then
        marching = marching + 1
      end
    end
  end
  if total == 0 then front, back = 0, 0 end

  love.graphics.setFont(M.font_title)
  love.graphics.setColor(COLOUR.text)
  love.graphics.print(M.scene.name, 40, top)

  love.graphics.setFont(M.font)
  love.graphics.setColor(COLOUR.dim)
  love.graphics.printf(M.scene.caption, 40, top + 28,
                       love.graphics.getWidth() - 80)

  love.graphics.setFont(M.font_small)
  love.graphics.setColor(COLOUR.text)
  love.graphics.print(string.format(
    "tick %d      formation front %.0f   back %.0f   depth %.0f      marching %d of %d      blocked %d",
    world.tick, front, back, front - back, marching, total, blocked_count),
    40, top + 96)

  love.graphics.setColor(COLOUR.dim)
  love.graphics.print(
    "P pauses and starts  --  1 2 3 speed  --  R reloads the scene from the beginning  --  ESC closes",
    40, top + 116)

  if M.paused then
    love.graphics.setColor(COLOUR.stray)
    love.graphics.print("HELD", love.graphics.getWidth() - 90, top + 96)
  end

  -- What the scene declared it was running. On the screen rather than in the file,
  -- because the honesty of the whole arrangement rests on it: a person looking at a
  -- picture should be able to see which machinery made it.
  love.graphics.setColor(COLOUR.dim)
  love.graphics.print("mechanics: " .. table.concat(M.scene.want, ", "), 40, 32)

  -- And why, when a module is here for something other than the obvious reason. The
  -- spatial grid lives inside the targeting module, so a scene about queueing has to
  -- name targeting without anything in it ever picking a target -- and a reader who
  -- sees the word and concludes there is combat has been misled by a true statement.
  if M.scene.note ~= nil then
    love.graphics.printf(M.scene.note, 40, 50, love.graphics.getWidth() - 80)
  end
end
-- }}}

-- {{{ function M.draw()
function M.draw()
  local world = M.world
  local view = fit(world)
  draw_ground(world, view)
  local blocked_count = draw_bodies(world, view)
  draw_readout(world, view, blocked_count)

  -- Written after the frame is drawn and before it is shown, which is the only moment
  -- the finished picture exists.
  if M.capture ~= nil and world.tick >= M.capture.at then
    love.graphics.captureScreenshot(function(image)
      image:encode("png", "arena-shot.png")
      -- LOVE writes into its own save directory and will not write anywhere else, so
      -- the file is moved into place afterwards by the script that asked for it. The
      -- path it lands in is printed rather than assumed.
      print(love.filesystem.getSaveDirectory() .. "/arena-shot.png")
      love.event.quit()
    end)
    M.capture = nil
  end
end
-- }}}

-- {{{ function M.keypressed()
function M.keypressed(key)
  if key == "p" or key == "space" then
    M.paused = not M.paused
  elseif key == "1" then M.speed = 1
  elseif key == "2" then M.speed = 3
  elseif key == "3" then M.speed = 8
  elseif key == "r" then
    -- From the beginning, in the same window. A scene is cheap to build and watching
    -- the same twenty seconds again is most of how one of these is read.
    M.load(M.root, M.scene.file)
  elseif key == "escape" then
    love.event.quit()
  end
end
-- }}}

function M.resize() end
function M.wheelmoved() end
function M.mousepressed() end
function M.mousereleased() end
function M.mousemoved() end

return M
