#!/bin/bash
# =============================================================================
# Neocities Modernization - Dependency Installation Script
# Installs all external dependencies locally to this project
#
# This script orchestrates installation of:
#   - Effil (Lua multithreading library)
#   - Other dependencies as needed
#
# Usage: ./scripts/install-deps.sh [--clean] [--check]
# =============================================================================

set -euo pipefail

# {{{ Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
LIBS_DIR="${PROJECT_DIR}/libs"
NATIVE_LIBS_DIR="${LIBS_DIR}/native"

# Effil configuration
EFFIL_VERSION="1.2.0"
EFFIL_REPO="https://github.com/effil/effil.git"
EFFIL_TAG="v${EFFIL_VERSION}"
EFFIL_DIR="${NATIVE_LIBS_DIR}/effil"

# Use LuaJIT for this project (parallel processing)
LUA_VERSION="luajit"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
# }}}

# {{{ check_dependencies
check_dependencies() {
    log_info "Checking system dependencies..."

    local missing=()

    command -v cmake &>/dev/null || missing+=("cmake")
    command -v git &>/dev/null || missing+=("git")
    command -v g++ &>/dev/null || command -v clang++ &>/dev/null || missing+=("g++ or clang++")
    command -v luajit &>/dev/null || missing+=("luajit")

    if [[ ${#missing[@]} -gt 0 ]]; then
        log_error "Missing: ${missing[*]}"
        echo "Install with: sudo apt-get install cmake git g++ luajit libluajit-5.1-dev"
        return 1
    fi

    log_info "All system dependencies found"
    return 0
}
# }}}

# {{{ install_effil
install_effil() {
    log_info "Installing Effil (Lua multithreading)..."

    # Check if already built
    if [[ -f "${EFFIL_DIR}/build/effil.so" ]]; then
        log_info "Effil already installed"
        return 0
    fi

    mkdir -p "$NATIVE_LIBS_DIR"

    # Clone if needed
    if [[ ! -d "${EFFIL_DIR}/.git" ]]; then
        log_info "Cloning Effil..."
        git clone --depth 1 --branch "$EFFIL_TAG" "$EFFIL_REPO" "$EFFIL_DIR"
        cd "$EFFIL_DIR"
        git submodule update --init --recursive
    fi

    # Build
    log_info "Building Effil..."
    mkdir -p "${EFFIL_DIR}/build"
    cd "${EFFIL_DIR}/build"

    # Find LuaJIT paths
    local lua_include="/usr/include/luajit-2.1"
    [[ ! -d "$lua_include" ]] && lua_include="/usr/include/luajit-2.0"

    cmake .. \
        -DCMAKE_BUILD_TYPE=Release \
        -DLUA_INCLUDE_DIR="$lua_include"

    make -j"$(nproc)"

    log_info "Effil built successfully"
    cd "$PROJECT_DIR"
}
# }}}

# {{{ create_lua_paths
create_lua_paths() {
    local paths_file="${LIBS_DIR}/paths.lua"

    log_info "Creating Lua paths configuration..."

    cat > "$paths_file" << 'EOF'
-- Auto-generated by install-deps.sh
-- Add this at the start of your Lua scripts:
--   dofile('libs/paths.lua')

local project_root = debug.getinfo(1, "S").source:match("@(.*/)")
if project_root then
    project_root = project_root:gsub("/libs/$", "")
else
    project_root = "."
end

-- Add native library paths (effil.so)
package.cpath = package.cpath .. ";" .. project_root .. "/libs/native/effil/build/?.so"

-- Add Lua library paths
package.path = package.path .. ";" .. project_root .. "/libs/?.lua"
package.path = package.path .. ";" .. project_root .. "/src/?.lua"

return project_root
EOF

    log_info "Created: $paths_file"
}
# }}}

# {{{ verify_installation
verify_installation() {
    log_info "Verifying installation..."

    cd "$PROJECT_DIR"

    # Test effil
    if luajit -e "package.cpath = './libs/native/effil/build/?.so;' .. package.cpath; local e = require('effil'); print('Effil OK, threads:', e.hardware_threads())" 2>/dev/null; then
        log_info "Effil: OK"
    else
        log_error "Effil: FAILED"
        return 1
    fi

    return 0
}
# }}}

# {{{ clean
clean() {
    log_info "Cleaning native libraries..."
    rm -rf "$NATIVE_LIBS_DIR"
    log_info "Cleaned"
}
# }}}

# {{{ show_usage
show_usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --check    Check if dependencies are installed"
    echo "  --clean    Remove all installed native libraries"
    echo "  --help     Show this help"
}
# }}}

# {{{ main
main() {
    cd "$PROJECT_DIR"

    case "${1:-}" in
        --check)
            check_dependencies && verify_installation
            exit $?
            ;;
        --clean)
            clean
            exit 0
            ;;
        --help|-h)
            show_usage
            exit 0
            ;;
    esac

    echo ""
    echo -e "${CYAN}=== Neocities Modernization Dependency Installer ===${NC}"
    echo ""

    check_dependencies || exit 1

    install_effil
    create_lua_paths
    verify_installation

    echo ""
    log_info "Installation complete!"
    echo ""
    echo "To use in your Lua scripts, add at the top:"
    echo "  dofile('libs/paths.lua')"
    echo ""
    echo "Or manually add to package.cpath:"
    echo "  package.cpath = './libs/native/effil/build/?.so;' .. package.cpath"
    echo ""
}

main "$@"
# }}}
