#!/usr/bin/env luajit
-- Test suite for j.lua (JASS script parser)
-- Tests parsing against synthetic JASS data since test maps lack war3map.j files.
-- Run from project root: luajit src/tests/test_j.lua

local DIR = "/mnt/mtwo/programming/ai-stuff/world-edit-to-execute"
package.path = DIR .. "/src/?.lua;" .. DIR .. "/src/?/init.lua;" .. package.path

local j = require("parsers.j")
local mpq = require("mpq")

-- {{{ Test configuration
local TEST_MAPS_DIR = DIR .. "/assets"
local VERBOSE = os.getenv("VERBOSE") == "1"
-- }}}

-- {{{ Test utilities
local tests_run = 0
local tests_passed = 0
local tests_failed = 0

-- {{{ log
local function log(...)
    if VERBOSE then
        print(...)
    end
end
-- }}}

-- {{{ assert_true
local function assert_true(value, message)
    tests_run = tests_run + 1
    if value then
        tests_passed = tests_passed + 1
        return true
    else
        tests_failed = tests_failed + 1
        print(string.format("  FAIL: %s", message or "expected true"))
        return false
    end
end
-- }}}

-- {{{ assert_eq
local function assert_eq(actual, expected, message)
    tests_run = tests_run + 1
    if actual == expected then
        tests_passed = tests_passed + 1
        return true
    else
        tests_failed = tests_failed + 1
        print(string.format("  FAIL: %s", message or "assertion failed"))
        print(string.format("    expected: %s", tostring(expected)))
        print(string.format("    actual:   %s", tostring(actual)))
        return false
    end
end
-- }}}

-- {{{ assert_gt
local function assert_gt(actual, threshold, message)
    tests_run = tests_run + 1
    if actual > threshold then
        tests_passed = tests_passed + 1
        return true
    else
        tests_failed = tests_failed + 1
        print(string.format("  FAIL: %s", message or "expected greater than"))
        print(string.format("    threshold: %s", tostring(threshold)))
        print(string.format("    actual:    %s", tostring(actual)))
        return false
    end
end
-- }}}

-- {{{ get_map_files
local function get_map_files()
    local files = {}
    local handle = io.popen('ls "' .. TEST_MAPS_DIR .. '"/*.w3x 2>/dev/null')
    if handle then
        for line in handle:lines() do
            files[#files + 1] = line
        end
        handle:close()
    end
    return files
end
-- }}}
-- }}}

-- {{{ Synthetic JASS data
-- Minimal valid JASS with globals, main, and config
local MINIMAL_JASS = [[
globals
    trigger gg_trg_Init = null
endglobals

function main takes nothing returns nothing
    call DisplayTextToPlayer(Player(0), 0, 0, "Hello World")
endfunction

function config takes nothing returns nothing
    call SetMapName("Test Map")
endfunction
]]

-- Full JASS with all features
local FULL_JASS = [[
// Test map header comment
// Generated by World Editor

globals
    // Generated trigger handles
    trigger gg_trg_Init = null
    trigger gg_trg_Combat = null

    // Generated unit handles
    unit gg_unit_Archmage_0000 = null

    // User-defined globals
    integer udg_PlayerScore = 0
    real udg_DamageMultiplier = 1.50
    string udg_MapVersion = "1.0"
    boolean udg_IsGameOver = false
    integer array udg_Inventory
endglobals

function Trig_Init_Conditions takes nothing returns boolean
    return GetTriggerPlayer() == Player(0)
endfunction

function Trig_Init_Actions takes nothing returns nothing
    set udg_PlayerScore = 0
    call DisplayTextToPlayer(Player(0), 0, 0, "Game Initialized")
endfunction

function InitTrig_Init takes nothing returns nothing
    set gg_trg_Init = CreateTrigger()
    call TriggerAddCondition(gg_trg_Init, Condition(function Trig_Init_Conditions))
    call TriggerAddAction(gg_trg_Init, function Trig_Init_Actions)
endfunction

function Trig_Combat_Conditions takes nothing returns boolean
    return true
endfunction

function Trig_Combat_Actions takes nothing returns nothing
    local unit u = GetTriggerUnit()
    call SetUnitLifePercentBJ(u, 100)
endfunction

function InitTrig_Combat takes nothing returns nothing
    set gg_trg_Combat = CreateTrigger()
    call TriggerAddCondition(gg_trg_Combat, Condition(function Trig_Combat_Conditions))
    call TriggerAddAction(gg_trg_Combat, function Trig_Combat_Actions)
endfunction

function CustomHelper takes integer value returns integer
    return value * 2
endfunction

function main takes nothing returns nothing
    call SetCameraBounds(-3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    call InitTrig_Init()
    call InitTrig_Combat()
endfunction

function config takes nothing returns nothing
    call SetMapName("Test Combat Map")
    call SetMapDescription("A test map for combat mechanics")
    call SetPlayers(4)
    call SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
endfunction
]]

-- JASS with only globals (missing functions)
local GLOBALS_ONLY_JASS = [[
globals
    integer udg_Test = 42
endglobals
]]

-- JASS with unbalanced blocks
local UNBALANCED_JASS = [[
globals
    integer x = 1

function main takes nothing returns nothing
endfunction

function config takes nothing returns nothing
endfunction
]]

-- Empty content
local EMPTY_JASS = ""
-- }}}

-- {{{ Test: Parse minimal JASS
print("=== Test: Parse Minimal JASS ===")
print()

local parsed = j.parse(MINIMAL_JASS)

assert_true(parsed ~= nil, "parse() should return result")
assert_true(parsed.globals ~= nil, "Should find globals section")
assert_true(parsed.has_main, "Should find main()")
assert_true(parsed.has_config, "Should find config()")
assert_eq(#parsed.functions, 2, "Should find 2 functions")
assert_eq(#parsed.variables, 1, "Should find 1 variable")

local valid, errors = j.validate(parsed)
assert_true(valid, "Minimal JASS should be valid")
assert_eq(#errors, 0, "Should have no validation errors")

log("Minimal JASS parsed successfully")
print()
-- }}}

-- {{{ Test: Parse full JASS
print("=== Test: Parse Full JASS ===")
print()

parsed = j.parse(FULL_JASS)

assert_true(parsed ~= nil, "parse() should return result")
assert_true(parsed.globals ~= nil, "Should find globals section")
assert_true(parsed.has_main, "Should find main()")
assert_true(parsed.has_config, "Should find config()")

-- Check function count (9 functions in FULL_JASS)
assert_eq(#parsed.functions, 9, "Should find 9 functions")

-- Check variable count (8 variables in FULL_JASS)
assert_eq(#parsed.variables, 8, "Should find 8 variables")

-- Check user-defined globals
local user_globals = j.get_user_globals(parsed)
assert_eq(#user_globals, 5, "Should find 5 user-defined globals (udg_*)")

-- Check trigger globals
local trigger_globals = j.get_trigger_globals(parsed)
assert_eq(#trigger_globals, 2, "Should find 2 trigger globals (gg_trg_*)")

-- Check functions by type
local trigger_conditions = j.get_functions_by_type(parsed, "trigger_condition")
assert_eq(#trigger_conditions, 2, "Should find 2 trigger condition functions")

local trigger_actions = j.get_functions_by_type(parsed, "trigger_action")
assert_eq(#trigger_actions, 2, "Should find 2 trigger action functions")

local trigger_inits = j.get_functions_by_type(parsed, "trigger_init")
assert_eq(#trigger_inits, 2, "Should find 2 trigger init functions")

local custom_funcs = j.get_functions_by_type(parsed, "custom")
assert_eq(#custom_funcs, 1, "Should find 1 custom function")

-- Validate
valid, errors = j.validate(parsed)
assert_true(valid, "Full JASS should be valid")

log("Full JASS parsed successfully")
print()
-- }}}

-- {{{ Test: Function lookup
print("=== Test: Function Lookup ===")
print()

local main_func = j.get_function_by_name(parsed, "main")
assert_true(main_func ~= nil, "Should find main() by name")
assert_eq(main_func.type, "entry_main", "main() should have entry_main type")
assert_eq(main_func.takes, "nothing", "main() takes nothing")
assert_eq(main_func.returns, "nothing", "main() returns nothing")

local custom_func = j.get_function_by_name(parsed, "CustomHelper")
assert_true(custom_func ~= nil, "Should find CustomHelper by name")
assert_eq(custom_func.type, "custom", "CustomHelper should have custom type")
assert_eq(custom_func.takes, "integer value", "CustomHelper takes integer value")
assert_eq(custom_func.returns, "integer", "CustomHelper returns integer")

local nonexistent = j.get_function_by_name(parsed, "DoesNotExist")
assert_true(nonexistent == nil, "Should return nil for nonexistent function")

print()
-- }}}

-- {{{ Test: Variable parsing
print("=== Test: Variable Parsing ===")
print()

-- Find specific variables
local found_score = false
local found_inventory = false
for _, var in ipairs(parsed.variables) do
    if var.name == "udg_PlayerScore" then
        found_score = true
        assert_eq(var.type, "integer", "udg_PlayerScore should be integer")
        assert_eq(var.initial_value, "0", "udg_PlayerScore should be initialized to 0")
        assert_eq(var.is_array, false, "udg_PlayerScore should not be array")
    elseif var.name == "udg_Inventory" then
        found_inventory = true
        assert_eq(var.type, "integer", "udg_Inventory should be integer")
        assert_eq(var.is_array, true, "udg_Inventory should be array")
    end
end

assert_true(found_score, "Should find udg_PlayerScore variable")
assert_true(found_inventory, "Should find udg_Inventory array variable")

print()
-- }}}

-- {{{ Test: Validation - missing entry points
print("=== Test: Validation - Missing Entry Points ===")
print()

parsed = j.parse(GLOBALS_ONLY_JASS)
assert_true(parsed ~= nil, "Should parse globals-only JASS")
assert_true(parsed.globals ~= nil, "Should find globals section")
assert_eq(parsed.has_main, false, "Should not find main()")
assert_eq(parsed.has_config, false, "Should not find config()")

valid, errors = j.validate(parsed)
assert_eq(valid, false, "Globals-only JASS should be invalid")
assert_gt(#errors, 0, "Should have validation errors")

-- Check for specific errors
local has_main_error = false
local has_config_error = false
for _, err in ipairs(errors) do
    if err:match("main") then has_main_error = true end
    if err:match("config") then has_config_error = true end
end
assert_true(has_main_error, "Should have error about missing main()")
assert_true(has_config_error, "Should have error about missing config()")

print()
-- }}}

-- {{{ Test: Validation - unbalanced blocks
print("=== Test: Validation - Unbalanced Blocks ===")
print()

parsed = j.parse(UNBALANCED_JASS)
assert_true(parsed ~= nil, "Should parse unbalanced JASS")

valid, errors = j.validate(parsed)
assert_eq(valid, false, "Unbalanced JASS should be invalid")

-- Check for unbalanced globals error
local has_globals_error = false
for _, err in ipairs(errors) do
    if err:match("globals") then has_globals_error = true end
end
assert_true(has_globals_error, "Should have error about unbalanced globals")

print()
-- }}}

-- {{{ Test: Empty content
print("=== Test: Empty Content ===")
print()

parsed = j.parse(EMPTY_JASS)
assert_true(parsed ~= nil, "Should return result for empty content")
assert_eq(parsed.raw, "", "Raw should be empty")
assert_eq(parsed.globals, nil, "Should have no globals")
assert_eq(#parsed.functions, 0, "Should have no functions")

valid, errors = j.validate(parsed)
assert_eq(valid, false, "Empty JASS should be invalid")
assert_gt(#errors, 0, "Should have validation errors")

print()
-- }}}

-- {{{ Test: Format output
print("=== Test: Format Output ===")
print()

parsed = j.parse(FULL_JASS)
local formatted = j.format(parsed)

assert_true(formatted ~= nil, "format() should return string")
assert_true(#formatted > 0, "Formatted output should not be empty")
assert_true(formatted:match("JASS Script Summary"), "Should have summary header")
assert_true(formatted:match("Functions:"), "Should show function count")
assert_true(formatted:match("main%(%)"), "Should mention main()")
assert_true(formatted:match("config%(%)"), "Should mention config()")
assert_true(formatted:match("PASSED") or formatted:match("FAILED"), "Should show validation status")

log("\nFormatted output:")
log(formatted)

print()
-- }}}

-- {{{ Test: Maps without war3map.j
print("=== Test: Maps Without war3map.j ===")
print()

local maps = get_map_files()
local maps_without_j = 0

for _, map_path in ipairs(maps) do
    local archive = mpq.open(map_path)
    if archive then
        local text, err = j.extract(archive)
        if not text then
            maps_without_j = maps_without_j + 1
            log(string.format("  %s: %s", map_path:match("([^/]+)$"), err))
        end
        archive:close()
    end
end

-- We expect all test maps to lack war3map.j (they're minimal maps)
print(string.format("Maps without war3map.j: %d/%d", maps_without_j, #maps))
assert_eq(maps_without_j, #maps, "All test maps should lack war3map.j (minimal maps)")

print()
-- }}}

-- {{{ Test: Line counting
print("=== Test: Line Counting ===")
print()

parsed = j.parse(MINIMAL_JASS)
assert_gt(parsed.line_count, 0, "Should count lines")

-- Count manually
local manual_count = 1
for _ in MINIMAL_JASS:gmatch("\n") do
    manual_count = manual_count + 1
end
assert_eq(parsed.line_count, manual_count, "Line count should match manual count")

print()
-- }}}

-- {{{ Summary
print("========================================")
print(string.format("JASS Parser Tests: %d/%d passed", tests_passed, tests_run))
if tests_failed == 0 then
    print("All tests PASSED!")
    os.exit(0)
else
    print(string.format("%d tests FAILED", tests_failed))
    os.exit(1)
end
-- }}}
