/*
 * 056-font-8x16.h — the character pictures, as the rest of the system
 * sees them.
 *
 * General description: font_8x16[c][row] is row `row` (0 at the top) of
 * character `c`, one bit per pixel, the leftmost pixel in the highest bit.
 * The table itself (056-font-8x16.c) is generated by scripts/generate-font.
 */
#ifndef SOREN_FONT_8X16_H
#define SOREN_FONT_8X16_H

#include <stdint.h>

#define FONT_WIDTH  8
#define FONT_HEIGHT 16

extern const uint8_t font_8x16[256][16];
extern const int font_8x16_missing;

#endif
