/*
 * 019-probe-engine.c — compiled-in hardware probe battery (issue 110i)
 *
 * Turns a `--debug` build of the kernel into a self-running
 * diagnostic instrument. Every #AUTO-marked probe under input/probes/
 * is generated into a C array (scripts/embed-probes -> probe-list.inc)
 * and compiled in; on boot the kernel arms them from their #NEEDED
 * defaults and runs the armed ones in priority order (issue 110n),
 * logging results to the SD-backed debug log. A normal build
 * defines nothing, so this whole file compiles to an empty object and
 * a production image carries no probe code at all.
 *
 * The probe language is deliberately tiny and dumb — read a register,
 * write a register, dump a range, delay, check a value, or call a
 * whole driver routine by name. No arithmetic, no variables, no
 * control flow. Anything more complex belongs in C.
 *
 * Two safety boundaries keep an arbitrary-MMIO-write instrument from
 * bricking the device:
 *   - writes are only honoured for a probe whose #WRITES marker set
 *     its writes-enabled flag, so a read-only probe cannot poke
 *     anything by accident;
 *   - writes are confined to an allowlist of peripheral register
 *     windows; a write outside is logged and skipped.
 *
 * Reads are unrestricted (reading a register cannot change state).
 *
 * History: this began as an SD-card-driven interpreter the lab tech
 * wrote scripts onto and the kernel read back at boot. The delivery
 * moved in-tree once we accepted that a build flag is already a
 * rebuild (so the no-rebuild benefit was moot) and that we run every
 * probe each time (so there was nothing to select). The interpreter
 * and the script language carried over unchanged. See issue 110i.
 * A later refinement (110k) brought build-time selection back: a
 * per-probe #NEEDED bit keeps a probe compiled in but lets a given
 * build de-select it — selection at build time, which a flag already
 * permits, not the flash-time selection 110i rightly dropped.
 */

#include <stdint.h>

#ifdef SOREN_DEBUG

extern void debug_write(const char *text);

/* Driver entry points reachable from the CALL command. Kept to a
 * small, hand-picked set of no-argument routines — the script can
 * poke arbitrary registers with R/W, so CALL is only for whole
 * bring-up routines that are awkward to express as register pokes. */
extern int  sd_init(void);
extern int  emmc_init(void);
extern int  emmc_read_block(uint32_t lba, uint8_t *buffer);
extern int  emmc_read_ext_csd(uint8_t *buffer);
extern int  emmc_switch_hs200(void);                    /* 012-emmc.c (110j) */
extern int  emmc_switch_hs400(void);                    /* 012-emmc.c (110j) */
extern void emmc_verify(void);                          /* 012-emmc.c (110j) */
extern void emmc_verify_dma(void);                      /* 012-emmc.c (110m) */
extern int  emmc_dump_to_sd(void);                      /* 012-emmc.c (110m) */
extern int  emmc_scan_map(void);                        /* 012-emmc.c (110m) */
extern void sd_probe_capabilities(void);                /* 015-sdmmc.c (110l) */
extern void sd_dma_write_test(void);                    /* 015-sdmmc.c (110m) */
extern void sd_select_speed(void);                      /* 015-sdmmc.c (110l) */
extern void led_pwm_init(void);                         /* 003-pwm.c */
extern void led_bottom(uint32_t current, uint32_t max);
extern void led_top(uint32_t cur_red, uint32_t max_red,
                    uint32_t cur_green, uint32_t max_green);
extern int  emmc_backup_to_sd(uint32_t emmc_start_lba,
                              uint32_t sd_start_lba,
                              uint32_t sector_count);

/* The probe battery is compiled in (issue 110i): a `--debug` build
 * embeds every #AUTO-marked probe under input/probes/ as this array,
 * generated by scripts/embed-probes into probe-list.inc. Each entry
 * carries the probe's name, its writes-enabled flag (#WRITES marker), a
 * needed flag (#NEEDED marker — 1 runs this build, 0 keeps the probe
 * compiled in but de-selected; issue 110k), and the raw script text.
 * The kernel runs the needed probes in priority order on boot and logs
 * a DE-SELECTED banner for the rest — there is no SD probe region, no
 * catalog, and no magic header any more (see the History note up top). */
struct builtin_probe {
    const char *name;
    int         writes_enabled;
    int         needed;          /* default arm state seeded into
                                  * probe_runflags at boot (110k/110n) */
    const char *text;
};
static const struct builtin_probe builtin_probes[] = {
#include "probe-list.inc"
};
static const unsigned builtin_probe_count =
    sizeof(builtin_probes) / sizeof(builtin_probes[0]);

/* enum probe_index — one stable name per probe, sweep order, generated
 * alongside builtin_probes[] (scripts/embed-probes -> probe-index.inc);
 * PROBE_COUNT trails the list. A caller arms a probe by name
 * (probe_arm(PROBE_x)) instead of a magic slot number — the runtime-trigger
 * seam a future button combo or USB console uses (issue 110n). */
enum probe_index {
#include "probe-index.inc"
    PROBE_COUNT
};

/* probe_runflags — the mutable run-list run_probes() walks: one byte per
 * probe, sweep order, 1 = armed and 0 = idle/already-ran. Seeded at boot
 * from each probe's #NEEDED default (probe_seed_defaults) and settable by
 * any code (probe_arm). This is what makes selection a runtime property
 * rather than the compile-time-fixed `needed` field, which is now only the
 * default the array is seeded from (issue 110n). The `? : 1` keeps the
 * array non-zero-length in the degenerate no-probes build. */
static uint8_t probe_runflags[PROBE_COUNT ? PROBE_COUNT : 1];

#define PROBE_BUF_BYTES (32u * 512u)    /* 16 KB line-split scratch */

extern void debug_log_flush(void);      /* flush the log between probes */

/* Line-split scratch (.bss, no allocator). Each probe's text is a
 * .rodata string literal and must not be written in place, so it is
 * copied here to NUL-terminate lines for the interpreter. */
static uint8_t probe_buf[PROBE_BUF_BYTES];

/* MMIO accessors. */
static inline uint32_t mmio_r32(uint32_t a) { return *(volatile uint32_t *)(uintptr_t)a; }
static inline uint16_t mmio_r16(uint32_t a) { return *(volatile uint16_t *)(uintptr_t)a; }
static inline uint8_t  mmio_r8 (uint32_t a) { return *(volatile uint8_t  *)(uintptr_t)a; }
static inline void mmio_w32(uint32_t a, uint32_t v) { *(volatile uint32_t *)(uintptr_t)a = v; }
static inline void mmio_w16(uint32_t a, uint16_t v) { *(volatile uint16_t *)(uintptr_t)a = v; }
static inline void mmio_w8 (uint32_t a, uint8_t  v) { *(volatile uint8_t  *)(uintptr_t)a = v; }

static void busy_delay(uint32_t n)
{
    volatile uint32_t r = n;
    while (r--) { __asm__ volatile ("nop"); }
}

/* {{{ helpers — tiny freestanding string / number parsing */

static int streq(const char *a, const char *b)
{
    while (*a && *b) { if (*a != *b) return 0; a++; b++; }
    return *a == *b;
}

/* Emit a 32-bit value as `0xXXXXXXXX` through debug_write. */
static void write_hex32(uint32_t v)
{
    static const char d[] = "0123456789ABCDEF";
    char buf[11];
    buf[0] = '0'; buf[1] = 'x';
    for (int i = 0; i < 8; i++) buf[2 + i] = d[(v >> ((7 - i) * 4)) & 0xFu];
    buf[10] = 0;
    debug_write(buf);
}

/* Skip spaces and tabs. */
static const char *skip_ws(const char *p)
{
    while (*p == ' ' || *p == '\t') p++;
    return p;
}

/* Read a whitespace-delimited token into out[], NUL-terminated.
 * Returns the token length and advances *pp past it. */
static int read_token(const char **pp, char *out, int max)
{
    const char *p = skip_ws(*pp);
    int n = 0;
    while (*p && *p != ' ' && *p != '\t' && n < max - 1) out[n++] = *p++;
    out[n] = 0;
    *pp = p;
    return n;
}

/* Parse a hex number (optional 0x prefix). Sets *ok to whether any
 * hex digits were consumed; advances *pp. */
static uint32_t parse_hex(const char **pp, int *ok)
{
    const char *p = skip_ws(*pp);
    if (p[0] == '0' && (p[1] == 'x' || p[1] == 'X')) p += 2;
    uint32_t v = 0;
    int digits = 0;
    for (;;) {
        char c = *p;
        int dgt;
        if (c >= '0' && c <= '9') dgt = c - '0';
        else if (c >= 'a' && c <= 'f') dgt = c - 'a' + 10;
        else if (c >= 'A' && c <= 'F') dgt = c - 'A' + 10;
        else break;
        v = (v << 4) | (uint32_t)dgt;
        p++; digits++;
    }
    *ok = (digits > 0);
    *pp = p;
    return v;
}

/* Parse a decimal number. */
static uint32_t parse_dec(const char **pp, int *ok)
{
    const char *p = skip_ws(*pp);
    uint32_t v = 0;
    int digits = 0;
    while (*p >= '0' && *p <= '9') { v = v * 10u + (uint32_t)(*p - '0'); p++; digits++; }
    *ok = (digits > 0);
    *pp = p;
    return v;
}

/* }}} */

/* {{{ the write allowlist
 *
 * Writes are confined to the chip's peripheral register space, so
 * a typo'd address cannot scribble over DRAM or the kernel. The
 * range covers the GRF / CRU / PMU blocks (0xFDC0_0000 region) and
 * the main peripheral window (0xFE00_0000 region) catalogued in
 * docs/016-physical-memory-map.md. Reads are not restricted. */
static int write_allowed(uint32_t addr)
{
    if (addr >= 0xFDC00000u && addr < 0xFDE00000u) return 1; /* GRF/CRU/PMU */
    if (addr >= 0xFE000000u && addr < 0xFE800000u) return 1; /* peripherals */
    return 0;
}
/* }}} */

/* {{{ memtest — bounded DRAM pattern test (the DRAM-walk CALL)
 *
 * Tests a fixed 1 MB window at the 1 GB mark of DRAM. That address
 * is chosen to sit far clear of the kernel image (loaded at
 * 0x0200_0000), its stack and .bss, and the page allocator's pool
 * (all in low DRAM), so the test never scribbles on anything live.
 * It writes four marching patterns plus an address-in-address pass
 * and verifies every read-back, reporting the first failing word.
 *
 * This lives in C because a probe script cannot W into DRAM — the
 * write allowlist is peripheral-only on purpose, so a stray W can't
 * corrupt RAM. The DRAM walk is a deliberate, bounded operation, so
 * it belongs behind a CALL. */
#define MEMTEST_BASE  0x40000000u
#define MEMTEST_WORDS (0x100000u / 4u)   /* 1 MB */

static int memtest_check(uint32_t pat)
{
    volatile uint32_t *m = (volatile uint32_t *)(uintptr_t)MEMTEST_BASE;
    for (uint32_t i = 0; i < MEMTEST_WORDS; i++) m[i] = pat;
    for (uint32_t i = 0; i < MEMTEST_WORDS; i++) {
        if (m[i] != pat) {
            debug_write("[probe]   FAIL at ");
            write_hex32(MEMTEST_BASE + i * 4u);
            debug_write(" got=");
            write_hex32(m[i]);
            debug_write(" want=");
            write_hex32(pat);
            debug_write("\r\n");
            return -1;
        }
    }
    return 0;
}

static void memtest_run(void)
{
    static const uint32_t pats[4] = {
        0x00000000u, 0xFFFFFFFFu, 0x55555555u, 0xAAAAAAAAu
    };
    debug_write("[probe] memtest: 1 MB @ 0x40000000\r\n");
    for (int p = 0; p < 4; p++) {
        debug_write("[probe]   pattern ");
        write_hex32(pats[p]);
        debug_write("\r\n");
        if (memtest_check(pats[p]) != 0) return;
    }
    /* Address-in-address: each word holds its own address. Catches
     * stuck address lines that the uniform patterns miss. */
    volatile uint32_t *m = (volatile uint32_t *)(uintptr_t)MEMTEST_BASE;
    for (uint32_t i = 0; i < MEMTEST_WORDS; i++) m[i] = MEMTEST_BASE + i * 4u;
    for (uint32_t i = 0; i < MEMTEST_WORDS; i++) {
        if (m[i] != MEMTEST_BASE + i * 4u) {
            debug_write("[probe]   FAIL addr-test at ");
            write_hex32(MEMTEST_BASE + i * 4u);
            debug_write(" got=");
            write_hex32(m[i]);
            debug_write("\r\n");
            return;
        }
    }
    debug_write("[probe] memtest PASS\r\n");
}
/* }}} */

/* {{{ i2c0 + PMIC dump — read RK817 registers over the PMIC bus
 *
 * The RK817 PMIC sits on i2c0 (0xFDD40000) at 7-bit address 0x20.
 * This brings the i2c0 controller up bare-metal (ungate its PMU-
 * domain clocks, route GPIO0_B1/B2 to the i2c0 function, set a
 * slow safe SCL divider) and reads registers through Rockchip's
 * "register-address then read" transfer mode, per RK3568 TRM
 * Chapter 22. The pmic_dump CALL target reads the first 16 RK817
 * registers and logs them — non-0xFF responses confirm the PMIC is
 * alive on the bus. Interpreting the values (regulator states,
 * battery) needs the RK817 datasheet; this is the reachability +
 * raw-snapshot layer the rest builds on. */
#define I2C0_BASE     0xFDD40000u
#define I2C0_CON      (I2C0_BASE + 0x00u)
#define I2C0_CLKDIV   (I2C0_BASE + 0x04u)
#define I2C0_MRXADDR  (I2C0_BASE + 0x08u)
#define I2C0_MRXRADDR (I2C0_BASE + 0x0Cu)
#define I2C0_MRXCNT   (I2C0_BASE + 0x14u)
#define I2C0_MTXCNT   (I2C0_BASE + 0x10u)
#define I2C0_IPD      (I2C0_BASE + 0x1Cu)
#define I2C0_TXDATA0  (I2C0_BASE + 0x100u)
#define I2C0_RXDATA0  (I2C0_BASE + 0x200u)
#define RK817_ADDR    0x20u

/* Diagnostics captured the instant a read times out, so pmic_dump can
 * report WHY instead of a bare "timeout": a NAK (IPD bit 6) means the
 * bus works but the chip stayed silent (pins / address / its own
 * clock); an all-zero IPD means the controller never ran a transaction
 * at all (its functional clock is gated). */
static uint32_t i2c0_fail_ipd, i2c0_fail_con;

static void i2c0_setup(void)
{
    /* Ungate i2c0's PMU-domain clocks (PMUGATE_CON01 bits 0,1)
     * and release its resets (PMUSOFTRST_CON00 bits 3,4). */
    mmio_w32(0xFDD00184u, 0x00030000u);
    mmio_w32(0xFDD00200u, 0x00180000u);
    /* Route GPIO0_B1 (SCL) and GPIO0_B2 (SDA) to i2c0 function 1
     * in the PMU GRF, and flip the pad source to the i2c0
     * controller rather than the audio codec. */
    mmio_w32(0xFDC20008u, 0x07700110u);
    mmio_w32(0xFDC20100u, 0x00020002u);
    /* Slow, safe SCL divider — a probe doesn't need speed, and a
     * too-fast clock would just NAK. (No write-mask on this IP.) */
    mmio_w32(I2C0_CLKDIV, 0x00FF00FFu);
}

/* Read one 8-bit register from an i2c device. Returns 0 on
 * success with the byte in *out, or -1 on timeout. */
static int i2c0_read_reg(uint32_t dev, uint32_t reg, uint8_t *out)
{
    uint32_t budget;

    /* Canonical Rockchip i2c register read, matching u-boot's rk_i2c.c
     * (saved in tmp/uboot-ref/rk_i2c.c). The order is strict, and our
     * earlier versions got it wrong in three ways: START must be its OWN
     * step first; the slave address must carry the read bit; the
     * transfer CON has NO start bit; and writing MRXCNT *last* is what
     * actually triggers the controller to clock the bus. Writing MRXCNT
     * before CON, and folding START into the mode write, left the
     * controller started but never transferring — the "STARTIPD then
     * nothing" we captured on hardware. */

    /* Step 1 — START on its own: CON = EN | START, wait the start
     * interrupt, clear it. */
    mmio_w32(I2C0_IPD, 0x7Fu);
    mmio_w32(I2C0_CON, 0x09u);                         /* EN | START */
    budget = 1000000u;
    while (!(mmio_r32(I2C0_IPD) & 0x10u)) {            /* STARTIPD */
        if (budget-- == 0u) {
            i2c0_fail_ipd = mmio_r32(I2C0_IPD);
            i2c0_fail_con = mmio_r32(I2C0_CON);
            mmio_w32(I2C0_CON, 0u);
            return -1;
        }
    }
    mmio_w32(I2C0_IPD, 0x10u);                         /* clear STARTIPD */

    /* Step 2 — slave address WITH the read bit, then the register
     * address. In TRX mode the controller sends addr+W, the register
     * address, a restart, then addr+R, so MRXADDR carries the read form. */
    mmio_w32(I2C0_MRXADDR, 0x01000000u | (dev << 1) | 1u);
    mmio_w32(I2C0_MRXRADDR, 0x01000000u | reg);

    /* Step 3 — transfer CON, NO start: EN | mode TRX(01) | NAK-the-last. */
    mmio_w32(I2C0_CON, 0x00000023u);

    /* Step 4 — writing MRXCNT is what triggers the receive. */
    mmio_w32(I2C0_MRXCNT, 1u);

    /* Step 5 — wait for the byte, or a NAK if the chip stays silent. */
    budget = 1000000u;
    for (;;) {
        uint32_t ipd = mmio_r32(I2C0_IPD);
        if (ipd & 0x08u) break;                       /* MBRF — byte ready */
        if (ipd & 0x40u) {                            /* NAK — no ACK */
            i2c0_fail_ipd = ipd;
            i2c0_fail_con = mmio_r32(I2C0_CON);
            mmio_w32(I2C0_IPD, 0x40u);
            mmio_w32(I2C0_CON, 0u);
            return -1;
        }
        if (budget-- == 0u) {
            i2c0_fail_ipd = ipd;
            i2c0_fail_con = mmio_r32(I2C0_CON);
            mmio_w32(I2C0_CON, 0u);
            return -1;
        }
    }
    mmio_w32(I2C0_IPD, 0x08u);                         /* clear MBRF */
    *out = (uint8_t)(mmio_r32(I2C0_RXDATA0) & 0xFFu);

    /* Step 6 — STOP. */
    mmio_w32(I2C0_CON, 0x00000011u);                  /* EN | STOP */
    budget = 1000000u;
    while (!(mmio_r32(I2C0_IPD) & 0x20u)) {            /* STOPIPD */
        if (budget-- == 0u) break;
    }
    mmio_w32(I2C0_IPD, 0x20u);
    mmio_w32(I2C0_CON, 0u);                            /* disable */
    return 0;
}

/* Single-byte register WRITE, matching u-boot rk_i2c_write. TX mode
 * (mode 00) transmits the bytes packed into TXDATA, lower byte first;
 * for a register write the three bytes are [slave<<1 (write), reg,
 * data]. Same shape as the read — START on its own, arm CON, then the
 * count write (MTXCNT) is the trigger. Returns 0 on success. */
static int i2c0_write_reg(uint32_t dev, uint32_t reg, uint8_t val)
{
    uint32_t budget;

    mmio_w32(I2C0_IPD, 0x7Fu);
    mmio_w32(I2C0_CON, 0x09u);                         /* EN | START */
    budget = 1000000u;
    while (!(mmio_r32(I2C0_IPD) & 0x10u)) {            /* STARTIPD */
        if (budget-- == 0u) {
            i2c0_fail_ipd = mmio_r32(I2C0_IPD);
            i2c0_fail_con = mmio_r32(I2C0_CON);
            mmio_w32(I2C0_CON, 0u);
            return -1;
        }
    }
    mmio_w32(I2C0_IPD, 0x10u);                         /* clear STARTIPD */

    /* TXDATA0 byte0 = slave<<1 (write), byte1 = reg, byte2 = value. */
    mmio_w32(I2C0_TXDATA0,
             ((dev << 1) & 0xFFu) | ((reg & 0xFFu) << 8) | ((uint32_t)val << 16));

    mmio_w32(I2C0_CON, 0x01u);                         /* EN | mode TX(00) */
    mmio_w32(I2C0_MTXCNT, 3u);                         /* 3 bytes -> triggers TX */

    budget = 1000000u;
    for (;;) {
        uint32_t ipd = mmio_r32(I2C0_IPD);
        if (ipd & 0x04u) break;                       /* MBTF — bytes sent */
        if (ipd & 0x40u) {                            /* NAK */
            i2c0_fail_ipd = ipd;
            i2c0_fail_con = mmio_r32(I2C0_CON);
            mmio_w32(I2C0_IPD, 0x40u);
            mmio_w32(I2C0_CON, 0u);
            return -1;
        }
        if (budget-- == 0u) {
            i2c0_fail_ipd = ipd;
            i2c0_fail_con = mmio_r32(I2C0_CON);
            mmio_w32(I2C0_CON, 0u);
            return -1;
        }
    }
    mmio_w32(I2C0_IPD, 0x04u);                         /* clear MBTF */

    mmio_w32(I2C0_CON, 0x11u);                         /* EN | STOP */
    budget = 1000000u;
    while (!(mmio_r32(I2C0_IPD) & 0x20u)) {            /* STOPIPD */
        if (budget-- == 0u) break;
    }
    mmio_w32(I2C0_IPD, 0x20u);
    mmio_w32(I2C0_CON, 0u);                            /* disable */
    return 0;
}

/* Log "  label=0xVALUE" for a register readback. */
static void i2c0_log_reg(const char *label, uint32_t addr)
{
    debug_write("[probe]   ");
    debug_write(label);
    debug_write("=");
    write_hex32(mmio_r32(addr));
    debug_write("\r\n");
}

static void pmic_dump(void)
{
    i2c0_setup();

    /* Read the setup back so we can see whether the writes took. These
     * are write-mask registers (upper-16 mask, lower-16 value), so a
     * read returns the live value with the mask half zero — a set bit
     * here means our ungate / route actually landed on the hardware. */
    debug_write("[probe] i2c0 setup readback:\r\n");
    i2c0_log_reg("PMUGATE_CON01@0xFDD00184", 0xFDD00184u);
    i2c0_log_reg("PMUSOFTRST_CON00@0xFDD00200", 0xFDD00200u);
    i2c0_log_reg("GPIO0B_IOMUX@0xFDC20008", 0xFDC20008u);
    i2c0_log_reg("PMU_GRF_SOC_CON0@0xFDC20100", 0xFDC20100u);
    i2c0_log_reg("I2C0_CON@0xFDD40000", I2C0_CON);
    i2c0_log_reg("I2C0_CLKDIV@0xFDD40004", I2C0_CLKDIV);
    /* SCL/SDA idle line levels. GPIO0_EXT_PORT shows the pad level
     * regardless of pin mux (per the TRM): B1=SCL is bit 9, B2=SDA is
     * bit 10. Both high = the bus is idle and the fault is the
     * controller not clocking; either low = that line is stuck (no
     * pull-up, the RK817's codec half holding it, or a routing fault) —
     * which is exactly what freezes a transaction right after START. */
    {
        uint32_t ext = mmio_r32(0xFDD60070u);
        debug_write("[probe]   GPIO0_EXT_PORT@0xFDD60070=");
        write_hex32(ext);
        debug_write("  SCL(bit9)=");
        write_hex32((ext >> 9) & 1u);
        debug_write(" SDA(bit10)=");
        write_hex32((ext >> 10) & 1u);
        debug_write("\r\n");
    }

    debug_write("[probe] RK817 PMIC @ i2c0 0x20, registers 0x00..0x0F:\r\n");
    int reported = 0;
    for (uint32_t reg = 0; reg <= 0x0Fu; reg++) {
        uint8_t v = 0;
        debug_write("[probe]   reg ");
        write_hex32(reg);
        if (i2c0_read_reg(RK817_ADDR, reg, &v) == 0) {
            debug_write(" = ");
            write_hex32((uint32_t)v);
            debug_write("\r\n");
        } else {
            debug_write(" = TIMEOUT");
            if (!reported) {
                /* One-time decode on the first failure. IPD bit 6
                 * (0x40) = NAK received: bus works, chip silent. IPD
                 * all-zero = the controller never transacted at all
                 * (clock/enable). CON still showing start (bit 3) =
                 * it began the transaction but stalled mid-way. */
                debug_write("  [IPD@timeout=");
                write_hex32(i2c0_fail_ipd);
                debug_write(" CON@timeout=");
                write_hex32(i2c0_fail_con);
                debug_write("  (IPD&0x40=NAK, IPD==0=controller idle)]");
                reported = 1;
            }
            debug_write("\r\n");
        }
    }
}
/* }}} */

/* {{{ pmic_write_test — non-destructive RK817 i2c write round-trip
 * Issue 114 layer 2. Writes a distinctive value to the RK817's RTC
 * compensation LSB (reg 0x10 — plain binary, no power rail, safe to
 * change), reads it back to prove the write landed, then restores the
 * original byte. The i2c write itself is i2c0_write_reg above. */
static void pmic_write_test(void)
{
    uint8_t orig = 0, after = 0, restored = 0;
    int w1, w2;

    i2c0_setup();
    debug_write("[probe] RK817 write round-trip on reg 0x10 (RTC_COMP_LSB):\r\n");

    i2c0_read_reg(RK817_ADDR, 0x10u, &orig);
    w1 = i2c0_write_reg(RK817_ADDR, 0x10u, 0x5Au);
    i2c0_read_reg(RK817_ADDR, 0x10u, &after);
    w2 = i2c0_write_reg(RK817_ADDR, 0x10u, orig);     /* restore original */
    i2c0_read_reg(RK817_ADDR, 0x10u, &restored);

    debug_write("[probe]   original=");
    write_hex32((uint32_t)orig);
    debug_write("\r\n[probe]   wrote 0x5A (rc=");
    write_hex32((uint32_t)w1);
    debug_write(") read-back=");
    write_hex32((uint32_t)after);
    debug_write("\r\n[probe]   restored (rc=");
    write_hex32((uint32_t)w2);
    debug_write(") read-back=");
    write_hex32((uint32_t)restored);
    debug_write("\r\n");

    if (w1 == 0 && after == 0x5Au) {
        debug_write("[probe]   WRITE PASS (read-back matched written value)\r\n");
    } else {
        debug_write("[probe]   WRITE FAIL\r\n");
    }
}
/* }}} */

/* Emit a decimal number (no leading zeros) through debug_write — so a
 * voltage logs as "1800 mV" instead of a hex selector. */
static void write_dec(uint32_t v)
{
    char b[11];
    int pos = 10;
    b[10] = 0;
    if (v == 0u) {
        b[--pos] = '0';
    } else {
        while (v != 0u) { b[--pos] = (char)('0' + (v % 10u)); v /= 10u; }
    }
    debug_write(&b[pos]);
}

/* {{{ RK817 LDO voltage control — set a rail to a precise voltage (114 L3)
 * Each of the RK817's nine LDOs (Low-DropOut regulators — they turn a
 * higher rail into a precise lower one) has an ON_VSEL register that
 * selects its output: mV = 600 + sel*25, where sel is the low 7 bits,
 * range 600..3400 mV. LDO n (1..9) lives at register 0xCC + (n-1)*2.
 * Register map from the Linux rk808 driver (tmp/uboot-ref/). This is the
 * "command a rail to an exact voltage" capability — e.g. a 1.8 V I/O
 * rail — that the PWM duty path is NOT (PWM varies time, not voltage). */
#define RK817_LDO_VSEL_BASE  0xCCu
#define RK817_LDO_VSEL_MASK  0x7Fu
#define RK817_LDO_MIN_MV     600u
#define RK817_LDO_STEP_MV    25u
#define RK817_LDO_MAX_MV     3400u

static uint32_t rk817_ldo_vsel_reg(uint32_t ldo)      /* ldo = 1..9 */
{
    return RK817_LDO_VSEL_BASE + (ldo - 1u) * 2u;
}

/* Read LDO n's programmed voltage in millivolts; -1 on an i2c error. */
static int rk817_ldo_get_mv(uint32_t ldo)
{
    uint8_t v = 0;
    if (i2c0_read_reg(RK817_ADDR, rk817_ldo_vsel_reg(ldo), &v) != 0) {
        return -1;
    }
    return (int)(RK817_LDO_MIN_MV
                 + (uint32_t)(v & RK817_LDO_VSEL_MASK) * RK817_LDO_STEP_MV);
}

/* Set LDO n to the highest representable voltage <= target_mv (clamped to
 * the LDO range), preserving the register's non-voltage high bit with a
 * read-modify-write. Returns the voltage actually programmed, or -1. */
static int rk817_ldo_set_mv(uint32_t ldo, uint32_t target_mv)
{
    uint8_t cur = 0, newval;
    uint32_t reg = rk817_ldo_vsel_reg(ldo);
    uint32_t sel;

    if (target_mv < RK817_LDO_MIN_MV) target_mv = RK817_LDO_MIN_MV;
    if (target_mv > RK817_LDO_MAX_MV) target_mv = RK817_LDO_MAX_MV;
    sel = (target_mv - RK817_LDO_MIN_MV) / RK817_LDO_STEP_MV;

    if (i2c0_read_reg(RK817_ADDR, reg, &cur) != 0) {
        return -1;
    }
    newval = (uint8_t)((cur & 0x80u) | (uint8_t)(sel & RK817_LDO_VSEL_MASK));
    if (i2c0_write_reg(RK817_ADDR, reg, newval) != 0) {
        return -1;
    }
    return (int)(RK817_LDO_MIN_MV + sel * RK817_LDO_STEP_MV);
}
/* }}} */

/* {{{ pmic_ldo_test — read every LDO, then prove the set path safely
 * Reads and decodes all nine LDO voltages (a snapshot of the board's
 * power rails), then exercises rk817_ldo_set_mv NON-DESTRUCTIVELY: it
 * reads LDO1's current voltage and programs it right back to the same
 * value, verifying encode/write/read-back without moving any rail. */
static void pmic_ldo_test(void)
{
    uint32_t n;
    int cur, back;

    i2c0_setup();
    debug_write("[probe] RK817 LDO voltages (mV = 600 + sel*25):\r\n");
    for (n = 1u; n <= 9u; n++) {
        int mv = rk817_ldo_get_mv(n);
        debug_write("[probe]   LDO");
        write_dec(n);
        debug_write(" = ");
        if (mv < 0) {
            debug_write("(i2c error)");
        } else {
            write_dec((uint32_t)mv);
            debug_write(" mV");
        }
        debug_write("\r\n");
    }

    cur = rk817_ldo_get_mv(1u);
    debug_write("[probe] set-path check on LDO1: ");
    write_dec((uint32_t)(cur < 0 ? 0 : cur));
    debug_write(" mV -> set same -> ");
    rk817_ldo_set_mv(1u, (uint32_t)(cur < 0 ? (int)RK817_LDO_MIN_MV : cur));
    back = rk817_ldo_get_mv(1u);
    write_dec((uint32_t)(back < 0 ? 0 : back));
    debug_write(" mV  ");
    if (cur >= 0 && back == cur) {
        debug_write("SET PATH OK (unchanged round-trip)\r\n");
    } else {
        debug_write("SET PATH MISMATCH\r\n");
    }
}
/* }}} */

/* {{{ emmc_ext_csd_dump — read the eMMC EXT_CSD, decode HS200 readiness
 * Step 1 of the fast-storage path (110j): confirm the card advertises
 * HS200 before we try to switch it there, and show its current state.
 * DEVICE_TYPE bit 4 = HS200 @ 1.8V. Also surfaces the boot-partition
 * config/size, which the eMMC-overwrite step (110b) will need. */
static void emmc_ext_csd_dump(void)
{
    static uint8_t ext[512];
    int r = emmc_read_ext_csd(ext);
    debug_write("[probe] CALL emmc_ext_csd -> rc=");
    write_hex32((uint32_t)r);
    debug_write("\r\n");
    if (r != 0) {
        debug_write("[probe]   (EXT_CSD read failed)\r\n");
        return;
    }
    debug_write("[probe]   DEVICE_TYPE[196]=");
    write_hex32(ext[196]);
    debug_write((ext[196] & 0x10u) ? "  -> HS200 @ 1.8V SUPPORTED\r\n"
                                   : "  -> no HS200-1.8V bit\r\n");
    debug_write("[probe]   HS_TIMING[185]=");
    write_hex32(ext[185]);
    debug_write("  BUS_WIDTH[183]=");
    write_hex32(ext[183]);
    debug_write("  EXT_CSD_REV[192]=");
    write_hex32(ext[192]);
    debug_write("\r\n");
    debug_write("[probe]   PARTITION_CONFIG[179]=");
    write_hex32(ext[179]);
    debug_write("  BOOT_SIZE_MULT[226]=");
    write_hex32(ext[226]);
    debug_write(" (boot partition = 128 KB * that)\r\n");
}
/* }}} */

/* {{{ cpu_core_recon — the boot core's identity and execution state
 * MIDR_EL1 identifies the core type/revision (the same Cortex-A55 part on
 * all four cores here); MPIDR_EL1's low bits say which physical core we
 * booted on; CurrentEL is the exception level we run at; SCTLR_EL1 bit 0
 * (MMU) and bit 2 (data cache) confirm both are still off in phase 1. The
 * other three cores' state can't be read from here without waking them —
 * that comes at phase-2 multi-core bring-up; this gathers the fixed identity
 * to record once. System registers -> MRS, so this is C, not an R line. */
static void cpu_core_recon(void)
{
    uint64_t midr = 0, mpidr = 0, el = 0, sctlr = 0;
    __asm__ volatile ("mrs %0, midr_el1"  : "=r"(midr));
    __asm__ volatile ("mrs %0, mpidr_el1" : "=r"(mpidr));
    __asm__ volatile ("mrs %0, CurrentEL" : "=r"(el));
    __asm__ volatile ("mrs %0, sctlr_el1" : "=r"(sctlr));

    debug_write("[cpu] MIDR_EL1=");  write_hex32((uint32_t)midr);
    debug_write("  (this core's impl/part/rev)\r\n");
    debug_write("[cpu] MPIDR_EL1="); write_hex32((uint32_t)mpidr);
    debug_write("  booted on core Aff0="); write_dec((uint32_t)(mpidr & 0xFFu));
    debug_write("\r\n[cpu] CurrentEL="); write_hex32((uint32_t)el);
    debug_write("  (EL"); write_dec((uint32_t)((el >> 2) & 0x3u)); debug_write(")\r\n");
    debug_write("[cpu] SCTLR_EL1="); write_hex32((uint32_t)sctlr);
    debug_write((sctlr & 0x1u) ? "  MMU=on" : "  MMU=off");
    debug_write((sctlr & 0x4u) ? "  Dcache=on\r\n" : "  Dcache=off\r\n");
}
/* }}} */

/* {{{ emmc_wear_report — decode the eMMC's wear / lifetime estimate
 * The card reports how much of its rated write life it has used, in the
 * EXT_CSD: PRE_EOL_INFO[267] is a coarse health flag (normal / 80% / 90%
 * consumed), and DEVICE_LIFE_TIME_EST_TYP_A[268] / _B[269] estimate used
 * life in 10% steps (0x01 = 0-10% ... 0x0A = 90-100%, 0x0B = exceeded) for
 * the card's two memory types. Reuses the EXT_CSD read the fast-storage
 * path relies on; read-only. */
static void emmc_wear_report(void)
{
    static uint8_t ext[512];
    int r = emmc_read_ext_csd(ext);
    debug_write("[wear] EXT_CSD read rc="); write_hex32((uint32_t)r); debug_write("\r\n");
    if (r != 0) { debug_write("[wear]   (read failed)\r\n"); return; }

    uint8_t eol = ext[267];
    debug_write("[wear] PRE_EOL_INFO[267]="); write_hex32(eol);
    debug_write(eol == 0x01u ? "  -> NORMAL (<80% consumed)\r\n" :
                eol == 0x02u ? "  -> WARNING (80% consumed)\r\n" :
                eol == 0x03u ? "  -> URGENT (90% consumed)\r\n" :
                               "  -> (not reported)\r\n");

    for (int t = 0; t < 2; t++) {
        uint8_t est = ext[268 + t];
        debug_write(t == 0 ? "[wear] LIFE_TIME_EST_A[268]="
                           : "[wear] LIFE_TIME_EST_B[269]=");
        write_hex32(est);
        if (est == 0x0Bu) {
            debug_write("  -> >100% of rated life used (exceeded)\r\n");
        } else if (est >= 0x01u && est <= 0x0Au) {
            debug_write("  -> ~"); write_dec((uint32_t)((est - 1u) * 10u));
            debug_write("-"); write_dec((uint32_t)(est * 10u));
            debug_write("% of rated life used\r\n");
        } else {
            debug_write("  -> (not reported)\r\n");
        }
    }
}
/* }}} */

/* {{{ memtest_full — striped march across the DRAM extent above the kernel
 * The routine memtest tests a 1 MB window; this is the thorough, on-demand
 * version: one word per 4 KB page across 0x40000000..0xC0000000 (the 2 GB
 * above the kernel/allocator, which live in low DRAM), four marching patterns
 * plus an address-in-address pass, reporting the first failing word. Striped
 * (a word per page) so it covers the whole extent without the wall-clock of a
 * dense march with caches off. Clobbers that whole range (nothing live is up
 * there in phase 1); DRAM only, never a peripheral, so it's C behind a CALL
 * (the interpreter's W is peripheral-only on purpose). */
#define MEMTEST_FULL_BASE   0x40000000u
#define MEMTEST_FULL_END    0xC0000000u
#define MEMTEST_FULL_STRIDE 0x1000u
static void memtest_full(void)
{
    static const uint32_t pats[4] = {
        0x00000000u, 0xFFFFFFFFu, 0x55555555u, 0xAAAAAAAAu
    };
    debug_write("[memtest-full] striped 0x40000000..0xC0000000, 1 word/4KB page\r\n");
    for (int p = 0; p < 4; p++) {
        for (uint32_t a = MEMTEST_FULL_BASE; a < MEMTEST_FULL_END; a += MEMTEST_FULL_STRIDE)
            *(volatile uint32_t *)(uintptr_t)a = pats[p];
        for (uint32_t a = MEMTEST_FULL_BASE; a < MEMTEST_FULL_END; a += MEMTEST_FULL_STRIDE) {
            uint32_t got = *(volatile uint32_t *)(uintptr_t)a;
            if (got != pats[p]) {
                debug_write("[memtest-full]   FAIL at "); write_hex32(a);
                debug_write(" got="); write_hex32(got);
                debug_write(" want="); write_hex32(pats[p]); debug_write("\r\n");
                return;
            }
        }
        debug_write("[memtest-full]   pattern "); write_hex32(pats[p]); debug_write(" OK\r\n");
    }
    for (uint32_t a = MEMTEST_FULL_BASE; a < MEMTEST_FULL_END; a += MEMTEST_FULL_STRIDE)
        *(volatile uint32_t *)(uintptr_t)a = a;
    for (uint32_t a = MEMTEST_FULL_BASE; a < MEMTEST_FULL_END; a += MEMTEST_FULL_STRIDE) {
        uint32_t got = *(volatile uint32_t *)(uintptr_t)a;
        if (got != a) {
            debug_write("[memtest-full]   ADDR FAIL at "); write_hex32(a);
            debug_write(" got="); write_hex32(got); debug_write("\r\n");
            return;
        }
    }
    debug_write("[memtest-full] PASS (striped)\r\n");
}
/* }}} */

/* {{{ otp_wait — bounded poll of an OTP status reg for a flag, then W1C-clear
 * Mirrors the driver's rockchip_otp_wait_status. Bounded so a wrong bit times
 * out instead of hanging the sweep. Returns 0 on the flag, -1 on timeout. */
static int otp_wait(uint32_t reg, uint32_t flag)
{
    for (int i = 0; i < 100000; i++) {
        if (mmio_r32(reg) & flag) { mmio_w32(reg, flag); return 0; }
    }
    return -1;
}
/* }}} */

/* {{{ otp_read_cpuid — read the chip ID words from OTP (rk3568)
 * Ported from docs/driver-refs/rockchip-otp.c (rk3568_otp_read), because the
 * OTP *controller* is not in the public TRM. Sequence: reset the controller
 * (assert/deassert its CON22 resets), enable ECC over the SBPI side-band, enter
 * user mode, then per 16-bit word write the word address + FSM-enable, poll
 * INT_STATUS for USER_DONE (bit2), and read USER_Q. Every constant is the
 * driver's. Reads the first 16 words (the cpuid is expected around word 0xa;
 * dumping a range makes the recon robust to the exact offset). Read-only on the
 * fuses; all polls bounded. */
static void otp_read_cpuid(void)
{
    /* Reset the OTP controller (driver rockchip_otp_reset: assert then
     * deassert). CON22 bits 12/13/14 = presetn / sbpi / usr_otpc_ns. */
    mmio_w32(0xFDD20458u, 0x70007000u);   /* assert   */
    busy_delay(4000u);
    mmio_w32(0xFDD20458u, 0x70000000u);   /* deassert */
    busy_delay(4000u);

    /* ECC-enable over SBPI (driver rockchip_otp_ecc_enable(true)). */
    mmio_w32(0xFE38C020u, 0xFF000200u);   /* SBPI_CTRL: DAP addr 0x02          */
    mmio_w32(0xFE38C024u, 0xFFFF0001u);   /* SBPI_CMD_VALID_PRE = 1            */
    mmio_w32(0xFE38D000u, 0x000000FAu);   /* SBPI_CMD0 = DAP_CMD_WRF|REG_ECC   */
    mmio_w32(0xFE38D004u, 0x00000000u);   /* SBPI_CMD1 = ECC_ENABLE            */
    mmio_w32(0xFE38C020u, 0x00010001u);   /* SBPI_CTRL: enable                 */
    if (otp_wait(0xFE38C304u, 0x2u) != 0) {   /* INT_STATUS SBPI_DONE (bit1)   */
        debug_write("[otp] cpuid: SBPI ecc-enable timeout\r\n");
        return;
    }

    /* User mode, then read words 0x0..0xf. */
    mmio_w32(0xFE38C100u, 0x00010001u);   /* USER_CTRL: USE_USER + mask        */
    busy_delay(400u);                      /* driver udelay(5)                  */
    for (uint32_t w = 0; w < 16u; w++) {
        mmio_w32(0xFE38C104u, w | 0xFFFF0000u);   /* USER_ADDR = word | mask   */
        mmio_w32(0xFE38C108u, 0x00010001u);       /* USER_ENABLE               */
        if (otp_wait(0xFE38C304u, 0x4u) != 0) {   /* USER_DONE (bit2)          */
            debug_write("[otp]   word "); write_hex32(w); debug_write(" <timeout>\r\n");
            break;
        }
        debug_write("[otp]   word "); write_hex32(w); debug_write(" = ");
        write_hex32(mmio_r32(0xFE38C124u) & 0xFFFFu);   /* USER_Q (16-bit)     */
        debug_write("\r\n");
    }
    mmio_w32(0xFE38C100u, 0x00010000u);   /* exit user mode (USE_USER=0 + mask) */
    debug_write("[otp] (cpuid expected ~word 0xa; see docs/driver-refs/rockchip-otp.c)\r\n");
}
/* }}} */

/* {{{ gic_probe — the interrupt controller's fixed config + clean-slate check
 * Reads only STABLE, actionable facts about the GIC-600 (base 0xFD400000, TRM
 * Part1 Table 1-1 / Ch9), not an ephemeral "what's enabled this instant" dump:
 * GICD_IIDR says which GIC it is and that it is reachable; GICD_TYPER says how
 * many interrupt IDs it supports and whether security is present — the numbers
 * phase-2 sizes its setup against (a fixed fact, like the timer frequency).
 * Then it checks whether the bootloader left any SPI enabled — the one
 * genuinely actionable ephemeral bit: if so, phase-2 must clear the distributor
 * before it unmasks, or a stale interrupt fires the instant it does. All reads
 * (the GIC is always accessible); no writes. */
static void gic_probe(void)
{
    uint32_t ctlr  = mmio_r32(0xFD400000u);   /* GICD_CTLR  */
    uint32_t typer = mmio_r32(0xFD400004u);   /* GICD_TYPER */
    uint32_t iidr  = mmio_r32(0xFD400008u);   /* GICD_IIDR  */
    uint32_t itlines = typer & 0x1Fu;

    debug_write("[gic] GICD_IIDR="); write_hex32(iidr);
    debug_write("  GICD_CTLR="); write_hex32(ctlr);
    debug_write("\r\n[gic] GICD_TYPER="); write_hex32(typer);
    debug_write(" -> up to "); write_dec(32u * (itlines + 1u));
    debug_write(" interrupt IDs, SecurityExtn=");
    write_dec((typer >> 10) & 0x1u);
    debug_write("\r\n");

    /* Clean-slate: SPIs are IDs 32+, i.e. ISENABLER[1] (@0x104) onward. Any
     * non-zero word means the bootloader left an interrupt enabled. */
    uint32_t left_on = 0;
    for (uint32_t n = 1u; n <= itlines; n++) {
        if (mmio_r32(0xFD400100u + n * 4u) != 0u) { left_on = 1; break; }
    }
    debug_write(left_on
        ? "[gic] bootloader left SPIs ENABLED -> phase-2 must clear before unmasking\r\n"
        : "[gic] no SPIs enabled -> clean slate for phase-2\r\n");
}
/* }}} */

/* {{{ i2c0_scan — liveness scan of the i2c0 bus
 * Walks every 7-bit address on i2c0 and logs which ACK a read of register 0.
 * This is a LIVENESS check, not discovery: "is the chip at this address still
 * responding?" A device that answers but misbehaves is a different, more
 * hopeful failure than one gone silent. Which address is which chip is decoded
 * from the board device tree (0x20 = the RK817 PMIC); this reports who is
 * alive. Reuses the existing i2c0 read primitive (0 = ACK+byte, -1 = NAK).
 * Read-only intent (it does set each probed device's register pointer to 0). */
static void i2c0_scan(void)
{
    i2c0_setup();
    debug_write("[i2c0-scan] responders (7-bit addr, reg0 read):");
    uint8_t b;
    unsigned found = 0;
    for (uint32_t a = 0x08u; a <= 0x77u; a++) {
        if (i2c0_read_reg(a, 0x00u, &b) == 0) {
            debug_write(" "); write_hex32(a); found++;
        }
    }
    if (found == 0u) debug_write(" (none)");
    debug_write("\r\n[i2c0-scan] (expect 0x20 = RK817 PMIC; others = undocumented board devices)\r\n");
}
/* }}} */

/* {{{ audio_codec_recon — dump the RK817's i2c register space (audio codec)
 * The audio codec is integrated in the RK817 PMIC, reachable over i2c0 (which
 * is up). We don't have the RK817 datasheet yet to name the codec registers,
 * so this captures the raw register space (0x00..0xFF) for later decode —
 * recon-ahead for the audio path, no I2S bring-up needed. Reuses the i2c0 read
 * path (NAKs on reserved regs print as "--"). TEMPORARY / probe-and-remove: a
 * one-board OS learns this once — run it, record the dump in the audio issue
 * file, then remove the probe. Read-only over i2c. */
static void audio_codec_recon(void)
{
    i2c0_setup();
    debug_write("[audio] RK817 (i2c 0x20) register dump 0x00-0xFF:\r\n");
    uint8_t v;
    for (uint32_t reg = 0; reg <= 0xFFu; reg++) {
        if ((reg & 0x0Fu) == 0u) {
            debug_write("[audio] ");
            write_hex32(reg);
            debug_write(":");
        }
        debug_write(" ");
        if (i2c0_read_reg(RK817_ADDR, reg, &v) == 0) {
            write_hex32((uint32_t)v);
        } else {
            debug_write("--");
        }
        if ((reg & 0x0Fu) == 0x0Fu) {
            debug_write("\r\n");
        }
    }
    debug_write("[audio] (codec regs are in here; decode needs the RK817 datasheet)\r\n");
}
/* }}} */

/* {{{ otp_probe — bring the OTP (eFuse) controller up enough to read it
 * Base 0xFE38C000 (non-secure OTP — the one that exposes the chip ID from a
 * non-secure EL). A read while the OTP bus clock is gated STALLS the APB
 * bridge and hangs the CPU, so ungate + release reset FIRST:
 *   CLKGATE_CON(26) @0xFDD20368 bits 9/10/11 (PCLK/SBPI/USR) -> ungate 0x0E000000
 *   SOFTRST_CON(22) @0xFDD20458 bit 12 (SRST_P_OTPC_NS)      -> release 0x10000000
 * then read OTPC_INT_STATUS @+0x0304 as a presence/clocking check.
 *
 * CONFIRMED against the TRM (extracted with ghostscript txtwrite): base
 * 0xFE38C000 = OTP_NS (Part1 Table 1-1); clock gates CLKGATE_CON26 bits 9/10/11
 * (pclk/sbpi/usr_otpc_ns) and reset SOFTRST_CON22 bit 12 (presetn_otpc_ns)
 * (Part1 Ch2). The OTP *controller* register map — the chip-ID FSM (USER_CTRL /
 * USER_ADDR=word 0xa / USER_ENABLE -> poll INT_STATUS -> read USER_Q@+0x124) —
 * is NOT in the public TRM (there is no OTP-controller chapter). The FSM and
 * every bit value ARE documented in docs/driver-refs/rockchip-otp.c
 * (rk3568_otp_read): user mode via USER_CTRL=0x00010001, per-word USER_ADDR=
 * offset|0xFFFF0000 + USER_ENABLE=0x00010001, poll INT_STATUS bit2 (USER_DONE),
 * read USER_Q; cpuid = 16 bytes ~word offset 0xa; needs an SBPI reset + ECC
 * preamble first. otp_read_cpuid() below implements that FSM (ported from the
 * driver); this probe does the presence read and then calls it. */
static void otp_probe(void)
{
    debug_write("[otp] ungate CON26 b9-11 + release CON22 b12\r\n");
    mmio_w32(0xFDD20368u, 0x0E000000u);
    mmio_w32(0xFDD20458u, 0x10000000u);
    busy_delay(10000u);
    debug_write("[otp] OTPC_INT_STATUS @0xFE38C304 = ");
    write_hex32(mmio_r32(0xFE38C304u));
    debug_write("\r\n");
    otp_read_cpuid();
}
/* }}} */

/* {{{ rng_probe — draw from the hardware RNG (inside the crypto complex)
 * Base 0xFE388000. A read while HCLK_CRYPTO_NS is gated hangs the AHB, so
 * ungate + release reset FIRST:
 *   CLKGATE_CON(8) @0xFDD20320 bit 12 (HCLK) + bit 15 (RNG) -> ungate 0x90000000
 *   SOFTRST_CON(6) @0xFDD20418 bit 8 (H_CRYPTO) + bit 11 (RNG) -> release 0x09000000
 * then start a draw via TRNG_RNG_CTL @+0x0400 and poll until its START bit
 * self-clears (that clear IS "data ready"), then read the eight output words
 * at +0x0410..+0x042C. The poll is BOUNDED so a wrong CTL value can only time
 * out, never hang.
 *
 * CONFIRMED against the TRM (extracted with ghostscript txtwrite): base
 * 0xFE388000 = TRNG_NS (Part1 Table 1-1); clock gates CLKGATE_CON8 bit 12
 * (hclk_crypto_ns) + bit 15 (clk_crypto_ns_rng) and reset SOFTRST_CON6 (Part1
 * Ch2); and the RNG_CTL start sequence + DOUT register offsets (Part2 Ch5). */
static void rng_probe(void)
{
    debug_write("[rng] ungate CON8 b12/15 + release CON6 b8/11\r\n");
    mmio_w32(0xFDD20320u, 0x90000000u);
    mmio_w32(0xFDD20418u, 0x09000000u);
    busy_delay(10000u);

    /* TRNG start sequence, CONFIRMED against TRM Part 2 Ch5. RNG_CTL (+0x400)
     * uses the upper-16-bit write-enable mask (bits 31:16 select which of
     * 15:0 change). The TRM's order: set rng_enable (bit1) FIRST, then set
     * rng_start (bit0) on its own — rng_start self-clears to 0 when the draw
     * is done. ring_sel (bits 3:2) defaults to fastest (RNG_CTL reset 0x0C)
     * and a masked write leaves it untouched. */
    mmio_w32(0xFE388404u, 0x00000000u);   /* RNG_SAMPLE_CNT = default rate    */
    mmio_w32(0xFE388400u, 0x00020002u);   /* rng_enable = 1 (mask+value bit1) */
    mmio_w32(0xFE388400u, 0x00010001u);   /* rng_start  = 1 (mask+value bit0) */
    int ready = 0;
    for (int i = 0; i < 200000; i++) {
        if ((mmio_r32(0xFE388400u) & 0x1u) == 0u) { ready = 1; break; }
    }
    debug_write(ready ? "[rng] rng_start self-cleared -> data ready\r\n"
                      : "[rng] TIMEOUT (rng_start never cleared)\r\n");
    if (ready) {
        debug_write("[rng] DOUT0-7:");
        for (uint32_t o = 0; o < 8u; o++) {
            debug_write(" ");
            write_hex32(mmio_r32(0xFE388410u + o * 4u));
        }
        debug_write("\r\n[rng] (words should differ run-to-run; all-equal/zero = stuck)\r\n");
    }
}
/* }}} */

/* {{{ crypto_probe — confirm the crypto accelerator is present and clocked
 * Base 0xFE380000. RK3568 crypto v2 exposes NO dedicated version/ID register,
 * so this is a presence/clocking check: ungate + release reset, then read the
 * first control register (CRYPTO_CLK_CTL @+0x0000). A read while ACLK/HCLK are
 * gated hangs the bus, so ungate FIRST:
 *   CLKGATE_CON(8) @0xFDD20320 bits 11-15 -> ungate 0xF8000000
 *   SOFTRST_CON(6) @0xFDD20418 bits 7-11  -> release 0x0F800000
 * CONFIRMED against the TRM (extracted with ghostscript txtwrite): base
 * 0xFE380000 = CRYPTO_NS (Part1 Table 1-1); CRYPTO_CLK_CTL @+0x0 reset 0x1
 * (Part2 Ch4); clock gates CLKGATE_CON8 bits 11/12 (aclk/hclk_crypto_ns)
 * (Part1 Ch2). A non-hanging read is the whole result — no version/ID reg. */
static void crypto_probe(void)
{
    debug_write("[crypto] ungate CON8 b11-15 + release CON6 b7-11\r\n");
    mmio_w32(0xFDD20320u, 0xF8000000u);
    mmio_w32(0xFDD20418u, 0x0F800000u);
    busy_delay(10000u);
    debug_write("[crypto] CRYPTO_CLK_CTL @0xFE380000 = ");
    write_hex32(mmio_r32(0xFE380000u));
    debug_write("\r\n[crypto] (CLK_CTL reset=0x1 per TRM Part2 Ch4; no version reg; non-hang = reachable)\r\n");
}
/* }}} */

/* {{{ timer_recon — read the ARM architected generic timer
 * Every core carries a counter (CNTPCT_EL0) that ticks at a fixed rate
 * (CNTFRQ_EL0), independent of the CPU clock — so it keeps real wall-clock
 * time even as the CPU clock changes. Reading the counter twice across a
 * fixed nop delay turns nop counts into measured time. It answers three
 * things at once: what rate firmware programmed the timer at (expected
 * ~24 MHz), how long our nop-counted busy_delay REALLY is (to calibrate
 * delay_busy), and it de-risks phase-2 scheduling, which leans on this
 * counter. System registers are read with MRS (not MMIO), so this is a C
 * CALL target rather than an R line. */
static void timer_recon(void)
{
    uint64_t freq = 0, t0 = 0, t1 = 0;
    __asm__ volatile ("mrs %0, cntfrq_el0" : "=r"(freq));
    __asm__ volatile ("mrs %0, cntpct_el0" : "=r"(t0));
    busy_delay(1000000u);
    __asm__ volatile ("mrs %0, cntpct_el0" : "=r"(t1));

    debug_write("[timer] CNTFRQ_EL0 (Hz) = ");
    write_hex32((uint32_t)freq);
    debug_write(" = ");
    write_dec((uint32_t)freq);
    debug_write("\r\n[timer] CNTPCT delta over ~1e6 nop loop = ");
    write_hex32((uint32_t)(t1 - t0));
    debug_write("\r\n");

    /* Elapsed microseconds = delta * 1e6 / freq, integer math (no FP in the
     * kernel). Tells us how long a million-nop busy_delay really is, so
     * delay_busy can be calibrated and dumps can report true MB/s. */
    if (freq != 0u) {
        uint32_t us = (uint32_t)(((t1 - t0) * 1000000u) / freq);
        debug_write("[timer] ~1e6 nop loop = ");
        write_dec(us);
        debug_write(" us of real time\r\n");
    }
}
/* }}} */

/* {{{ CALL dispatch — whole driver routines by name */
static void call_target(const char *name)
{
    if (streq(name, "timer_recon")) {
        timer_recon();
    } else if (streq(name, "cpu_recon")) {
        cpu_core_recon();
    } else if (streq(name, "emmc_wear")) {
        emmc_wear_report();
    } else if (streq(name, "memtest_full")) {
        memtest_full();
    } else if (streq(name, "otp_probe")) {
        otp_probe();
    } else if (streq(name, "rng_probe")) {
        rng_probe();
    } else if (streq(name, "crypto_probe")) {
        crypto_probe();
    } else if (streq(name, "gic_probe")) {
        gic_probe();
    } else if (streq(name, "i2c_scan")) {
        i2c0_scan();
    } else if (streq(name, "audio_recon")) {
        audio_codec_recon();
    } else if (streq(name, "sd_init")) {
        debug_write("[probe] CALL sd_init -> ");
        write_hex32((uint32_t)sd_init());
        debug_write("\r\n");
    } else if (streq(name, "emmc_init")) {
        debug_write("[probe] CALL emmc_init -> ");
        write_hex32((uint32_t)emmc_init());
        debug_write("\r\n");
    } else if (streq(name, "emmc_read0")) {
        /* Read eMMC block 0 and log its first word — a quick
         * "is the eMMC alive and returning real data" check. */
        static uint8_t blk[512];
        int r = emmc_read_block(0, blk);
        debug_write("[probe] CALL emmc_read0 -> ");
        write_hex32((uint32_t)r);
        if (r == 0) {
            debug_write(" word0=");
            write_hex32(((uint32_t)blk[0]) | ((uint32_t)blk[1] << 8)
                        | ((uint32_t)blk[2] << 16) | ((uint32_t)blk[3] << 24));
        }
        debug_write("\r\n");
    } else if (streq(name, "backup_boot")) {
        /* Copy just the eMMC's BOOTLOADER region — the Rockchip boot
         * chain (GPT at LBA 1, idbloader at LBA 64, u-boot at LBA 16384)
         * living in the 16 MB before the first partition — to the SD's
         * reserved region at LBA 0x200000. 32768 sectors = 16 MB. This is
         * the targeted safety copy (110e); when we install our own boot
         * image (110b), retarget this to wherever that lands. */
        debug_write("[probe] CALL backup_boot -> ");
        write_hex32((uint32_t)emmc_backup_to_sd(0, 0x200000u, 32768u));
        debug_write("\r\n");
    } else if (streq(name, "memtest")) {
        memtest_run();
    } else if (streq(name, "pmic_dump")) {
        pmic_dump();
    } else if (streq(name, "pmic_write_test")) {
        pmic_write_test();
    } else if (streq(name, "pmic_ldo_test")) {
        pmic_ldo_test();
    } else if (streq(name, "emmc_ext_csd")) {
        emmc_ext_csd_dump();
    } else if (streq(name, "emmc_hs200")) {
        /* Stage A of the fast-storage path (110j): switch the card to
         * HS200. A following CALL emmc_read0 is the go/no-go. */
        debug_write("[probe] CALL emmc_hs200 -> ");
        write_hex32((uint32_t)emmc_switch_hs200());
        debug_write("\r\n");
    } else if (streq(name, "emmc_hs400")) {
        /* Stage B (110j): transition HS200 -> HS400. Must follow a
         * successful emmc_hs200. A following emmc_read0 is the go/no-go. */
        debug_write("[probe] CALL emmc_hs400 -> ");
        write_hex32((uint32_t)emmc_switch_hs400());
        debug_write("\r\n");
    } else if (streq(name, "emmc_verify")) {
        /* Read a fixed non-zero block and log its fingerprint — run at
         * each speed to prove the fast read is byte-identical (110j). */
        emmc_verify();
    } else if (streq(name, "emmc_verify_dma")) {
        /* Read that block via ADMA2 (DMA) and fingerprint it — must match
         * the PIO fingerprint to prove the descriptor path is correct (110m). */
        emmc_verify_dma();
    } else if (streq(name, "emmc_dump")) {
        /* Sparse eMMC -> SD dump (110m) — packs only the non-zero chunks to
         * the SD and logs a MAP for reconstruct-emmc to rebuild from (110m). */
        debug_write("[probe] CALL emmc_dump -> ");
        write_hex32((uint32_t)emmc_dump_to_sd());
        debug_write("\r\n");
    } else if (streq(name, "emmc_scan")) {
        /* Scan the whole eMMC and log where the NON-ZERO data is (110m) —
         * a cheap layout map for a mostly-zero card, no big SD write. */
        debug_write("[probe] CALL emmc_scan -> ");
        write_hex32((uint32_t)emmc_scan_map());
        debug_write("\r\n");
    } else if (streq(name, "sd_caps")) {
        /* Read what the SD card supports (SCR / SD_STATUS / SWITCH_FUNC) —
         * the dynamic-probe foundation for the SD fast path (110l). */
        sd_probe_capabilities();
    } else if (streq(name, "sd_dma")) {
        /* Write a pattern to a reserved SD block via the IDMAC, read it
         * back PIO, and compare — proves the microSD DMA *write* engine,
         * the direction the eMMC dump needs (110m). */
        sd_dma_write_test();
    } else if (streq(name, "sd_speed")) {
        /* Dynamically pick the safe SD bus speed (the minimum of the card
         * and host ceilings) and apply it, logging the decision (110l). */
        sd_select_speed();
    } else {
        debug_write("[probe] CALL unknown target: ");
        debug_write(name);
        debug_write("\r\n");
    }
}
/* }}} */

/* {{{ execute one script line */
static void run_line(const char *line, int writes_enabled)
{
    const char *p = skip_ws(line);
    if (*p == 0 || *p == '#') return;            /* blank or comment */

    char cmd[12];
    read_token(&p, cmd, sizeof cmd);

    int ok = 0;

    if (streq(cmd, "R") || streq(cmd, "RH") || streq(cmd, "RB")) {
        uint32_t addr = parse_hex(&p, &ok);
        if (!ok) { debug_write("[probe] R: bad address\r\n"); return; }
        uint32_t v = streq(cmd, "RH") ? mmio_r16(addr)
                   : streq(cmd, "RB") ? mmio_r8(addr)
                   : mmio_r32(addr);
        debug_write("[probe] ");
        debug_write(cmd);
        debug_write(" ");
        write_hex32(addr);
        debug_write(" = ");
        write_hex32(v);
        debug_write("\r\n");

    } else if (streq(cmd, "W") || streq(cmd, "WH") || streq(cmd, "WB")) {
        uint32_t addr = parse_hex(&p, &ok);
        if (!ok) { debug_write("[probe] W: bad address\r\n"); return; }
        uint32_t val = parse_hex(&p, &ok);
        if (!ok) { debug_write("[probe] W: bad value\r\n"); return; }
        if (!writes_enabled) {
            debug_write("[probe] W skipped (writes not enabled in header): ");
            write_hex32(addr); debug_write("\r\n");
            return;
        }
        if (!write_allowed(addr)) {
            debug_write("[probe] W BLOCKED (outside allowlist): ");
            write_hex32(addr); debug_write("\r\n");
            return;
        }
        if (streq(cmd, "WH")) mmio_w16(addr, (uint16_t)val);
        else if (streq(cmd, "WB")) mmio_w8(addr, (uint8_t)val);
        else mmio_w32(addr, val);
        debug_write("[probe] ");
        debug_write(cmd);
        debug_write(" ");
        write_hex32(addr);
        debug_write(" <= ");
        write_hex32(val);
        debug_write("\r\n");

    } else if (streq(cmd, "DUMP")) {
        uint32_t addr = parse_hex(&p, &ok);
        if (!ok) { debug_write("[probe] DUMP: bad address\r\n"); return; }
        uint32_t count = parse_dec(&p, &ok);
        if (!ok) count = 4;
        if (count > 64) count = 64;              /* keep the log sane */
        for (uint32_t i = 0; i < count; i++) {
            debug_write("[probe]   ");
            write_hex32(addr + i * 4u);
            debug_write(" = ");
            write_hex32(mmio_r32(addr + i * 4u));
            debug_write("\r\n");
        }

    } else if (streq(cmd, "DELAY")) {
        uint32_t n = parse_dec(&p, &ok);
        if (!ok) n = 100000;
        busy_delay(n);
        debug_write("[probe] DELAY done\r\n");

    } else if (streq(cmd, "EXPECT")) {
        uint32_t addr = parse_hex(&p, &ok);
        if (!ok) { debug_write("[probe] EXPECT: bad address\r\n"); return; }
        uint32_t want = parse_hex(&p, &ok);
        if (!ok) { debug_write("[probe] EXPECT: bad value\r\n"); return; }
        uint32_t mask = parse_hex(&p, &ok);
        if (!ok) mask = 0xFFFFFFFFu;
        uint32_t got = mmio_r32(addr) & mask;
        debug_write("[probe] EXPECT ");
        write_hex32(addr);
        debug_write(got == (want & mask) ? " PASS got=" : " FAIL got=");
        write_hex32(got);
        debug_write(" want=");
        write_hex32(want & mask);
        debug_write("\r\n");

    } else if (streq(cmd, "POLL")) {
        /* POLL <addr> <want> <mask> <maxtries> — read addr until
         * (value & mask) == (want & mask), or maxtries elapse.
         * The wait-for-a-ready-bit primitive: DLL lock, clock
         * stable, command-done, etc. Logs how many tries it took
         * or TIMEOUT with the last value seen. */
        uint32_t addr = parse_hex(&p, &ok);
        if (!ok) { debug_write("[probe] POLL: bad address\r\n"); return; }
        uint32_t want = parse_hex(&p, &ok);
        if (!ok) { debug_write("[probe] POLL: bad value\r\n"); return; }
        uint32_t mask = parse_hex(&p, &ok);
        if (!ok) mask = 0xFFFFFFFFu;
        uint32_t tries = parse_dec(&p, &ok);
        if (!ok) tries = 100000u;
        uint32_t i, got = 0;
        for (i = 0; i < tries; i++) {
            got = mmio_r32(addr) & mask;
            if (got == (want & mask)) break;
            busy_delay(64);
        }
        debug_write("[probe] POLL ");
        write_hex32(addr);
        if (got == (want & mask)) {
            debug_write(" MATCH after ");
            write_hex32(i);
            debug_write(" tries\r\n");
        } else {
            debug_write(" TIMEOUT got=");
            write_hex32(got);
            debug_write(" want=");
            write_hex32(want & mask);
            debug_write("\r\n");
        }

    } else if (streq(cmd, "CALL")) {
        char name[16];
        read_token(&p, name, sizeof name);
        call_target(name);

    } else if (streq(cmd, "LOG")) {
        /* Echo the rest of the line verbatim — a readable marker. */
        debug_write("[probe] LOG: ");
        debug_write(skip_ws(p));
        debug_write("\r\n");

    } else {
        debug_write("[probe] unknown command: ");
        debug_write(cmd);
        debug_write("\r\n");
    }
}
/* }}} */

/* {{{ run_probe_text — run one compiled-in probe through the interpreter
 * Brackets the run with banners carrying `name` so the log is
 * splittable per probe and a hang is pinned to the last START banner
 * with no END. The text is a .rodata literal, so it is copied into the
 * writable scratch buffer before each line is NUL-terminated in place. */
static void run_probe_text(const char *name, int writes_enabled, const char *text)
{
    debug_write("\r\n[probe] ===== PROBE ");
    debug_write(name);
    debug_write(writes_enabled ? " (writes) =====\r\n" : " =====\r\n");

    uint32_t len = 0;
    while (text[len] != 0 && len < PROBE_BUF_BYTES - 1u) {
        probe_buf[len] = (uint8_t)text[len];
        len++;
    }
    char *buf = (char *)probe_buf;
    buf[len] = 0;

    uint32_t start = 0;
    for (uint32_t i = 0; i <= len; i++) {
        if (buf[i] == '\n' || buf[i] == '\r' || buf[i] == 0) {
            char saved = buf[i];
            buf[i] = 0;
            run_line(buf + start, writes_enabled);
            buf[i] = saved;
            start = i + 1;
            if (saved == 0) break;
        }
    }

    debug_write("[probe] ===== END ");
    debug_write(name);
    debug_write(" =====\r\n");
}
/* }}} */

/* {{{ probe_seed_defaults — arm each probe per its compiled-in default
 * Copies each probe's #NEEDED bit (its default arm state) into the mutable
 * run-flag array. Called once at boot in a --debug build; a production
 * build never links this file. #NEEDED now defaults to 0 (opt-in, issue
 * 110n), so only probes that explicitly asked to run are armed here. */
void probe_seed_defaults(void)
{
    for (unsigned i = 0; i < builtin_probe_count; i++) {
        probe_runflags[i] = (uint8_t)(builtin_probes[i].needed ? 1u : 0u);
    }
}
/* }}} */

/* {{{ probe_arm — arm one probe by its generated index
 * Sets a probe's run-flag so the next run_probes() runs it. The runtime-
 * trigger entry point for callers outside the boot seed (a button combo, a
 * USB console). An out-of-range index is ignored rather than trusted. */
void probe_arm(enum probe_index which)
{
    if ((unsigned)which < builtin_probe_count) {
        probe_runflags[(unsigned)which] = 1u;
    }
}
/* }}} */

/* {{{ run_probes — run every armed probe in sweep order, then self-clear
 * Walks probe_runflags[] (sweep order, already sorted by #AUTO priority)
 * and runs each ARMED probe through the interpreter. After a probe runs,
 * its output is flushed to the SD-backed log — the always-present sink;
 * screen / audio / other sinks join here as they come up — and then its
 * flag is cleared, so a slot reads 0 once its results are safely written
 * and the probe re-runs only if re-armed. An unarmed slot logs a
 * DE-SELECTED banner in its place, so the roster stays honest: a skipped
 * probe reads as deliberately skipped, not missing.
 *
 * Callable from anywhere: arm a probe (probe_arm) and call this to run it
 * on demand — the runtime-trigger seam (issue 110n). The flush-after-each
 * also means a hang leaves everything before it safe on the card — the
 * stuck probe is the last START banner with no END. Supersedes 110i's
 * terminal probe_engine_run. */
void run_probes(void)
{
    debug_write("\r\n[probe] ########## RUN ARMED PROBES ##########\r\n");

    /* Drive the LEDs over PWM: the top window holds green ("running"), the
     * bottom amber is a bar that fills across the roster (position in the
     * list, not work done), and at the end the top flips to red ("done").
     * led_top/led_bottom live in 003-pwm.c. */
    led_pwm_init();
    led_top(0u, 1u, 1u, 1u);    /* red off, green full -> top green */

    /* Segment the bottom-LED bar by the probes ARMED THIS run, not by how
     * many probes exist — the developer cares about progress through *this*
     * run (probe 2 of 5 armed = 40%), not our total probe count. Count the
     * armed ones up front, then advance the bar as each one finishes. */
    uint32_t armed_total = 0;
    for (unsigned i = 0; i < builtin_probe_count; i++) {
        if (probe_runflags[i]) armed_total++;
    }

    uint32_t armed_done = 0;
    for (unsigned i = 0; i < builtin_probe_count; i++) {
        /* Unarmed / de-selected this run: keep it in the roster with a
         * banner so the log shows a deliberate skip, not a missing probe —
         * "de-selected" is more informative than "absent". It does NOT move
         * the bar, since it is not part of this run's work. */
        if (!probe_runflags[i]) {
            debug_write("\r\n[probe] ===== PROBE ");
            debug_write(builtin_probes[i].name);
            debug_write(" DE-SELECTED (not armed) =====\r\n");
            debug_log_flush();
            continue;
        }

        run_probe_text(builtin_probes[i].name,
                       builtin_probes[i].writes_enabled,
                       builtin_probes[i].text);
        debug_log_flush();          /* commit results before clearing */
        probe_runflags[i] = 0u;     /* self-clear: ran, results written */
        armed_done++;
        led_bottom(armed_done, armed_total);   /* fraction of THIS run done */
    }
    led_bottom(1u, 1u);         /* amber full (also covers "none armed") */
    led_top(1u, 1u, 0u, 1u);    /* red full, green off -> top red = done */

    debug_write("[probe] ########## RUN DONE ##########\r\n");
}
/* }}} */

#endif /* SOREN_DEBUG */
