/*
 * 019-probe-engine.c — compiled-in hardware probe battery (issue 110i)
 *
 * Turns a `--probes` build of the kernel into a self-running
 * diagnostic instrument. Every #AUTO-marked probe under input/probes/
 * is generated into a C array (scripts/embed-probes -> probe-list.inc)
 * and compiled in; on boot the kernel runs them all in priority order
 * and logs the results to the SD-backed debug log. A normal build
 * defines nothing, so this whole file compiles to an empty object and
 * a production image carries no probe code at all.
 *
 * The probe language is deliberately tiny and dumb — read a register,
 * write a register, dump a range, delay, check a value, or call a
 * whole driver routine by name. No arithmetic, no variables, no
 * control flow. Anything more complex belongs in C.
 *
 * Two safety boundaries keep an arbitrary-MMIO-write instrument from
 * bricking the device:
 *   - writes are only honoured for a probe whose #WRITES marker set
 *     its writes-enabled flag, so a read-only probe cannot poke
 *     anything by accident;
 *   - writes are confined to an allowlist of peripheral register
 *     windows; a write outside is logged and skipped.
 *
 * Reads are unrestricted (reading a register cannot change state).
 *
 * History: this began as an SD-card-driven interpreter the lab tech
 * wrote scripts onto and the kernel read back at boot. The delivery
 * moved in-tree once we accepted that a build flag is already a
 * rebuild (so the no-rebuild benefit was moot) and that we run every
 * probe each time (so there was nothing to select). The interpreter
 * and the script language carried over unchanged. See issue 110i.
 */

#include <stdint.h>

#ifdef SOREN_PROBES

extern void debug_write(const char *text);

/* Driver entry points reachable from the CALL command. Kept to a
 * small, hand-picked set of no-argument routines — the script can
 * poke arbitrary registers with R/W, so CALL is only for whole
 * bring-up routines that are awkward to express as register pokes. */
extern int  sd_init(void);
extern int  emmc_init(void);
extern int  emmc_read_block(uint32_t lba, uint8_t *buffer);
extern int  emmc_backup_to_sd(uint32_t emmc_start_lba,
                              uint32_t sd_start_lba,
                              uint32_t sector_count);

/* The probe battery is compiled in (issue 110i): a `--probes` build
 * embeds every #AUTO-marked probe under input/probes/ as this array,
 * generated by scripts/embed-probes into probe-list.inc. Each entry
 * carries the probe's name, its writes-enabled flag (from the probe's
 * #WRITES marker), and the raw script text. The kernel runs them all
 * in priority order on boot — there is no SD probe region, no catalog,
 * and no magic header any more (see the History note up top). */
struct builtin_probe {
    const char *name;
    int         writes_enabled;
    const char *text;
};
static const struct builtin_probe builtin_probes[] = {
#include "probe-list.inc"
};
static const unsigned builtin_probe_count =
    sizeof(builtin_probes) / sizeof(builtin_probes[0]);

#define PROBE_BUF_BYTES (32u * 512u)    /* 16 KB line-split scratch */

extern void debug_log_flush(void);      /* flush the log between probes */

/* Line-split scratch (.bss, no allocator). Each probe's text is a
 * .rodata string literal and must not be written in place, so it is
 * copied here to NUL-terminate lines for the interpreter. */
static uint8_t probe_buf[PROBE_BUF_BYTES];

/* MMIO accessors. */
static inline uint32_t mmio_r32(uint32_t a) { return *(volatile uint32_t *)(uintptr_t)a; }
static inline uint16_t mmio_r16(uint32_t a) { return *(volatile uint16_t *)(uintptr_t)a; }
static inline uint8_t  mmio_r8 (uint32_t a) { return *(volatile uint8_t  *)(uintptr_t)a; }
static inline void mmio_w32(uint32_t a, uint32_t v) { *(volatile uint32_t *)(uintptr_t)a = v; }
static inline void mmio_w16(uint32_t a, uint16_t v) { *(volatile uint16_t *)(uintptr_t)a = v; }
static inline void mmio_w8 (uint32_t a, uint8_t  v) { *(volatile uint8_t  *)(uintptr_t)a = v; }

static void busy_delay(uint32_t n)
{
    volatile uint32_t r = n;
    while (r--) { __asm__ volatile ("nop"); }
}

/* {{{ helpers — tiny freestanding string / number parsing */

static int streq(const char *a, const char *b)
{
    while (*a && *b) { if (*a != *b) return 0; a++; b++; }
    return *a == *b;
}

/* Emit a 32-bit value as `0xXXXXXXXX` through debug_write. */
static void write_hex32(uint32_t v)
{
    static const char d[] = "0123456789ABCDEF";
    char buf[11];
    buf[0] = '0'; buf[1] = 'x';
    for (int i = 0; i < 8; i++) buf[2 + i] = d[(v >> ((7 - i) * 4)) & 0xFu];
    buf[10] = 0;
    debug_write(buf);
}

/* Skip spaces and tabs. */
static const char *skip_ws(const char *p)
{
    while (*p == ' ' || *p == '\t') p++;
    return p;
}

/* Read a whitespace-delimited token into out[], NUL-terminated.
 * Returns the token length and advances *pp past it. */
static int read_token(const char **pp, char *out, int max)
{
    const char *p = skip_ws(*pp);
    int n = 0;
    while (*p && *p != ' ' && *p != '\t' && n < max - 1) out[n++] = *p++;
    out[n] = 0;
    *pp = p;
    return n;
}

/* Parse a hex number (optional 0x prefix). Sets *ok to whether any
 * hex digits were consumed; advances *pp. */
static uint32_t parse_hex(const char **pp, int *ok)
{
    const char *p = skip_ws(*pp);
    if (p[0] == '0' && (p[1] == 'x' || p[1] == 'X')) p += 2;
    uint32_t v = 0;
    int digits = 0;
    for (;;) {
        char c = *p;
        int dgt;
        if (c >= '0' && c <= '9') dgt = c - '0';
        else if (c >= 'a' && c <= 'f') dgt = c - 'a' + 10;
        else if (c >= 'A' && c <= 'F') dgt = c - 'A' + 10;
        else break;
        v = (v << 4) | (uint32_t)dgt;
        p++; digits++;
    }
    *ok = (digits > 0);
    *pp = p;
    return v;
}

/* Parse a decimal number. */
static uint32_t parse_dec(const char **pp, int *ok)
{
    const char *p = skip_ws(*pp);
    uint32_t v = 0;
    int digits = 0;
    while (*p >= '0' && *p <= '9') { v = v * 10u + (uint32_t)(*p - '0'); p++; digits++; }
    *ok = (digits > 0);
    *pp = p;
    return v;
}

/* }}} */

/* {{{ the write allowlist
 *
 * Writes are confined to the chip's peripheral register space, so
 * a typo'd address cannot scribble over DRAM or the kernel. The
 * range covers the GRF / CRU / PMU blocks (0xFDC0_0000 region) and
 * the main peripheral window (0xFE00_0000 region) catalogued in
 * docs/016-physical-memory-map.md. Reads are not restricted. */
static int write_allowed(uint32_t addr)
{
    if (addr >= 0xFDC00000u && addr < 0xFDE00000u) return 1; /* GRF/CRU/PMU */
    if (addr >= 0xFE000000u && addr < 0xFE800000u) return 1; /* peripherals */
    return 0;
}
/* }}} */

/* {{{ memtest — bounded DRAM pattern test (the DRAM-walk CALL)
 *
 * Tests a fixed 1 MB window at the 1 GB mark of DRAM. That address
 * is chosen to sit far clear of the kernel image (loaded at
 * 0x0200_0000), its stack and .bss, and the page allocator's pool
 * (all in low DRAM), so the test never scribbles on anything live.
 * It writes four marching patterns plus an address-in-address pass
 * and verifies every read-back, reporting the first failing word.
 *
 * This lives in C because a probe script cannot W into DRAM — the
 * write allowlist is peripheral-only on purpose, so a stray W can't
 * corrupt RAM. The DRAM walk is a deliberate, bounded operation, so
 * it belongs behind a CALL. */
#define MEMTEST_BASE  0x40000000u
#define MEMTEST_WORDS (0x100000u / 4u)   /* 1 MB */

static int memtest_check(uint32_t pat)
{
    volatile uint32_t *m = (volatile uint32_t *)(uintptr_t)MEMTEST_BASE;
    for (uint32_t i = 0; i < MEMTEST_WORDS; i++) m[i] = pat;
    for (uint32_t i = 0; i < MEMTEST_WORDS; i++) {
        if (m[i] != pat) {
            debug_write("[probe]   FAIL at ");
            write_hex32(MEMTEST_BASE + i * 4u);
            debug_write(" got=");
            write_hex32(m[i]);
            debug_write(" want=");
            write_hex32(pat);
            debug_write("\r\n");
            return -1;
        }
    }
    return 0;
}

static void memtest_run(void)
{
    static const uint32_t pats[4] = {
        0x00000000u, 0xFFFFFFFFu, 0x55555555u, 0xAAAAAAAAu
    };
    debug_write("[probe] memtest: 1 MB @ 0x40000000\r\n");
    for (int p = 0; p < 4; p++) {
        debug_write("[probe]   pattern ");
        write_hex32(pats[p]);
        debug_write("\r\n");
        if (memtest_check(pats[p]) != 0) return;
    }
    /* Address-in-address: each word holds its own address. Catches
     * stuck address lines that the uniform patterns miss. */
    volatile uint32_t *m = (volatile uint32_t *)(uintptr_t)MEMTEST_BASE;
    for (uint32_t i = 0; i < MEMTEST_WORDS; i++) m[i] = MEMTEST_BASE + i * 4u;
    for (uint32_t i = 0; i < MEMTEST_WORDS; i++) {
        if (m[i] != MEMTEST_BASE + i * 4u) {
            debug_write("[probe]   FAIL addr-test at ");
            write_hex32(MEMTEST_BASE + i * 4u);
            debug_write(" got=");
            write_hex32(m[i]);
            debug_write("\r\n");
            return;
        }
    }
    debug_write("[probe] memtest PASS\r\n");
}
/* }}} */

/* {{{ i2c0 + PMIC dump — read RK817 registers over the PMIC bus
 *
 * The RK817 PMIC sits on i2c0 (0xFDD40000) at 7-bit address 0x20.
 * This brings the i2c0 controller up bare-metal (ungate its PMU-
 * domain clocks, route GPIO0_B1/B2 to the i2c0 function, set a
 * slow safe SCL divider) and reads registers through Rockchip's
 * "register-address then read" transfer mode, per RK3568 TRM
 * Chapter 22. The pmic_dump CALL target reads the first 16 RK817
 * registers and logs them — non-0xFF responses confirm the PMIC is
 * alive on the bus. Interpreting the values (regulator states,
 * battery) needs the RK817 datasheet; this is the reachability +
 * raw-snapshot layer the rest builds on. */
#define I2C0_BASE     0xFDD40000u
#define I2C0_CON      (I2C0_BASE + 0x00u)
#define I2C0_CLKDIV   (I2C0_BASE + 0x04u)
#define I2C0_MRXADDR  (I2C0_BASE + 0x08u)
#define I2C0_MRXRADDR (I2C0_BASE + 0x0Cu)
#define I2C0_MRXCNT   (I2C0_BASE + 0x14u)
#define I2C0_IPD      (I2C0_BASE + 0x1Cu)
#define I2C0_RXDATA0  (I2C0_BASE + 0x200u)
#define RK817_ADDR    0x20u

static void i2c0_setup(void)
{
    /* Ungate i2c0's PMU-domain clocks (PMUGATE_CON01 bits 0,1)
     * and release its resets (PMUSOFTRST_CON00 bits 3,4). */
    mmio_w32(0xFDD00184u, 0x00030000u);
    mmio_w32(0xFDD00200u, 0x00180000u);
    /* Route GPIO0_B1 (SCL) and GPIO0_B2 (SDA) to i2c0 function 1
     * in the PMU GRF, and flip the pad source to the i2c0
     * controller rather than the audio codec. */
    mmio_w32(0xFDC20008u, 0x07700110u);
    mmio_w32(0xFDC20100u, 0x00020002u);
    /* Slow, safe SCL divider — a probe doesn't need speed, and a
     * too-fast clock would just NAK. (No write-mask on this IP.) */
    mmio_w32(I2C0_CLKDIV, 0x00FF00FFu);
}

/* Read one 8-bit register from an i2c device. Returns 0 on
 * success with the byte in *out, or -1 on timeout. */
static int i2c0_read_reg(uint32_t dev, uint32_t reg, uint8_t *out)
{
    mmio_w32(I2C0_IPD, 0xFFu);                       /* clear stale pending */
    mmio_w32(I2C0_MRXADDR, 0x01000000u | (dev << 1));/* addlvld | dev<<1 */
    mmio_w32(I2C0_MRXRADDR, 0x01000000u | reg);      /* sraddlvld | reg */
    mmio_w32(I2C0_MRXCNT, 1u);                        /* read 1 byte */
    /* CON: enable | mode 01 (reg-addr then read) | start | NAK-last */
    mmio_w32(I2C0_CON, 0x0000002Bu);

    uint32_t budget = 1000000u;
    while (!(mmio_r32(I2C0_IPD) & 0x08u)) {           /* wait MBRF */
        if (budget-- == 0u) { mmio_w32(I2C0_CON, 0u); return -1; }
    }
    mmio_w32(I2C0_IPD, 0x08u);                         /* clear MBRF */
    *out = (uint8_t)(mmio_r32(I2C0_RXDATA0) & 0xFFu);

    mmio_w32(I2C0_CON, 0x00000011u);                  /* enable | stop */
    budget = 1000000u;
    while (!(mmio_r32(I2C0_IPD) & 0x20u)) {            /* wait STOP done */
        if (budget-- == 0u) break;
    }
    mmio_w32(I2C0_IPD, 0x20u);
    mmio_w32(I2C0_CON, 0u);                            /* disable */
    return 0;
}

static void pmic_dump(void)
{
    i2c0_setup();
    debug_write("[probe] RK817 PMIC @ i2c0 0x20, registers 0x00..0x0F:\r\n");
    for (uint32_t reg = 0; reg <= 0x0Fu; reg++) {
        uint8_t v = 0;
        debug_write("[probe]   reg ");
        write_hex32(reg);
        if (i2c0_read_reg(RK817_ADDR, reg, &v) == 0) {
            debug_write(" = ");
            write_hex32((uint32_t)v);
            debug_write("\r\n");
        } else {
            debug_write(" = TIMEOUT (PMIC not responding)\r\n");
        }
    }
}
/* }}} */

/* {{{ CALL dispatch — whole driver routines by name */
static void call_target(const char *name)
{
    if (streq(name, "sd_init")) {
        debug_write("[probe] CALL sd_init -> ");
        write_hex32((uint32_t)sd_init());
        debug_write("\r\n");
    } else if (streq(name, "emmc_init")) {
        debug_write("[probe] CALL emmc_init -> ");
        write_hex32((uint32_t)emmc_init());
        debug_write("\r\n");
    } else if (streq(name, "emmc_read0")) {
        /* Read eMMC block 0 and log its first word — a quick
         * "is the eMMC alive and returning real data" check. */
        static uint8_t blk[512];
        int r = emmc_read_block(0, blk);
        debug_write("[probe] CALL emmc_read0 -> ");
        write_hex32((uint32_t)r);
        if (r == 0) {
            debug_write(" word0=");
            write_hex32(((uint32_t)blk[0]) | ((uint32_t)blk[1] << 8)
                        | ((uint32_t)blk[2] << 16) | ((uint32_t)blk[3] << 24));
        }
        debug_write("\r\n");
    } else if (streq(name, "backup200")) {
        /* The standard 200 MB eMMC->SD validation backup. */
        debug_write("[probe] CALL backup200 -> ");
        write_hex32((uint32_t)emmc_backup_to_sd(0, 0x200000u, 409600u));
        debug_write("\r\n");
    } else if (streq(name, "memtest")) {
        memtest_run();
    } else if (streq(name, "pmic_dump")) {
        pmic_dump();
    } else {
        debug_write("[probe] CALL unknown target: ");
        debug_write(name);
        debug_write("\r\n");
    }
}
/* }}} */

/* {{{ execute one script line */
static void run_line(const char *line, int writes_enabled)
{
    const char *p = skip_ws(line);
    if (*p == 0 || *p == '#') return;            /* blank or comment */

    char cmd[12];
    read_token(&p, cmd, sizeof cmd);

    int ok = 0;

    if (streq(cmd, "R") || streq(cmd, "RH") || streq(cmd, "RB")) {
        uint32_t addr = parse_hex(&p, &ok);
        if (!ok) { debug_write("[probe] R: bad address\r\n"); return; }
        uint32_t v = streq(cmd, "RH") ? mmio_r16(addr)
                   : streq(cmd, "RB") ? mmio_r8(addr)
                   : mmio_r32(addr);
        debug_write("[probe] ");
        debug_write(cmd);
        debug_write(" ");
        write_hex32(addr);
        debug_write(" = ");
        write_hex32(v);
        debug_write("\r\n");

    } else if (streq(cmd, "W") || streq(cmd, "WH") || streq(cmd, "WB")) {
        uint32_t addr = parse_hex(&p, &ok);
        if (!ok) { debug_write("[probe] W: bad address\r\n"); return; }
        uint32_t val = parse_hex(&p, &ok);
        if (!ok) { debug_write("[probe] W: bad value\r\n"); return; }
        if (!writes_enabled) {
            debug_write("[probe] W skipped (writes not enabled in header): ");
            write_hex32(addr); debug_write("\r\n");
            return;
        }
        if (!write_allowed(addr)) {
            debug_write("[probe] W BLOCKED (outside allowlist): ");
            write_hex32(addr); debug_write("\r\n");
            return;
        }
        if (streq(cmd, "WH")) mmio_w16(addr, (uint16_t)val);
        else if (streq(cmd, "WB")) mmio_w8(addr, (uint8_t)val);
        else mmio_w32(addr, val);
        debug_write("[probe] ");
        debug_write(cmd);
        debug_write(" ");
        write_hex32(addr);
        debug_write(" <= ");
        write_hex32(val);
        debug_write("\r\n");

    } else if (streq(cmd, "DUMP")) {
        uint32_t addr = parse_hex(&p, &ok);
        if (!ok) { debug_write("[probe] DUMP: bad address\r\n"); return; }
        uint32_t count = parse_dec(&p, &ok);
        if (!ok) count = 4;
        if (count > 64) count = 64;              /* keep the log sane */
        for (uint32_t i = 0; i < count; i++) {
            debug_write("[probe]   ");
            write_hex32(addr + i * 4u);
            debug_write(" = ");
            write_hex32(mmio_r32(addr + i * 4u));
            debug_write("\r\n");
        }

    } else if (streq(cmd, "DELAY")) {
        uint32_t n = parse_dec(&p, &ok);
        if (!ok) n = 100000;
        busy_delay(n);
        debug_write("[probe] DELAY done\r\n");

    } else if (streq(cmd, "EXPECT")) {
        uint32_t addr = parse_hex(&p, &ok);
        if (!ok) { debug_write("[probe] EXPECT: bad address\r\n"); return; }
        uint32_t want = parse_hex(&p, &ok);
        if (!ok) { debug_write("[probe] EXPECT: bad value\r\n"); return; }
        uint32_t mask = parse_hex(&p, &ok);
        if (!ok) mask = 0xFFFFFFFFu;
        uint32_t got = mmio_r32(addr) & mask;
        debug_write("[probe] EXPECT ");
        write_hex32(addr);
        debug_write(got == (want & mask) ? " PASS got=" : " FAIL got=");
        write_hex32(got);
        debug_write(" want=");
        write_hex32(want & mask);
        debug_write("\r\n");

    } else if (streq(cmd, "POLL")) {
        /* POLL <addr> <want> <mask> <maxtries> — read addr until
         * (value & mask) == (want & mask), or maxtries elapse.
         * The wait-for-a-ready-bit primitive: DLL lock, clock
         * stable, command-done, etc. Logs how many tries it took
         * or TIMEOUT with the last value seen. */
        uint32_t addr = parse_hex(&p, &ok);
        if (!ok) { debug_write("[probe] POLL: bad address\r\n"); return; }
        uint32_t want = parse_hex(&p, &ok);
        if (!ok) { debug_write("[probe] POLL: bad value\r\n"); return; }
        uint32_t mask = parse_hex(&p, &ok);
        if (!ok) mask = 0xFFFFFFFFu;
        uint32_t tries = parse_dec(&p, &ok);
        if (!ok) tries = 100000u;
        uint32_t i, got = 0;
        for (i = 0; i < tries; i++) {
            got = mmio_r32(addr) & mask;
            if (got == (want & mask)) break;
            busy_delay(64);
        }
        debug_write("[probe] POLL ");
        write_hex32(addr);
        if (got == (want & mask)) {
            debug_write(" MATCH after ");
            write_hex32(i);
            debug_write(" tries\r\n");
        } else {
            debug_write(" TIMEOUT got=");
            write_hex32(got);
            debug_write(" want=");
            write_hex32(want & mask);
            debug_write("\r\n");
        }

    } else if (streq(cmd, "CALL")) {
        char name[16];
        read_token(&p, name, sizeof name);
        call_target(name);

    } else if (streq(cmd, "LOG")) {
        /* Echo the rest of the line verbatim — a readable marker. */
        debug_write("[probe] LOG: ");
        debug_write(skip_ws(p));
        debug_write("\r\n");

    } else {
        debug_write("[probe] unknown command: ");
        debug_write(cmd);
        debug_write("\r\n");
    }
}
/* }}} */

/* {{{ run_probe_text — run one compiled-in probe through the interpreter
 * Brackets the run with banners carrying `name` so the log is
 * splittable per probe and a hang is pinned to the last START banner
 * with no END. The text is a .rodata literal, so it is copied into the
 * writable scratch buffer before each line is NUL-terminated in place. */
static void run_probe_text(const char *name, int writes_enabled, const char *text)
{
    debug_write("\r\n[probe] ===== PROBE ");
    debug_write(name);
    debug_write(writes_enabled ? " (writes) =====\r\n" : " =====\r\n");

    uint32_t len = 0;
    while (text[len] != 0 && len < PROBE_BUF_BYTES - 1u) {
        probe_buf[len] = (uint8_t)text[len];
        len++;
    }
    char *buf = (char *)probe_buf;
    buf[len] = 0;

    uint32_t start = 0;
    for (uint32_t i = 0; i <= len; i++) {
        if (buf[i] == '\n' || buf[i] == '\r' || buf[i] == 0) {
            char saved = buf[i];
            buf[i] = 0;
            run_line(buf + start, writes_enabled);
            buf[i] = saved;
            start = i + 1;
            if (saved == 0) break;
        }
    }

    debug_write("[probe] ===== END ");
    debug_write(name);
    debug_write(" =====\r\n");
}
/* }}} */

/* {{{ probe_engine_run — run the whole compiled-in probe battery
 * Walks builtin_probes[] (generated from input/probes/, already sorted
 * by #AUTO priority) and runs each through the interpreter, flushing
 * the log after every probe so a hang leaves everything before it safe
 * on the card — the stuck probe is the last START banner with no END.
 * Returns the number of probes run; kernel_main parks while it is
 * nonzero. A --probes build with no #AUTO probes returns 0 and falls
 * through to the normal boot flow. */
int probe_engine_run(void)
{
    debug_write("\r\n[probe] ########## RUN-ALL SWEEP ##########\r\n");

    for (unsigned i = 0; i < builtin_probe_count; i++) {
        run_probe_text(builtin_probes[i].name,
                       builtin_probes[i].writes_enabled,
                       builtin_probes[i].text);
        debug_log_flush();   /* preserve results before the next probe */
    }

    debug_write("[probe] ########## SWEEP DONE, ");
    {
        /* small inline decimal print of the count */
        char b[12]; int pos = 10; b[11] = 0;
        unsigned v = builtin_probe_count;
        if (v == 0) b[pos--] = '0';
        else { while (v) { b[pos--] = (char)('0' + v % 10u); v /= 10u; } }
        debug_write(&b[pos + 1]);
    }
    debug_write(" probes ##########\r\n");
    return (int)builtin_probe_count;
}
/* }}} */

#endif /* SOREN_PROBES */
