-- archived-exceptions.lua
-- GENERATED by find-archived-exceptions; do not edit by hand.
--
-- Transcripts written before the exporter's header settled, whose session
-- logs are gone, so they can never be rebuilt. The reader accepts these
-- (by session id) without a "Generated on" line. Each is followed by where
-- it was found when this list was made.
return {
}
