-- default-palette.lua
-- GENERATED by make-default-palette from
-- /home/ritz/games/tq/ai-stuff/double-diaper-dungeon/assets/023-balance-table.lua
-- Do not edit by hand; tune the game's colours and run the generator again.
--
-- The same shape as that balance table: palette maps a colour name to
-- { value = { red, green, blue } }, each channel a number from 0 to 1.
return {
  palette = {
    strength     = { value = { 1.00, 0.55, 0.78 } },
    dexterity    = { value = { 0.42, 1.00, 0.15 } },
    constitution = { value = { 0.72, 0.52, 0.96 } },
    intellect    = { value = { 0.40, 0.76, 1.00 } },
    spirit       = { value = { 1.00, 0.88, 0.25 } },
    background   = { value = { 0.02, 0.02, 0.03 } },
    plain_text   = { value = { 0.55, 0.55, 0.58 } },
  },
}
