-- transcript-reader.lua
-- Copyright (C) 2026 gabrilend. SPDX-License-Identifier: AGPL-3.0-or-later
--
-- Reads a saved conversation and hands back its shape: who spoke, in what
-- order, which model answered, and the recaps listed at the top.
--
-- Taken from double-diaper-dungeon's src/047-transcript-reader.lua (at its
-- commit 58f89bf) for every project's transcripts (issue 035). Three changes
-- from that copy, each because other projects hold shapes that one did not:
--
--   the recap Contents list (issue 037) is read instead of discarded;
--   the lines above the first request (a slash command, a background task) are
--   kept as a turn written by neither speaker instead of discarded;
--   the header rules are the exporter's current ones, plus a fixed list of
--   archived transcripts written before those rules settled.
--
-- WHY THIS DOES NOT RE-PARSE MARKDOWN. A transcript is markdown, so the first
-- instinct is to run it through a markdown reader and walk the result. That
-- would be wrong, and the reason is visible in any transcript: the assistant
-- writes its own `##` headings inside a reply, dozens of them. To a markdown
-- reader those are indistinguishable from structure.
--
-- The exporter's structure is a fixed vocabulary at one level and the prose
-- never reaches it:
--
--     # Conversation Summary: <session id>     the first line, always
--     Generated on: <when the file was written>
--     Models: <every model that served a reply>
--     ## Contents                              the recaps, when there are any
--     ### User Request 1                       an exchange begins
--     ### Assistant Response 1                 the reply to it
--     *model: claude-opus-5*                   the model changed here
--
-- So splitting on the exporter's `### ` lines is reliable and `## ` is left
-- alone as body. The original version of this file said a model writing
-- prose never writes `###`; that was true of one project's transcripts and
-- false across the machine, so a `###` line counts as structure only where
-- the exporter puts one: directly under its rule line (see M.read). The one
-- `##` the exporter writes, Contents, sits above the first rule line, where
-- no prose ever is.
--
-- WHAT THE BODY IS. Everything between one `###` line and the next, with the
-- rule lines the exporter puts between exchanges removed. The body is handed
-- on as markdown text and rendered elsewhere; this file does not know what
-- HTML is and should not learn.
--
-- THE SESSION ID IS A KEY, NOT DECORATION. It is the name of Claude Code's own
-- log for the same conversation, which is where the per-exchange timestamps
-- live, so the id is carried out rather than dropped.

local M = {}

-- The line the exporter draws between exchanges. Matched rather than counted,
-- because its length is the exporter's business and not this file's.
local RULE = "^%-%-%-%-%-%-%-%-+$"

-- The archived transcripts written before the exporter's header settled: a set
-- of session ids (string -> true), generated by find-archived-exceptions and
-- never added to by hand. Their session logs are gone, so they can never be
-- rewritten into today's shape, and the exporter writes today's shape into
-- everything it makes, so the set cannot grow. Loaded when first wanted.
local ARCHIVED = nil

-- {{{ local function archived()
local function archived()
  if not ARCHIVED then
    local here = debug.getinfo(1, "S").source:match("^@(.*/)") or "./"
    ARCHIVED = dofile(here .. "archived-exceptions.lua")
  end
  return ARCHIVED
end
-- }}}

-- {{{ function M.use_archived_list()
-- Replaces the archived list for this run. find-archived-exceptions passes an
-- empty set, so the reader applies the exporter's rules with no exceptions
-- and the tool can see exactly which transcripts need one.
function M.use_archived_list(set)
  ARCHIVED = set
end
-- }}}

-- {{{ local function strip_rules()
-- Takes the exporter's separator lines out of a body and trims the blank lines
-- they leave behind. The separators belong to the file format rather than to
-- anything a person said, so they never reach a page.
local function strip_rules(body)
  local kept = {}
  for line in (body .. "\n"):gmatch("([^\n]*)\n") do
    if not line:match(RULE) then
      kept[#kept + 1] = line
    end
  end
  local text = table.concat(kept, "\n")
  text = text:gsub("^%s+", ""):gsub("%s+$", "")
  return text
end
-- }}}

-- {{{ local function read_header()
-- Pulls the header facts off the top of a transcript.
--
-- The rules are the exporter's own, as it writes today:
--
--   the session id is required. A transcript without one cannot be matched to
--   its log, and a caller that silently accepted a nil id would fail much
--   later, in the timeline, as a link that goes nowhere.
--
--   the generated-on line is required. The exporter always writes it.
--
--   the models line is written only when some reply named its model, so its
--   absence is a real shape: models is an empty list, meaning none named.
--
-- One exception, and it is a list rather than a looser rule: a transcript on
-- the archived list may lack the generated-on line. Its generated_on comes
-- back nil and its header_complete false, so a page can say "not recorded"
-- instead of inventing a date. Anything else missing a line is still an error,
-- because a new transcript without one means the exporter's format moved.
local function read_header(text)
  local session_id = text:match("^# Conversation Summary: ([^\n]+)")
  if not session_id then
    error("transcript has no session id on its first line")
  end
  local is_archived = archived()[session_id] == true

  local generated_on = text:match("\nGenerated on: ([^\n]+)")
  if not generated_on and not is_archived then
    error("transcript " .. session_id .. " has no generated-on line, and is not on the archived list")
  end

  local models = {}
  local models_line = text:match("\nModels: ([^\n]+)")
  if models_line then
    for name in models_line:gmatch("[^,%s]+") do
      models[#models + 1] = name
    end
  end

  return session_id, generated_on, models, not is_archived
end
-- }}}

-- {{{ local function read_contents()
-- The list of recaps the exporter writes at the top of a transcript (issue
-- 037 in ai-stuff/scripts): one numbered entry per recap Claude Code wrote
-- while the person was away, each saying when, after which request, and what.
--
--   1. 2026-09-23 15:40, after Request 1 - I've reviewed the README: ...
--      continuation lines indented under the text
--
-- Returns a list of { when = <string "YYYY-MM-DD HH:MM">, after_request =
-- <number, 0 for "before Request 1">, text = <string> }, empty when the
-- transcript has no Contents section. An entry that does not have that shape
-- is an error: the exporter wrote it, so a mismatch means the two disagree.
local function read_contents(header_block)
  local section = header_block:match("\n## Contents\n\n(.-)\n\n") or
                  header_block:match("\n## Contents\n\n(.-)%s*$")
  local entries = {}
  if not section then
    return entries
  end
  -- Join each entry's wrapped lines back into one, then read it.
  local joined = {}
  for line in (section .. "\n"):gmatch("([^\n]*)\n") do
    if line:match("^%d+%. ") then
      joined[#joined + 1] = line
    elseif line:match("^%s+%S") and #joined > 0 then
      joined[#joined] = joined[#joined] .. " " .. line:match("^%s+(.-)$")
    elseif line ~= "" then
      error("unrecognised line in the Contents section: " .. line)
    end
  end
  for _, entry in ipairs(joined) do
    local when, place, text = entry:match(
      "^%d+%. (%d%d%d%d%-%d%d%-%d%d %d%d:%d%d), (%a+ Request %d+) %- (.*)$")
    if not when then
      error("unrecognised Contents entry: " .. entry)
    end
    -- Two places a recap can be: after a numbered request, or before the
    -- first one. Anything else is a phrase the exporter does not write.
    local after = place:match("^after Request (%d+)$")
    if place == "before Request 1" then
      after = 0
    elseif not after then
      error("unrecognised place in a Contents entry: " .. place)
    end
    entries[#entries + 1] = { when = when, after_request = tonumber(after), text = text }
  end
  return entries
end
-- }}}

-- {{{ local function read_commits()
-- The commits a reply records making (issue 035), one line each, written by
-- the exporter where the commit happened:
--
--   *[commit] 8a235a0fe in ai-stuff - Close four finished issues...*
--   *[commit] 6b80531 - One service per mailbox...*
--
-- Returns a list of { hash = <string, abbreviated hex>, subject = <string> },
-- empty when the reply made none. The subject's escaped asterisks are
-- restored so it compares equal to the commit's own subject.
local function read_commits(body)
  local commits = {}
  for line in (body .. "\n"):gmatch("([^\n]*)\n") do
    local hash, rest = line:match("^%*%[commit%] (%x+)(.*)%*$")
    if hash then
      -- Two shapes: with the repository named (" in name - subject"), or
      -- without (" - subject").
      local subject = rest:match("^ in %S+ %- (.*)$") or rest:match("^ %- (.*)$") or ""
      commits[#commits + 1] = { hash = hash, subject = (subject:gsub("\\%*", "*")) }
    end
  end
  return commits
end
-- }}}

-- {{{ local function classify()
-- Turns a `###` heading into the three things the rest of the file wants from
-- it: which side spoke, which exchange this is, and whether it carries on from
-- the one before.
--
-- FOUR SHAPES, AND THE THIRD AND FOURTH WERE FOUND BY FAILING. The first
-- version of this function knew two, ran against the real corpus, and stopped
-- on a heading nobody had written down. That is the whole argument for erroring
-- rather than skipping: a reader that ignored the unknown line would have
-- dropped ten replies onto the floor and still printed a page that looked fine.
--
--   User Request N                    she spoke
--   Assistant Response N              the reply
--   Assistant Response N (continued)  the same reply, resumed after the
--                                     conversation ran out of room
--   Session Recap (...)               neither of them: the harness wrote it
--
-- THE RECAP IS ITS OWN KIND ON PURPOSE. When a conversation runs out of room
-- the harness writes a summary of what came before, and its own heading says
-- it is "written by the harness, not by either speaker". Folding that into the
-- assistant's replies would put machine bookkeeping in a person's mouth on a
-- public page. It gets its own kind so the page can show it as what it is.
local function classify(heading)
  local number = heading:match("^User Request (%d+)$")
  if number then
    return "user", tonumber(number), false
  end

  number = heading:match("^Assistant Response (%d+)$")
  if number then
    return "assistant", tonumber(number), false
  end

  number = heading:match("^Assistant Response (%d+) %(continued%)$")
  if number then
    return "assistant", tonumber(number), true
  end

  if heading:match("^Session Recap") then
    return "recap", nil, false
  end

  error("unrecognised transcript heading: " .. heading)
end
-- }}}

-- {{{ function M.read()
-- Reads a whole transcript and returns its shape.
--
-- The returned table:
--
--   session_id       string
--   generated_on     string, or nil for an archived transcript without one
--   header_complete  boolean, false for an archived transcript: its
--                    generated-on and models lines may be missing because
--                    they were never written, not because none applied
--   models           list of strings, first-use order; may be empty
--   contents         list of recap entries (see read_contents), may be empty
--   exchanges        list of turns, in file order, which is the order they
--                    happened
--
-- Each exchange is a table:
--
--   kind    "user", "assistant", "recap", or "harness" (lines the harness
--           wrote above the first request - a slash command, a background
--           task finishing - which belong to neither speaker)
--   number  the exchange number the exporter gave it; nil for recap, harness
--   body    what was said, as markdown, separators removed
--   continued  true for the rest of a reply resumed after running out of room
--   model   for an assistant reply, the model named by the most recent
--           `*model: ...*` line, or the first model in the header
--   commits for an assistant reply, the commits it records making (see
--           read_commits); empty for every other kind
--
-- The model is carried forward rather than looked up per reply, because the
-- exporter only writes the marker when the model CHANGES. A reply with no
-- marker above it was served by whatever served the one before.
function M.read(text)
  local session_id, generated_on, models, header_complete = read_header(text)

  -- The header block is everything down to the first rule line; below it and
  -- above the first `###` heading are lines the harness wrote before the
  -- first request, if any.
  local rule_at = text:find("\n%-%-%-%-%-%-%-%-+\n")
  local header_block = rule_at and text:sub(1, rule_at) or text
  local contents = read_contents(header_block)

  local exchanges = {}

  -- The first model in the header is the one that served the first reply.
  --
  -- This is not a guess. The exporter writes a `*model: ...*` marker only where
  -- the model CHANGES, and a change marker implies something before it, so the
  -- opening model can never have one. Header order is first-use order.
  local current_model = models[1]

  -- Walk the file by the exporter's `###` headings. Each match gives the
  -- heading and everything up to the next heading or the end, which is that
  -- exchange's body.
  --
  -- A heading is the exporter's only when it sits directly under a rule line
  -- and a blank line. Models DO write `###` headings in their prose ("###
  -- Directory Layout", "### 401a-core-fixed-timestep-loop"): 38 transcripts
  -- across the machine held one on 2026-09-26, and the first version of this
  -- reader, which took every `###` line as structure, refused all of them. A
  -- model never writes the exporter's eighty-dash rule, and the exporter
  -- writes one above every heading it makes, in every transcript old and new.
  -- `at` is where the heading's `###` begins.
  local positions = {}
  for start_at, heading in text:gmatch("\n%-%-%-%-%-%-%-%-+\n\n()### ([^\n]+)") do
    positions[#positions + 1] = { at = start_at, heading = heading }
  end

  -- Two paths for the stretch between the header block and the first heading:
  -- it holds harness lines, and they become a turn of their own so nothing
  -- the file says is dropped; or it holds nothing but rules and blank lines,
  -- and there is no turn.
  if rule_at then
    -- Up to the character before the first heading's "###"; the heading's
    -- own first "#" once leaked in here and drew a harness turn holding "#".
    local first_heading_at = positions[1] and (positions[1].at - 1) or #text
    local before = strip_rules(text:sub(rule_at + 1, first_heading_at))
    if before ~= "" then
      exchanges[#exchanges + 1] = { kind = "harness", body = before, continued = false }
    end
  end

  for index, here in ipairs(positions) do
    local body_from = text:find("\n", here.at) or #text
    local body_to = positions[index + 1] and (positions[index + 1].at - 1) or #text
    local body = strip_rules(text:sub(body_from + 1, body_to))

    -- A model marker sits inside the body it applies to, so it is read before
    -- the body is handed on, and it updates the running model for every reply
    -- after it as well as this one.
    local named = body:match("%*model: ([%w%-%.]+)%*")
    if named then
      current_model = named
    end

    local kind, number, continued = classify(here.heading)
    exchanges[#exchanges + 1] = {
      kind = kind,
      number = number,
      body = body,
      continued = continued,
      model = (kind == "assistant") and current_model or nil,
      commits = (kind == "assistant") and read_commits(body) or {},
    }
  end

  return {
    session_id = session_id,
    generated_on = generated_on,
    header_complete = header_complete,
    models = models,
    contents = contents,
    exchanges = exchanges,
  }
end
-- }}}

-- {{{ function M.first_request()
-- The first thing the person said, which is what a contents page shows as the
-- summary line for a conversation before anybody clicks into it.
--
-- Returns nil when a transcript holds no user request at all. That is a real
-- shape rather than a broken one -- a conversation can be resumed and exported
-- with only replies in it -- so the caller decides what to print, and this file
-- does not invent a sentence nobody said.
function M.first_request(conversation)
  for _, exchange in ipairs(conversation.exchanges) do
    if exchange.kind == "user" then
      return exchange.body
    end
  end
  return nil
end
-- }}}

-- {{{ function M.turn_after_request()
-- Which turn a reader should land on to read from just after request N: the
-- index (number) in conversation.exchanges of the turn that starts request
-- N + 1. This is where a Contents entry's "after Request N" points.
--
-- Two paths: request N + 1 exists, and its index is returned; or N was the
-- last request, and the last turn's index is returned, since the recap
-- follows everything there is.
function M.turn_after_request(conversation, n)
  for index, exchange in ipairs(conversation.exchanges) do
    if exchange.kind == "user" and exchange.number == n + 1 then
      return index
    end
  end
  return #conversation.exchanges
end
-- }}}

return M
