/*
 * 069-bridge-main.c -- the program each participant runs.
 *
 * Two jobs and no others: hold one socket to the server, and serve a browser on
 * localhost.
 *
 * IT HOLDS NO AUTHORITY. If the bridge and the server disagree about where a
 * goblin is, the server is right by definition. It does not simulate, it does
 * not filter, and it does not remember anything the server has not told it --
 * it translates.
 *
 * Usage:
 *   069-bridge <address> <door-port> <name> [local-port]
 *
 * Then open http://localhost:12345 -- and you are at the table, without hosting
 * anything. The world is on the host's machine the whole time.
 */

#include "061-door.h"
#include "064-httpd.h"
#include "106-controls.h"
#include "096-engrave.h"

/*
 * Where the last session's carving is kept. The RAM tier, because it is
 * regenerated every time a session ends -- and the sharing script is what
 * moves one somewhere durable.
 */
#define ENGRAVING_PATH "/dev/shm/my-own-custom-vtt/engravings/last.engraving"
#include "056-protocol.h"
#include "051-commandlog.h"

#include "066-embedded-view.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <time.h>
#include <errno.h>
#include <unistd.h>
#include <sys/socket.h>

#define DEFAULT_LOCAL_PORT 12345

static volatile sig_atomic_t asked_to_stop = 0;

/* {{{ static void note_the_interrupt */
static void note_the_interrupt(int which)
{
    (void)which;
    asked_to_stop = 1;
}
/* }}} */

/*
 * The opcode and slot table, handed to the browser as JavaScript.
 *
 * GENERATED FROM THE C TABLE AT STARTUP rather than written into the page a
 * second time. Two copies of a grammar drift, and when they do the symptom is
 * operands read at the wrong offsets -- which looks like corruption rather than
 * like a mismatch, and is very hard to recognise as either.
 */
/* {{{ static uint32_t build_tables_js */
static uint32_t build_tables_js(char *out, uint32_t capacity)
{
    uint32_t written = 0;
    uint8_t opcodes[] = {
        VERB_DRIVE, VERB_ORDER_MOVE, VERB_ORDER_FACE, VERB_ORDER_STOP,
        VERB_INTERACT,
        OP_HELLO, OP_TICK, OP_WALL, OP_THING, OP_FAN, OP_REFUSAL,
        OP_RECALL, OP_END, OP_LAYER
    };
    uint32_t i;

    written += (uint32_t)snprintf(out + written, capacity - written,
        "/* GENERATED by the bridge from the C slot table. */\n"
        "const TABLES = { slots: {}, op: {}, refusals: {}, maxFlagWords: %d };\n",
        PROTO_MAX_FLAG_WORDS);

    for (i = 0; i < sizeof(opcodes) / sizeof(opcodes[0]); i++) {
        uint8_t op = opcodes[i];
        uint32_t slots = opcode_slot_count(op);
        uint32_t slot;

        written += (uint32_t)snprintf(out + written, capacity - written,
                                      "TABLES.slots[%u] = {", op);

        for (slot = 0; slot < slots; slot++) {
            written += (uint32_t)snprintf(out + written, capacity - written,
                                          "%s%u:%u",
                                          (slot > 0) ? "," : "",
                                          slot, opcode_slot_bits(op, slot));
        }

        written += (uint32_t)snprintf(out + written, capacity - written, "};\n");
    }

    written += (uint32_t)snprintf(out + written, capacity - written,
        "TABLES.op.DRIVE=%u; TABLES.op.ORDER_MOVE=%u; TABLES.op.ORDER_FACE=%u;\n"
        "TABLES.op.ORDER_STOP=%u; TABLES.op.HELLO=%u; TABLES.op.TICK=%u;\n"
        "TABLES.op.WALL=%u; TABLES.op.THING=%u; TABLES.op.FAN=%u;\n"
        "TABLES.op.REFUSAL=%u; TABLES.op.RECALL=%u; TABLES.op.END=%u;\n"
        "TABLES.op.LAYER=%u; TABLES.op.INTERACT=%u;\n",
        VERB_DRIVE, VERB_ORDER_MOVE, VERB_ORDER_FACE, VERB_ORDER_STOP,
        OP_HELLO, OP_TICK, OP_WALL, OP_THING, OP_FAN, OP_REFUSAL,
        OP_RECALL, OP_END, OP_LAYER, VERB_INTERACT);

    /*
     * And the compass, from the same table the server's own arithmetic uses.
     *
     * The dials belong to the view and the server never hears about them -- but
     * WHAT NORTH-EAST MEANS is a number, and two copies of a number drift. So the
     * view is handed the one that 106-controls holds, along with the distances
     * and the words, and there is nowhere for a second opinion to live.
     */
    written += (uint32_t)snprintf(out + written, capacity - written,
        "TABLES.compass = [];\nTABLES.reach = [];\n");

    {
        uint8_t aim;
        uint8_t reach;

        for (aim = 0; aim < AIM_COUNT; aim++) {
            struct dial d;
            wcoord x = 0;
            wcoord y = 0;

            dial_init(&d);
            d.aim = aim;
            d.reach = REACH_NEAR;
            dial_resolve(&d, 0, 0, &x, &y);

            /* As the point one "near" step away from the origin, so the view
             * divides rather than being handed a unit it has to scale. */
            written += (uint32_t)snprintf(out + written, capacity - written,
                "TABLES.compass[%u] = {x:%d, y:%d, name:\"%s\"};\n",
                aim, (int)x, (int)y, aim_name(aim));
        }

        for (reach = 0; reach < REACH_COUNT; reach++) {
            written += (uint32_t)snprintf(out + written, capacity - written,
                "TABLES.reach[%u] = {metres:%u, name:\"%s\"};\n",
                reach, reach_in_metres(reach), reach_name(reach));
        }

        written += (uint32_t)snprintf(out + written, capacity - written,
            "TABLES.nearMetres = %u;\n", reach_in_metres(REACH_NEAR));
    }

    /*
     * And the refusal sentences, from the same table the server refuses with. A
     * number arriving with no sentence anywhere would be a silent drop wearing a
     * disguise.
     */
    for (i = 0; i <= REFUSED_SUBJECT_IS_NOTHING; i++) {
        written += (uint32_t)snprintf(out + written, capacity - written,
                                      "TABLES.refusals[%u] = \"%s\";\n",
                                      i, refusal_sentence((uint16_t)i));
    }

    return written;
}
/* }}} */

/* {{{ int main */
/*
 * The engraving the last session left, or a sentence saying there is none.
 *
 * A MISSING ENGRAVING IS NOT AN ERROR. It is what a first session looks like,
 * and a bar that said nothing would be indistinguishable from a bar that failed
 * to load -- so it says what is true instead.
 */
/* {{{ static uint32_t read_the_engraving */
static uint32_t read_the_engraving(char *into, uint32_t capacity)
{
    FILE *in = fopen(ENGRAVING_PATH, "r");
    size_t length;

    if (in == NULL) {
        snprintf(into, capacity,
                 "no engraving yet -- this table has no history.\n"
                 "One is carved when a session ends.\n");
        return (uint32_t)strlen(into);
    }

    length = fread(into, 1, (size_t)capacity - 1u, in);
    fclose(in);

    into[length] = '\0';
    return (uint32_t)length;
}
/* }}} */

int main(int argc, char **argv)
{
    const char *address;
    uint16_t door_port;
    const char *name;
    uint16_t local_port = DEFAULT_LOCAL_PORT;

    int server_socket;
    uint8_t outcome = 0;
    uint16_t private_port = 0;

    struct httpd h;
    const char *why = NULL;

    static char tables_js[8192];
    uint32_t tables_length;

    /*
     * The previous session's engraving, read once at startup and hung in the
     * action bar. A table's history is visible while the table is playing.
     *
     * READ ONCE, not watched. The engraving is what the LAST session left; the
     * current one has no statistics yet and will not until it ends. That is what
     * a carving on a wall is.
     */
    static char engraving[ENGRAVING_MAX_BYTES];
    uint32_t engraving_length;

    struct served_file files[4];

    uint8_t from_server[65536];
    uint8_t from_browser[8192];

    if (argc < 4) {
        printf("usage: %s <address> <door-port> <name> [local-port]\n", argv[0]);
        printf("\n");
        printf("Holds one socket to the server and serves a browser on\n");
        printf("localhost. You are not hosting anything -- the world stays on\n");
        printf("the host's machine.\n");
        return 1;
    }

    address = argv[1];
    door_port = (uint16_t)atoi(argv[2]);
    name = argv[3];

    if (argc > 4) {
        local_port = (uint16_t)atoi(argv[4]);
    }

    /*
     * Line buffering, so that what this prints appears when it is printed rather
     * than when the program ends. Redirected to a file, C buffers a whole block
     * by default -- which makes a server that is running perfectly well look
     * exactly like a server that hung on startup.
     */
    setvbuf(stdout, NULL, _IOLBF, 0);

    signal(SIGINT, note_the_interrupt);
    signal(SIGTERM, note_the_interrupt);

    /*
     * The address is accepted and then ignored in favour of loopback, because
     * door_join_as_client only speaks to this machine. Connecting across a
     * network is the next thing this file needs and is not built -- said out
     * loud rather than silently pretended.
     */
    if (strcmp(address, "127.0.0.1") != 0 && strcmp(address, "localhost") != 0) {
        printf("This bridge can only reach a server on this machine so far.\n");
        printf("Given: %s\n", address);
        return 1;
    }

    printf("knocking on %s:%u as \"%s\" ...\n", address, door_port, name);

    server_socket = door_join_as_client(door_port, name, &outcome, &private_port);

    if (server_socket < 0) {
        printf("  refused: %s\n", join_sentence(outcome));
        return 1;
    }

    printf("  in, on port %u\n", private_port);

    tables_length = build_tables_js(tables_js, sizeof(tables_js));

    files[0].path = "/";
    files[0].content_type = "text/html; charset=utf-8";
    files[0].body = embedded_view_html;
    files[0].length = (uint32_t)strlen(embedded_view_html);

    files[1].path = "/view.js";
    files[1].content_type = "text/javascript; charset=utf-8";
    files[1].body = embedded_view_js;
    files[1].length = (uint32_t)strlen(embedded_view_js);

    files[2].path = "/tables.js";
    files[2].content_type = "text/javascript; charset=utf-8";
    files[2].body = tables_js;
    files[2].length = tables_length;

    engraving_length = read_the_engraving(engraving, sizeof(engraving));

    /*
     * ONE MORE ROW IN A FIXED TABLE, which is not the same as adding a
     * directory. The table is still matched by exact path, so ".." remains a
     * question this program cannot be asked.
     */
    files[3].path = "/engraving";
    files[3].content_type = "text/plain; charset=utf-8";
    files[3].body = engraving;
    files[3].length = engraving_length;

    if (!httpd_start(&h, local_port, files, 4, &why)) {
        printf("  could not serve a browser: %s\n", why);
        close(server_socket);
        return 1;
    }

    printf("\n");
    printf("  open  http://localhost:%u\n", local_port);
    printf("  ctrl-c to stop\n\n");

    while (!asked_to_stop) {
        ssize_t got;
        uint32_t said;

        /*
         * Server to browser. The frames carry exactly the instructions the
         * server sent, re-framed -- so the browser learns one format rather than
         * two, and this program is a translator rather than an interpreter.
         */
        got = recv(server_socket, from_server, sizeof(from_server), MSG_DONTWAIT);

        if (got > 0) {
            httpd_broadcast(&h, from_server, (uint32_t)got);
        } else if (got == 0) {
            printf("  the server hung up\n");
            break;
        } else if (errno != EAGAIN && errno != EWOULDBLOCK) {
            printf("  lost the server\n");
            break;
        }

        /* Browser to server. */
        said = httpd_poll(&h, from_browser, sizeof(from_browser));

        if (said > 0) {
            uint32_t written = 0;

            while (written < said) {
                ssize_t n = send(server_socket, from_browser + written,
                                 (size_t)(said - written), MSG_NOSIGNAL);

                if (n <= 0) {
                    if (n < 0 && (errno == EAGAIN || errno == EWOULDBLOCK)) {
                        continue;
                    }
                    break;
                }

                written += (uint32_t)n;
            }
        }

        /*
         * A short rest, so an idle bridge does not spin a core. Shorter than a
         * beat, so nothing waits on it.
         */
        {
            struct timespec gap;
            gap.tv_sec = 0;
            gap.tv_nsec = 2000000;   /* two milliseconds */
            nanosleep(&gap, NULL);
        }
    }

    printf("\n  closing up\n");

    httpd_stop(&h);
    close(server_socket);

    return 0;
}
/* }}} */
