#!/usr/bin/env luajit
--[[
messages-c.lua - writes the C unpacker for the gameplay messages, from their Lua descriptions (issue 804)

What this is: the renderer is C, and it has to read the server's messages
without going through Lua tables (turning 2,048 units into Lua tables
costs 1.7 ms). Rather than write a C reader by hand and hope it keeps up
with messages.lua, this reads the same descriptions and prints a C header
that reads every message. Change a message in messages.lua, run this again,
and the C side follows.

What the header holds, per message NAME:
  - NET_NAME, the message's type number (the first byte);
  - net_NAME, a struct with a field per description field (uint8_t,
    uint16_t, uint32_t or float), and for a list LIST: a pointer
    `LIST` to the caller's array of net_NAME_LIST records, `LIST_room`
    (how many fit, set by the caller) and `LIST_count` (how many came);
  - net_decode_NAME(bytes, length, out) -> NULL, or why it refused: the
    message ends early, has bytes left over, is of another type, or has
    more records than the caller made room for.
Numbers are read low byte first, as messages.lua writes them.

Usage: luajit messages-c.lua DIR > net-messages.h
]]

local DIR = arg[1] or "/mnt/mtwo/programming/ai-stuff/world-edit-to-execute"
package.path = DIR .. "/src/?.lua;" .. DIR .. "/src/?/init.lua;" .. package.path

local messages = require("net.messages")

local out = {}
-- {{{ local function w(...)
local function w(...) out[#out + 1] = string.format(...) end
-- }}}

local c_type = { u8 = "uint8_t", u16 = "uint16_t", u32 = "uint32_t", f32 = "float" }

w("/* net-messages.h - reads the gameplay messages in C (issues 803, 804).")
w(" * GENERATED by src/net/messages-c.lua from src/net/messages.lua; edit those, not this. */")
w("#ifndef NET_MESSAGES_H")
w("#define NET_MESSAGES_H")
w("#include <stddef.h>")
w("#include <stdint.h>")
w("#include <string.h>")
w("")
w("/* {{{ the readers of one number, low byte first; each moves *pos on */")
w("static inline uint32_t net_read_u(const uint8_t *b, size_t *pos, int n)")
w("{")
w("    uint32_t v = 0;")
w("    for (int i = n - 1; i >= 0; i--) v = v * 256u + b[*pos + (size_t)i];")
w("    *pos += (size_t)n;")
w("    return v;")
w("}")
w("static inline float net_read_f32(const uint8_t *b, size_t *pos)")
w("{")
w("    uint32_t u = net_read_u(b, pos, 4);")
w("    float f;")
w("    memcpy(&f, &u, 4);")
w("    return f;")
w("}")
w("/* }}} */")
w("")

-- {{{ local function record_bytes(fields)
-- The bytes one record of these fields takes (lists aren't allowed inside
-- lists: the C reader keeps every list flat).
local function record_bytes(fields, where)
    local sizes = { u8 = 1, u16 = 2, u32 = 4, f32 = 4 }
    local n = 0
    for _, f in ipairs(fields) do
        if not sizes[f[2]] then error(where .. "." .. f[1] .. ": a list inside a list can't be read in C", 0) end
        n = n + sizes[f[2]]
    end
    return n
end
-- }}}

local sizes = { u8 = 1, u16 = 2, u32 = 4, f32 = 4 }

-- {{{ local function read_field(indent, target, kind)
local function read_field(indent, target, kind)
    if kind == "f32" then
        w("%s%s = net_read_f32(b, &pos);", indent, target)
    else
        w("%s%s = (%s)net_read_u(b, &pos, %d);", indent, target, c_type[kind], sizes[kind])
    end
end
-- }}}

for _, d in ipairs(messages.descriptions) do
    local number, name, fields = d[1], d[2], d[3]
    local NAME = name:upper()
    w("/* {{{ %s */", name)
    w("#define NET_%s %d", NAME, number)
    -- the record structs of its lists
    for _, f in ipairs(fields) do
        if f[2] == "list" then
            record_bytes(f[3], name)
            w("typedef struct {")
            for _, rf in ipairs(f[3]) do w("    %s %s;", c_type[rf[2]], rf[1]) end
            w("} net_%s_%s;", name, f[1])
        end
    end
    w("typedef struct {")
    for _, f in ipairs(fields) do
        if f[2] == "list" then
            w("    net_%s_%s *%s;   /* the caller's array */", name, f[1], f[1])
            w("    int %s_room;     /* set by the caller: how many fit */", f[1])
            w("    int %s_count;    /* set by the reader: how many came */", f[1])
        else
            w("    %s %s;", c_type[f[2]], f[1])
        end
    end
    w("} net_%s;", name)
    w("static inline const char *net_decode_%s(const uint8_t *b, size_t length, net_%s *out)", name, name)
    w("{")
    w("    size_t pos = 0;")
    w("    if (length < 1 || b[0] != NET_%s) return \"%s: not this message\";", NAME, name)
    w("    pos = 1;")
    for _, f in ipairs(fields) do
        if f[2] == "list" then
            local each = record_bytes(f[3], name)
            w("    if (pos + 2 > length) return \"%s.%s: the message ends early\";", name, f[1])
            w("    {")
            w("        int count = (int)net_read_u(b, &pos, 2);")
            w("        if (count > out->%s_room) return \"%s.%s: more records than room for them\";", f[1], name, f[1])
            w("        if (pos + (size_t)count * %d > length) return \"%s.%s: the message ends early\";", each, name, f[1])
            w("        for (int i = 0; i < count; i++) {")
            for _, rf in ipairs(f[3]) do read_field("            ", string.format("out->%s[i].%s", f[1], rf[1]), rf[2]) end
            w("        }")
            w("        out->%s_count = count;", f[1])
            w("    }")
        else
            w("    if (pos + %d > length) return \"%s.%s: the message ends early\";", sizes[f[2]], name, f[1])
            read_field("    ", "out->" .. f[1], f[2])
        end
    end
    w("    if (pos != length) return \"%s: bytes left over after the last field\";", name)
    w("    return NULL;")
    w("}")
    w("/* }}} */")
    w("")
end
w("#endif")
print(table.concat(out, "\n"))
