#!/usr/bin/env lua
-- test_conversation-parser-harness-traffic.lua
-- Validates issues #021 and #022: the parser tells what the USER wrote apart
-- from what the HARNESS wrote into the user's seat, and strips the bytes that
-- were composed for a terminal rather than for a file.
--
-- WHY THIS MATTERS. A session log has one seat for text addressed to the model,
-- so Claude Code files its own messages there too. All of it used to arrive
-- under a "### User Request N" heading, indistinguishable from something the
-- user typed and taking a number in the same sequence, so the numbering no
-- longer counted the conversation. The escape sequences rode in on the same
-- traffic: invisible in a terminal, literal control characters everywhere else.
--
-- Self-contained: writes a fixture JSONL, runs the parser as a subprocess the
-- way the exporter does, and asserts on the markdown produced.
-- Run: `lua test_conversation-parser-harness-traffic.lua`.

-- {{{ DIR + paths
local DIR = arg[1] or "/home/ritz/programming/ai-stuff/scripts"
local PARSER = DIR .. "/libs/conversation-parser.lua"
local TMP = os.getenv("TMPDIR") or "/tmp"
-- }}}

-- {{{ run_parser(jsonl_text) -> markdown
local function run_parser(jsonl_text)
    local infile  = TMP .. "/envelope_fixture_in.jsonl"
    local outfile = TMP .. "/envelope_fixture_out.md"
    local f = assert(io.open(infile, "w"))
    f:write(jsonl_text)
    f:close()
    os.execute(string.format("lua %q %q %q >/dev/null 2>&1",
        PARSER, infile, outfile))
    local g = assert(io.open(outfile, "r"))
    local s = g:read("*all")
    g:close()
    return s
end
-- }}}

local failures = 0
-- {{{ check(condition, description)
local function check(condition, description)
    if condition then
        print("  ok   - " .. description)
    else
        print("  FAIL - " .. description)
        failures = failures + 1
    end
end
-- }}}

-- {{{ the fixture
-- Every kind of harness traffic found in the corpus, in the order a real
-- session produces it. Note the model confirmation carries "[1m" around
-- the model name: that is what the log really holds, and what the JSON decoder
-- turns into the raw escape byte the stripper has to remove.
local FIXTURE = table.concat({
    -- boilerplate that says "do not respond to this" and nothing else
    '{"type":"user","uuid":"e1","timestamp":"2026-07-07T00:00:00.000Z","message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>"}}',
    -- a slash command: records only that the picker opened
    '{"type":"user","uuid":"e2","timestamp":"2026-07-07T00:00:01.000Z","message":{"role":"user","content":"<command-name>/model</command-name>\\n<command-message>model</command-message>\\n<command-args></command-args>"}}',
    -- ...and, in a separate message, what it actually did
    '{"type":"user","uuid":"e3","timestamp":"2026-07-07T00:00:02.000Z","message":{"role":"user","content":"<local-command-stdout>Set model to \\u001b[1mFable 5.1\\u001b[22m and saved as your default</local-command-stdout>"}}',
    -- the first thing the user actually says
    '{"type":"user","uuid":"e4","timestamp":"2026-07-07T00:00:03.000Z","message":{"role":"user","content":"my first real question"}}',
    '{"type":"assistant","uuid":"a1","timestamp":"2026-07-07T00:00:04.000Z","message":{"role":"assistant","model":"claude-test-1","content":[{"type":"text","text":"an answer"}]}}',
    -- a background task reporting in, whose result is a huge machine dump
    '{"type":"user","uuid":"e5","timestamp":"2026-07-07T00:00:05.000Z","message":{"role":"user","content":"<task-notification><task-id>wf0test</task-id><status>completed</status><summary>Swept the corpus and counted things</summary><result>{\\"enormous\\":\\"machine readable dump nobody reads\\"}</result></task-notification>"}}',
    -- content arriving as a LIST rather than a string: used to yield a heading
    -- with nothing under it
    '{"type":"user","uuid":"e6","timestamp":"2026-07-07T00:00:06.000Z","message":{"role":"user","content":[{"type":"text","text":"a question that arrived as a list"}]}}',
    '{"type":"assistant","uuid":"a2","timestamp":"2026-07-07T00:00:07.000Z","message":{"role":"assistant","model":"claude-test-1","content":[{"type":"text","text":"a second answer"}]}}',
    -- a reminder addressed to the model, riding along with real user words
    '{"type":"user","uuid":"e7","timestamp":"2026-07-07T00:00:08.000Z","message":{"role":"user","content":"words the user typed<system-reminder>machine text addressed to the model</system-reminder>"}}',
}, "\n") .. "\n"
-- }}}

local out = run_parser(FIXTURE)

print("Terminal escape codes (issue 021):")
check(not out:find("\27", 1, true),
    "no raw escape byte survives into the file")
check(not out:find("[1m", 1, true) and not out:find("[22m", 1, true),
    "no orphaned sequence body is left behind either")
check(out:find("Fable 5.1", 1, true),
    "the text the sequences were decorating is kept")

print("Harness traffic is not the user (issue 022):")
check(not out:find("DO NOT respond", 1, true),
    "the boilerplate caveat is dropped entirely")
check(not out:find("machine text addressed to the model", 1, true),
    "a system reminder is dropped")
check(out:find("words the user typed", 1, true),
    "...but the user's own words in the same message are kept")
check(not out:find("<command%-name>") and not out:find("<local%-command%-stdout>"),
    "no envelope tag leaks through as literal text")

print("A slash command reads as one line:")
check(out:find("`/model` .- Set model to", 1, false),
    "the command and what it did are joined into one line")

print("A background task is reduced to its summary:")
check(out:find("Swept the corpus and counted things", 1, true),
    "the summary survives")
check(not out:find("machine readable dump nobody reads", 1, true),
    "the machine dump does not")

print("Numbering counts the conversation, not the traffic:")
check(out:find("### User Request 1\n\nmy first real question", 1, true),
    "the user's first real words are User Request 1, not request 5")
check(out:find("a question that arrived as a list", 1, true),
    "a message whose content arrived as a list still renders its words")
check(not out:find("### User Request %d+\n\n%-%-%-%-"),
    "no heading is written with nothing underneath it")

print("")
if failures == 0 then
    print("PASS: all checks passed")
    os.exit(0)
else
    print("FAIL: " .. failures .. " check(s) failed")
    os.exit(1)
end
