#!/usr/bin/env luajit
-- Test script for html_gen library

package.path = package.path .. ";./lua/?.lua"

local htmlgen = require("html_gen")

print("HTML Generator Library Test")
print("============================")

-- Issue 8-059: route this test's output through the project's tmpfs-backed
-- tmp/ symlink. DIR resolves from arg[1] or the hard-coded project path.
local DIR = (arg and arg[1]) or "/mnt/mtwo/programming/ai-stuff/neocities-modernization"
os.execute(string.format('"%s/scripts/ensure-tmp-symlink" "%s"', DIR, DIR))
local TEST_DIR = DIR .. "/tmp/htmlgen-test"

-- Create test directory
os.execute("mkdir -p " .. TEST_DIR)

-- Initialize with 4 threads
print("\n1. Initializing with 4 threads...")
local ctx = htmlgen.init(4)
print("   Context created successfully")

-- Add test files
print("\n2. Adding test files...")
local num_files = 100
for i = 1, num_files do
    local content = string.format([[<!DOCTYPE html>
<html>
<head><title>Test Page %d</title></head>
<body>
<h1>Test Page %d</h1>
<p>This is test content for page %d.</p>
<p>Generated by htmlgen library.</p>
</body>
</html>]], i, i, i)

    htmlgen.add_file(ctx, string.format("%s/page-%04d.html", TEST_DIR, i), content)
end
print(string.format("   Added %d files to queue", num_files))

-- Write all files
print("\n3. Writing files in parallel...")
htmlgen.write_all(ctx)
print("   Write completed")

-- Get statistics
print("\n4. Statistics:")
local stats = htmlgen.get_stats(ctx)
print(string.format("   Total files:    %d", stats.total_files))
print(string.format("   Files written:  %d", stats.files_written))
print(string.format("   Files failed:   %d", stats.files_failed))
print(string.format("   Total bytes:    %d", stats.total_bytes))
print(string.format("   Elapsed time:   %.3f seconds", stats.elapsed_seconds))
print(string.format("   Throughput:     %.1f files/sec", stats.files_written / stats.elapsed_seconds))

-- Cleanup
print("\n5. Cleaning up...")
htmlgen.destroy(ctx)

-- Verify files exist
print("\n6. Verifying output...")
local count = 0
for i = 1, num_files do
    local f = io.open(string.format("%s/page-%04d.html", TEST_DIR, i), "r")
    if f then
        count = count + 1
        f:close()
    end
end
print(string.format("   Found %d/%d files", count, num_files))

-- Cleanup test files
os.execute("rm -rf " .. TEST_DIR)

if count == num_files and stats.files_failed == 0 then
    print("\n✓ All tests passed!")
else
    print("\n✗ Some tests failed!")
    os.exit(1)
end
