-- supcom-derivative-clone — a factory war on dunes where nothing is out of range
-- Copyright (C) 2026 gabrilend
--
-- This program is free software: you can redistribute it and/or modify it
-- under the terms of the GNU Affero General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or (at
-- your option) any later version.
--
-- This program is distributed in the hope that it will be useful, but
-- WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
-- General Public License for more details.
--
-- You should have received a copy of the GNU Affero General Public License
-- along with this program. If not, see <https://www.gnu.org/licenses/>.
--
-- SPDX-License-Identifier: AGPL-3.0-or-later

-- 017-the-documentation-becomes-html.lua
--
-- Every document, issue, companion and test, turned into pages you can browse.
--
-- ## The same separation, one level up
--
-- **The Markdown is the data and the HTML is a view of it**, generated by a tool
-- rather than maintained by hand. That is the same rule the simulation and the
-- viewer follow, applied to the project's own prose -- and for the same reason: a
-- hand-kept second copy of anything is a copy that will disagree with the first.
--
-- ## What it is for
--
-- This project is read far more than it is run. There are more words in it than
-- code, the words came first, and reconstructing the software means reading them.
-- But they reference each other constantly and a directory of files is a bad way
-- to follow a reference -- so: every page reachable from every other, a table of
-- contents down the side that can be filtered, **every issue number a link**, and
-- the ideas the design rests on drawn as things you can push on.
--
-- ## What it never does
--
-- It never runs a command. The output directory is made by the shell wrapper that
-- calls this; everything here is a read of a directory listing or a write of one
-- file. It never emits a dead link: a Markdown link to a file that is not there is
-- collected as an error and the run fails at the end, naming every one.
--
-- Usage:
--   luajit scripts/017-the-documentation-becomes-html.lua --dir /path/to/project

local M = {}

-- {{{ M.PALETTE
-- The game's own colours: night over a dune field. Sand for one side, sea for the
-- other, on the dark ground the field is drawn on.
M.PALETTE = [[
:root {
  --ground:   #0f0e0b;
  --panel:    #17150f;
  --edge:     #2a2619;
  --ink:      #d6cfbf;
  --dim:      #8a826f;
  --sand:     #e0a95a;
  --sea:      #4fb3c9;
  --bone:     #ede6d3;
  --rust:     #b8452b;
  --green:    #8cbf6a;
  --dune:     #6b5330;
}
]]
-- }}}

-- {{{ M.STYLE
M.STYLE = [[
* { box-sizing: border-box; }
body {
  margin: 0; background: var(--ground); color: var(--ink);
  font: 15.5px/1.65 "Iowan Old Style", "Palatino Linotype", Palatino, Georgia, serif;
}
a { color: var(--sea); text-decoration: none; border-bottom: 1px solid #2b4d54; }
a:hover { color: var(--sand); border-bottom-color: var(--sand); }

#shell { display: flex; min-height: 100vh; }

#contents {
  width: 300px; flex: 0 0 300px; background: var(--panel);
  border-right: 1px solid var(--edge); padding: 20px 0 60px;
  position: sticky; top: 0; height: 100vh; overflow-y: auto;
}
#contents h1 {
  font-size: 14px; letter-spacing: .14em; text-transform: uppercase;
  color: var(--sand); margin: 0 20px 4px; font-weight: 600;
}
#contents .tagline { margin: 0 20px 18px; color: var(--dim); font-size: 12.5px; font-style: italic; }
#contents section { margin-bottom: 14px; }
#contents h2 {
  font-size: 11px; letter-spacing: .18em; text-transform: uppercase;
  color: var(--dim); margin: 14px 20px 5px; font-weight: 600;
}
#contents a {
  display: block; padding: 3px 20px 3px 20px; border: 0;
  font-size: 13.5px; color: var(--ink); line-height: 1.4;
}
#contents a:hover { background: #211d14; color: var(--sand); }
#contents a.here { background: #211d14; color: var(--sand); border-left: 3px solid var(--sand); padding-left: 17px; }
#contents .index { color: var(--dim); font-variant-numeric: tabular-nums; margin-right: 7px; }

#filter {
  margin: 0 20px 12px; width: calc(100% - 40px); background: var(--ground);
  border: 1px solid var(--edge); color: var(--ink); padding: 6px 9px;
  font: inherit; font-size: 13px; border-radius: 3px;
}
#filter:focus { outline: 0; border-color: var(--sand); }

#page { flex: 1; min-width: 0; padding: 42px 56px 120px; max-width: 920px; }
h1, h2, h3, h4 { font-family: "Inter", "Helvetica Neue", Arial, sans-serif; line-height: 1.25; }
h1 { font-size: 30px; color: var(--sand); margin: 0 0 26px; font-weight: 600; }
h2 { font-size: 21px; color: var(--bone); margin: 38px 0 12px; font-weight: 600;
     border-bottom: 1px solid var(--edge); padding-bottom: 7px; }
h3 { font-size: 16.5px; color: var(--sea); margin: 26px 0 8px; font-weight: 600; }
h4 { font-size: 14.5px; color: var(--dim); margin: 20px 0 6px;
     text-transform: uppercase; letter-spacing: .09em; }
p { margin: 0 0 15px; }
strong { color: var(--bone); font-weight: 600; }
em { color: var(--dim); }
hr { border: 0; border-top: 1px solid var(--edge); margin: 34px 0; }

blockquote {
  margin: 20px 0; padding: 3px 0 3px 20px; border-left: 3px solid var(--sand);
  color: var(--bone); font-style: italic;
}
blockquote p { margin: 0 0 8px; }
blockquote p:last-child { margin: 0; }

ul, ol { margin: 0 0 15px; padding-left: 24px; }
li { margin-bottom: 5px; }

table { border-collapse: collapse; margin: 20px 0; width: 100%; font-size: 14px; }
th, td { text-align: left; padding: 7px 12px; border-bottom: 1px solid var(--edge); vertical-align: top; }
th { color: var(--dim); font-weight: 600; text-transform: uppercase;
     letter-spacing: .08em; font-size: 11.5px; }
tr:hover td { background: #1c1913; }

code {
  font-family: "Berkeley Mono", "SF Mono", Menlo, Consolas, monospace;
  font-size: 13px; background: #1e1a12; padding: 1.5px 5px; border-radius: 3px;
  color: var(--bone);
}
pre {
  background: #13110c; border: 1px solid var(--edge); border-left: 3px solid var(--sea);
  padding: 14px 17px; overflow-x: auto; border-radius: 3px; margin: 18px 0;
}
pre code { background: none; padding: 0; font-size: 12.5px; line-height: 1.6; }

.kw { color: #d68fd6; }
.str { color: var(--green); }
.num { color: var(--sand); }
.cmt { color: #6a6252; font-style: italic; }

.issue-link { border-bottom: 1px dotted var(--sand); color: var(--sand); }
.badge {
  display: inline-block; font-size: 11px; letter-spacing: .08em; text-transform: uppercase;
  padding: 2px 8px; border-radius: 10px; margin-left: 8px; vertical-align: middle;
  font-family: "Inter", sans-serif;
}
.badge.built { background: #1e3320; color: var(--green); }
.badge.part  { background: #33301c; color: var(--sand); }
.badge.none  { background: #26221a; color: var(--dim); }

figure { margin: 24px 0; }
figcaption { color: var(--dim); font-size: 13px; font-style: italic; margin-top: 8px; }
svg { max-width: 100%; }

.toy { background: var(--panel); border: 1px solid var(--edge); border-radius: 4px;
       padding: 16px 18px; margin: 22px 0; }
.toy h4 { margin: 0 0 10px; color: var(--sand); }
.toy label { display: inline-block; margin: 4px 18px 4px 0; font-size: 13px; color: var(--dim); }
.toy input[type=range] { vertical-align: middle; width: 160px; accent-color: var(--sand); }
.toy input[type=number] { width: 70px; background: var(--ground); color: var(--ink);
       border: 1px solid var(--edge); padding: 3px 6px; font: inherit; font-size: 13px; }
.toy output, .toy .readout { color: var(--bone); font-family: "Berkeley Mono", Menlo, monospace; font-size: 13px; }
.toy .verdict { font-family: "Inter", sans-serif; font-weight: 600; margin-left: 10px; }
.toy .yes { color: var(--green); } .toy .no { color: var(--rust); }
.toy button { background: var(--ground); color: var(--ink); border: 1px solid var(--edge);
       padding: 4px 10px; font: inherit; font-size: 13px; border-radius: 3px; cursor: pointer; }
.toy button:hover { border-color: var(--sand); color: var(--sand); }

#page > footer { margin-top: 60px; padding-top: 18px; border-top: 1px solid var(--edge);
                 color: var(--dim); font-size: 13px; }
]]
-- }}}

-- {{{ local function escape()
local function escape(text)
  text = text:gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;")
  return text
end
-- }}}

-- {{{ local function highlight_lua()
-- Syntax highlighting, for Lua, done by hand. Three passes over a line rather
-- than a real lexer, because the thing being highlighted is already correct Lua
-- that a real compiler has read -- this only has to make it easier to look at.
local function highlight_lua(code)
  local out = {}
  for line in (code .. "\n"):gmatch("(.-)\n") do
    local comment = line:match("^(.-)%-%-")
    local body, tail = line, nil
    if comment ~= nil then
      body = comment
      tail = line:sub(#comment + 1)
    end

    body = escape(body)
    body = body:gsub('(".-")', "<span class='str'>%1</span>")
    body = body:gsub("(%f[%w])(%d+%.?%d*)(%f[%W])", "%1<span class='num'>%2</span>%3")
    for _, word in ipairs({"local", "function", "end", "if", "then", "else", "elseif",
                           "for", "while", "do", "return", "and", "or", "not", "nil",
                           "true", "false", "in", "break", "repeat", "until"}) do
      body = body:gsub("(%f[%w])(" .. word .. ")(%f[%W])", "%1<span class='kw'>%2</span>%3")
    end

    if tail ~= nil then
      out[#out + 1] = body .. "<span class='cmt'>" .. escape(tail) .. "</span>"
    else
      out[#out + 1] = body
    end
  end
  return table.concat(out, "\n")
end
-- }}}

-- {{{ local function highlight_shell()
-- The same for shell: comments and strings, nothing more. Enough to read a
-- script's explanatory header apart from its commands.
local function highlight_shell(code)
  local out = {}
  for line in (code .. "\n"):gmatch("(.-)\n") do
    local body, tail = line:match("^(.-)(#.*)$")
    if body == nil then body = line end
    body = escape(body)
    body = body:gsub('(".-")', "<span class='str'>%1</span>")
    body = body:gsub("('.-')", "<span class='str'>%1</span>")
    if tail ~= nil then
      out[#out + 1] = body .. "<span class='cmt'>" .. escape(tail) .. "</span>"
    else
      out[#out + 1] = body
    end
  end
  return table.concat(out, "\n")
end
-- }}}

local HIGHLIGHT = {
  lua = highlight_lua,
  sh = highlight_shell,
  bash = highlight_shell,
}

-- {{{ local function inline()
-- The inline half of Markdown, plus the things this project needs that Markdown
-- has no syntax for: **an issue number is a link**, a Markdown link to a
-- document becomes a link to the generated page, and a code span naming a source
-- file becomes a link to that file's companion.
--
-- `links` maps every issue number, page slug and source stem to a page slug.
-- `report` is where an unresolvable Markdown link is written down, because a dead
-- link in generated documentation is a bug in the source Markdown.
local function inline(text, links, report, page_name)
  text = escape(text)

  -- Code first, so nothing else formats inside it. A span that names a known
  -- companion is linked to it.
  local spans = {}
  text = text:gsub("`([^`]+)`", function(code)
    local stem = code:match("([%w%-]+)%.lua$") or code:match("^([%w%-]+)$")
    local target = stem and links.stem[stem]
    if target ~= nil then
      spans[#spans + 1] = "<a href='" .. target .. ".html'><code>" .. code .. "</code></a>"
    else
      spans[#spans + 1] = "<code>" .. code .. "</code>"
    end
    return "\1" .. #spans .. "\1"
  end)

  text = text:gsub("%*%*([^*]+)%*%*", "<strong>%1</strong>")
  text = text:gsub("%*([^*]+)%*", "<em>%1</em>")

  -- Markdown links, rewritten to the generated page names. A target ending in .md
  -- is a page here and must exist; anything else is passed through as written.
  text = text:gsub("%[([^%]]+)%]%(([^)]+)%)", function(label, target)
    local page = target:match("([^/]+)%.md$")
    if page ~= nil then
      if links.page[page] == nil then
        report[#report + 1] = page_name .. " links to " .. target .. ", which has no page"
      end
      return "<a href='" .. page .. ".html'>" .. label .. "</a>"
    end
    local bare = target:match("([^/]+)$")
    if links.page[bare] ~= nil then
      return "<a href='" .. bare .. ".html'>" .. label .. "</a>"
    end
    return "<a href='" .. target .. "'>" .. label .. "</a>"
  end)

  -- And the issue numbers: "issue 102", "issues 102, 103", "308a".
  text = text:gsub("(%f[%a][Ii]ssues?%s+)(%d%d%d%l?)", function(word, number)
    local target = links.issue[number]
    if target == nil then
      return word .. number
    end
    return word .. "<a class='issue-link' href='" .. target .. ".html'>" .. number .. "</a>"
  end)
  -- A comma-separated run after "issues" links each member.
  text = text:gsub("(</a>, )(%d%d%d%l?)", function(sep, number)
    local target = links.issue[number]
    if target == nil then return sep .. number end
    return sep .. "<a class='issue-link' href='" .. target .. ".html'>" .. number .. "</a>"
  end)

  text = text:gsub("\1(%d+)\1", function(index)
    return spans[tonumber(index)]
  end)
  return text
end
-- }}}

-- {{{ local function toy_html()
-- The interactive pieces. Each is a self-contained block of HTML and script,
-- keyed by the name a document asks for with a line "<!-- toy: name -->". None
-- of them reads a catalogue table: the toys illustrate the *rules*, and the
-- rules are stated in the documents; the numbers belong to the catalogue and
-- appear here only as sliders the reader sets.
local TOYS = {}

TOYS.sightline = [[
<div class='toy' id='toy-sightline'>
<h4>A sightline over the dunes</h4>
<p>Drag the two marks. The line between the viewer's eye and the target's profile
is clear only if it never dips below the sand. Raise an eye and watch what a
crest hides.</p>
<svg id='sl-svg' viewBox='0 0 720 220' width='100%' height='220' style='cursor:crosshair'></svg>
<label>eye height <input type='range' id='sl-eye' min='2' max='40' value='8'> <output id='sl-eye-out'>8</output></label>
<label>target profile <input type='range' id='sl-prof' min='2' max='40' value='8'> <output id='sl-prof-out'>8</output></label>
<label>roughness <input type='range' id='sl-rough' min='0' max='100' value='45'></label>
<button id='sl-reseed'>new dunes</button>
<span class='verdict' id='sl-verdict'></span>
<script>
(function () {
  var svg = document.getElementById('sl-svg');
  var W = 720, H = 220, N = 180;
  var seed = 7, heights = [];
  function rnd() { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return seed / 0x7fffffff; }
  function raise() {
    var rough = +document.getElementById('sl-rough').value / 100;
    var a = rnd() * 6.28, b = rnd() * 6.28, c = rnd() * 6.28;
    heights = [];
    for (var i = 0; i < N; i++) {
      var t = i / N;
      var h = 60 + 45 * Math.sin(t * 6.28 * 1.3 + a) + 25 * rough * Math.sin(t * 6.28 * 4.1 + b)
            + 12 * rough * Math.sin(t * 6.28 * 9.7 + c);
      heights.push(h);
    }
  }
  var viewer = { i: 30 }, target = { i: 140 }, dragging = null;
  function groundAt(x) { var i = Math.max(0, Math.min(N - 1, Math.round(x / W * (N - 1)))); return heights[i]; }
  function draw() {
    var eye = +document.getElementById('sl-eye').value, prof = +document.getElementById('sl-prof').value;
    document.getElementById('sl-eye-out').textContent = eye;
    document.getElementById('sl-prof-out').textContent = prof;
    var pts = [];
    for (var i = 0; i < N; i++) pts.push((i / (N - 1) * W).toFixed(1) + ',' + (H - heights[i]).toFixed(1));
    var x1 = viewer.i / (N - 1) * W, y1 = H - heights[viewer.i] - eye;
    var x2 = target.i / (N - 1) * W, y2 = H - heights[target.i] - prof;
    var clear = true;
    var lo = Math.min(viewer.i, target.i), hi = Math.max(viewer.i, target.i);
    for (var j = lo; j <= hi; j++) {
      var f = (hi === lo) ? 0 : (j - lo) / (hi - lo);
      var ya = (viewer.i < target.i) ? y1 : y2, yb = (viewer.i < target.i) ? y2 : y1;
      var lineY = ya + (yb - ya) * f;
      if (lineY > H - heights[j]) { clear = false; break; }
    }
    svg.innerHTML =
      "<rect x='0' y='0' width='" + W + "' height='" + H + "' fill='#13110c'/>" +
      "<polygon points='0," + H + " " + pts.join(' ') + " " + W + "," + H + "' fill='#6b5330'/>" +
      "<polyline points='" + pts.join(' ') + "' fill='none' stroke='#e0a95a' stroke-width='1.5'/>" +
      "<line x1='" + x1 + "' y1='" + y1 + "' x2='" + x2 + "' y2='" + y2 + "' stroke='" + (clear ? '#8cbf6a' : '#b8452b') + "' stroke-width='2' stroke-dasharray='" + (clear ? '' : '6 4') + "'/>" +
      "<line x1='" + x1 + "' y1='" + (H - heights[viewer.i]) + "' x2='" + x1 + "' y2='" + y1 + "' stroke='#4fb3c9' stroke-width='2'/>" +
      "<circle cx='" + x1 + "' cy='" + y1 + "' r='6' fill='#4fb3c9'/>" +
      "<line x1='" + x2 + "' y1='" + (H - heights[target.i]) + "' x2='" + x2 + "' y2='" + y2 + "' stroke='#e0a95a' stroke-width='2'/>" +
      "<circle cx='" + x2 + "' cy='" + y2 + "' r='6' fill='#e0a95a'/>";
    var v = document.getElementById('sl-verdict');
    v.textContent = clear ? 'seen -- in range, because everything is' : 'hidden by the sand';
    v.className = 'verdict ' + (clear ? 'yes' : 'no');
  }
  function pick(evt) {
    var box = svg.getBoundingClientRect();
    var x = (evt.clientX - box.left) / box.width * W;
    var i = Math.round(x / W * (N - 1));
    return Math.max(0, Math.min(N - 1, i));
  }
  svg.addEventListener('mousedown', function (e) {
    var i = pick(e);
    dragging = (Math.abs(i - viewer.i) <= Math.abs(i - target.i)) ? viewer : target;
    dragging.i = i; draw();
  });
  window.addEventListener('mousemove', function (e) { if (dragging) { dragging.i = pick(e); draw(); } });
  window.addEventListener('mouseup', function () { dragging = null; });
  ['sl-eye', 'sl-prof'].forEach(function (id) { document.getElementById(id).addEventListener('input', draw); });
  document.getElementById('sl-rough').addEventListener('input', function () { raise(); draw(); });
  document.getElementById('sl-reseed').addEventListener('click', function () { raise(); draw(); });
  raise(); draw();
})();
</script>
</div>
]]

TOYS.timer = [[
<div class='toy' id='toy-timer'>
<h4>A periodic effect is a pair of integers</h4>
<p>A unit stores a value and the increment it was written at. Move the counter
and watch the current value derive itself: <code>min(cap, written + (now - at))</code>.
Press <em>hit</em> to take damage, which rewrites the pair at the current increment.</p>
<label>increment now <input type='range' id='tm-now' min='0' max='60' value='0'> <output id='tm-now-out'>0</output></label>
<label>cap <input type='number' id='tm-cap' value='100'></label>
<button id='tm-hit'>hit for 25</button>
<button id='tm-reset'>reset</button>
<p class='readout'>written = <span id='tm-written'>100</span>, at = <span id='tm-at'>0</span>
&nbsp;&nbsp;→&nbsp;&nbsp; current = <strong id='tm-current'>100</strong></p>
<script>
(function () {
  var written = 100, at = 0;
  function now() { return +document.getElementById('tm-now').value; }
  function cap() { return +document.getElementById('tm-cap').value; }
  function current() { return Math.min(cap(), written + (now() - at)); }
  function draw() {
    document.getElementById('tm-now-out').textContent = now();
    document.getElementById('tm-written').textContent = written;
    document.getElementById('tm-at').textContent = at;
    document.getElementById('tm-current').textContent = current();
  }
  document.getElementById('tm-now').addEventListener('input', draw);
  document.getElementById('tm-cap').addEventListener('input', draw);
  document.getElementById('tm-hit').addEventListener('click', function () {
    written = current() - 25; at = now(); draw();
  });
  document.getElementById('tm-reset').addEventListener('click', function () {
    written = cap(); at = 0; document.getElementById('tm-now').value = 0; draw();
  });
  draw();
})();
</script>
</div>
]]

TOYS.costs = [[
<div class='toy' id='toy-costs'>
<h4>The cost table is a shape</h4>
<p>Pick a magnitude for the resource an alignment leans on and read off the
other. The ratios are the design; the magnitude is the catalogue's.</p>
<label>tier-one magnitude <input type='range' id='ct-mag' min='10' max='100' value='50'> <output id='ct-mag-out'>50</output></label>
<table><thead><tr><th>alignment</th><th>mass</th><th>energy</th><th>tier two</th><th>experimental</th></tr></thead>
<tbody id='ct-rows'></tbody></table>
<script>
(function () {
  var rows = [
    ['land', 10, 1], ['air', 1, 10], ['sea', 10, 10], ['land that shoots air', 1, 1]
  ];
  function draw() {
    var m = +document.getElementById('ct-mag').value;
    document.getElementById('ct-mag-out').textContent = m;
    var out = '';
    rows.forEach(function (r) {
      var big = Math.max(r[1], r[2]);
      var mass = Math.round(m * r[1] / big), energy = Math.round(m * r[2] / big);
      out += '<tr><td>' + r[0] + '</td><td>' + mass + '</td><td>' + energy + '</td><td>' +
             (mass * 10) + ' / ' + (energy * 10) + '</td><td>' + (mass * 100) + ' / ' + (energy * 100) + '</td></tr>';
    });
    document.getElementById('ct-rows').innerHTML = out;
  }
  document.getElementById('ct-mag').addEventListener('input', draw);
  draw();
})();
</script>
</div>
]]

TOYS.ground = [[
<div class='toy' id='toy-ground'>
<h4>Losing ground costs bodies</h4>
<p>The fraction of territory lost is the fraction of the roster hurt. Slide the
loss and read the infirmary.</p>
<label>territory lost <input type='range' id='gr-loss' min='0' max='100' value='4'> <output id='gr-loss-out'>4</output>%</label>
<label>builders <input type='number' id='gr-b' value='50'></label>
<label>engineers <input type='number' id='gr-e' value='12'></label>
<p class='readout'>hurt: <strong id='gr-hb'>2</strong> builders and <strong id='gr-he'>0</strong> engineers</p>
<svg id='gr-svg' viewBox='0 0 720 40' width='100%' height='40'></svg>
<script>
(function () {
  function draw() {
    var loss = +document.getElementById('gr-loss').value;
    var b = +document.getElementById('gr-b').value, e = +document.getElementById('gr-e').value;
    var hb = Math.round(b * loss / 100), he = Math.round(e * loss / 100);
    document.getElementById('gr-loss-out').textContent = loss;
    document.getElementById('gr-hb').textContent = hb;
    document.getElementById('gr-he').textContent = he;
    var s = "<rect x='0' y='4' width='720' height='14' fill='#2a2619'/>" +
            "<rect x='0' y='4' width='" + (720 * (100 - loss) / 100) + "' height='14' fill='#e0a95a'/>" +
            "<text x='0' y='34' fill='#8a826f' font-size='11' font-family='Inter,sans-serif'>held ground; the rest changed hands</text>";
    document.getElementById('gr-svg').innerHTML = s;
  }
  ['gr-loss', 'gr-b', 'gr-e'].forEach(function (id) { document.getElementById(id).addEventListener('input', draw); });
  draw();
})();
</script>
</div>
]]

TOYS.lockstep = [[
<div class='toy' id='toy-lockstep'>
<h4>Commands are scheduled for a later tick</h4>
<p>A command issued at a tick is stamped for that tick plus the delay and sent at
once. The other machine may run the stamped tick only once the command has
arrived. Slide the wire's latency past the delay and watch the stall appear.</p>
<label>delay (ticks) <input type='range' id='ls-delay' min='1' max='12' value='5'> <output id='ls-delay-out'>5</output></label>
<label>latency (ticks) <input type='range' id='ls-lat' min='0' max='16' value='2'> <output id='ls-lat-out'>2</output></label>
<svg id='ls-svg' viewBox='0 0 720 110' width='100%' height='110'></svg>
<span class='verdict' id='ls-verdict'></span>
<script>
(function () {
  function draw() {
    var delay = +document.getElementById('ls-delay').value, lat = +document.getElementById('ls-lat').value;
    document.getElementById('ls-delay-out').textContent = delay;
    document.getElementById('ls-lat-out').textContent = lat;
    var issued = 3, stamped = issued + delay, arrives = issued + lat;
    var scale = 720 / 24, s = '';
    for (var t = 0; t < 24; t++) {
      s += "<rect x='" + (t * scale + 1) + "' y='20' width='" + (scale - 2) + "' height='18' fill='" +
           (t === issued ? '#4fb3c9' : (t === stamped ? '#e0a95a' : '#2a2619')) + "'/>";
      s += "<text x='" + (t * scale + scale / 2) + "' y='14' fill='#8a826f' font-size='9' text-anchor='middle' font-family='Inter,sans-serif'>" + t + "</text>";
    }
    s += "<line x1='" + (issued * scale + scale / 2) + "' y1='38' x2='" + (arrives * scale + scale / 2) + "' y2='70' stroke='#4fb3c9' stroke-width='2'/>";
    s += "<rect x='" + (arrives * scale + 1) + "' y='70' width='" + (scale - 2) + "' height='18' fill='#4fb3c9'/>";
    s += "<text x='0' y='100' fill='#8a826f' font-size='11' font-family='Inter,sans-serif'>issued at " + issued + ", stamped for " + stamped + ", arrives at the peer at " + arrives + "</text>";
    document.getElementById('ls-svg').innerHTML = s;
    var v = document.getElementById('ls-verdict');
    if (arrives <= stamped) { v.textContent = 'in time: the peer runs tick ' + stamped + ' without waiting'; v.className = 'verdict yes'; }
    else { v.textContent = 'stall: the peer must wait ' + (arrives - stamped) + ' tick(s) at tick ' + stamped; v.className = 'verdict no'; }
  }
  ['ls-delay', 'ls-lat'].forEach(function (id) { document.getElementById(id).addEventListener('input', draw); });
  draw();
})();
</script>
</div>
]]

local function toy_html(name, report, page_name)
  local html = TOYS[name]
  if html == nil then
    report[#report + 1] = page_name .. " asks for a toy called '" .. name .. "', which does not exist"
    return "<p><em>[no toy called " .. escape(name) .. "]</em></p>"
  end
  return html
end
-- }}}

-- {{{ local function render()
-- Markdown to HTML. The subset this project actually writes, and nothing else:
-- headings, lists, tables, quotes, fenced code, rules, and the inline marks. A
-- line "<!-- toy: name -->" is replaced by the named interactive piece.
local function render(markdown, links, report, page_name)
  local out = {}
  local in_list, in_table, in_code = false, false, false
  local code_buffer, code_kind = {}, ""

  local function close_list()
    if in_list then out[#out + 1] = "</" .. in_list .. ">" ; in_list = false end
  end
  local function close_table()
    if in_table then out[#out + 1] = "</tbody></table>" ; in_table = false end
  end
  local function line_inline(text)
    return inline(text, links, report, page_name)
  end

  for line in (markdown .. "\n"):gmatch("(.-)\n") do
    if in_code then
      if line:match("^```") then
        in_code = false
        local body = table.concat(code_buffer, "\n")
        local painter = HIGHLIGHT[code_kind]
        out[#out + 1] = "<pre><code>" .. (painter and painter(body) or escape(body)) .. "</code></pre>"
        code_buffer = {}
      else
        code_buffer[#code_buffer + 1] = line
      end
    elseif line:match("^```") then
      close_list() ; close_table()
      in_code = true
      code_kind = line:match("^```(%w*)") or ""
    elseif line:match("^<!%-%- toy: ([%w%-]+) %-%->%s*$") then
      close_list() ; close_table()
      out[#out + 1] = toy_html(line:match("^<!%-%- toy: ([%w%-]+) %-%->"), report, page_name)
    elseif line:match("^%s*$") then
      close_list() ; close_table()
    elseif line:match("^#+%s") then
      close_list() ; close_table()
      local hashes, rest = line:match("^(#+)%s+(.*)$")
      local level = #hashes
      out[#out + 1] = string.format("<h%d>%s</h%d>", level, line_inline(rest), level)
    elseif line:match("^%-%-%-+%s*$") then
      close_list() ; close_table()
      out[#out + 1] = "<hr>"
    elseif line:match("^>%s?") then
      close_list() ; close_table()
      out[#out + 1] = "<blockquote><p>" .. line_inline((line:gsub("^>%s?", ""))) .. "</p></blockquote>"
    elseif line:match("^%s*[-*]%s+") then
      close_table()
      if not in_list then out[#out + 1] = "<ul>" ; in_list = "ul" end
      out[#out + 1] = "<li>" .. line_inline((line:gsub("^%s*[-*]%s+", ""))) .. "</li>"
    elseif line:match("^%s*%d+%.%s+") then
      close_table()
      if not in_list then out[#out + 1] = "<ol>" ; in_list = "ol" end
      out[#out + 1] = "<li>" .. line_inline((line:gsub("^%s*%d+%.%s+", ""))) .. "</li>"
    elseif in_list and line:match("^%s%s+%S") then
      -- A continuation line of a list item, indented. Joined to the item above.
      out[#out] = out[#out]:gsub("</li>$", " " .. line_inline((line:gsub("^%s+", ""))) .. "</li>")
    elseif line:match("^|") then
      close_list()
      if line:match("^|[%s|:%-]+|%s*$") and in_table then
        out[#out + 1] = "</thead><tbody>"
      else
        local cells = {}
        for cell in line:gmatch("|([^|]*)") do
          cells[#cells + 1] = cell:match("^%s*(.-)%s*$")
        end
        if cells[#cells] == "" then cells[#cells] = nil end
        local tag = "td"
        if not in_table then
          out[#out + 1] = "<table><thead>"
          in_table = true
          tag = "th"
        end
        local row = {"<tr>"}
        for _, cell in ipairs(cells) do
          -- A cell that is exactly an issue number is a link to the issue, which
          -- is what makes the roadmap and the progress tables navigable.
          local number = cell:match("^(%d%d%d%l?)$")
          if number ~= nil and links.issue[number] ~= nil then
            row[#row + 1] = "<" .. tag .. "><a class='issue-link' href='" ..
              links.issue[number] .. ".html'>" .. number .. "</a></" .. tag .. ">"
          else
            row[#row + 1] = "<" .. tag .. ">" .. line_inline(cell) .. "</" .. tag .. ">"
          end
        end
        row[#row + 1] = "</tr>"
        out[#out + 1] = table.concat(row)
      end
    else
      close_list() ; close_table()
      out[#out + 1] = "<p>" .. line_inline(line) .. "</p>"
    end
  end
  close_list() ; close_table()
  return table.concat(out, "\n")
end
-- }}}

M.render = render

-- {{{ local function list_files()
-- Every file matching a pattern in a directory, sorted. One read-only listing per
-- directory, and nothing else is ever run.
local function list_files(directory, pattern)
  local names = {}
  local pipe = io.popen("ls -1 '" .. directory .. "' 2>/dev/null")
  if pipe == nil then
    return names
  end
  for name in pipe:lines() do
    if name:match(pattern) then
      names[#names + 1] = name
    end
  end
  pipe:close()
  table.sort(names)
  return names
end
-- }}}

-- {{{ local function read_file()
local function read_file(path)
  local handle = io.open(path, "r")
  if handle == nil then return nil end
  local text = handle:read("*a")
  handle:close()
  return text
end
-- }}}

-- {{{ local function status_of_issues()
-- Every issue's status, read off the phase progress tables, so an issue page can
-- wear a badge that agrees with the tracker rather than with itself.
local function status_of_issues(root)
  local status = {}
  for _, name in ipairs(list_files(root .. "/issues", "^phase%-%d%-progress%.md$")) do
    local text = read_file(root .. "/issues/" .. name) or ""
    for number, state in text:gmatch("\n| (%d%d%d%l?) | [^|]* | ([^|]*) |") do
      status[number] = state:match("^%s*(.-)%s*$")
    end
  end
  return status
end
-- }}}

-- {{{ function M.build()
-- Walks every document and writes the site. Returns the count written and where;
-- raises with every unresolved reference if there were any.
function M.build(root)
  local out_dir = root .. "/docs/HTML"
  local report = {}

  local sections = {
    {title = "start here", dir = "notes", pattern = "^[a-z][^.]*$", plain = true},
    {title = "the design", dir = "docs", pattern = "^%d%d%d%-.*%.md$"},
    {title = "the ledgers", dir = "docs", pattern = "^[a-z][%w%-]*%.md$"},
    {title = "issues", dir = "issues", pattern = "^%d%d%d%l?%-.*%.md$"},
    {title = "completed", dir = "issues/completed", pattern = "^%d%d%d%l?%-.*%.md$"},
    {title = "progress", dir = "issues", pattern = "^phase%-%d%-progress%.md$"},
    {title = "the tests", dir = "tests", pattern = "^%d%d%d%-.*%.info%.md$"},
    {title = "the tools", dir = "scripts", pattern = "^%d%d%d%-.*%.info%.md$"},
    {title = "the simulation", dir = "src", pattern = "^%d%d%d%-.*%.info%.md$"},
    {title = "the catalogues", dir = "assets", pattern = "^%d%d%d%-.*%.info%.md$"},
  }

  -- Every page's slug, every issue number, and every source stem, so that a
  -- mention anywhere becomes a link -- and a mention of something that is not
  -- there becomes an error.
  local links = {page = {}, issue = {}, stem = {}}
  local pages = {}
  for _, section in ipairs(sections) do
    local entries = {}
    for _, name in ipairs(list_files(root .. "/" .. section.dir, section.pattern)) do
      local body = read_file(root .. "/" .. section.dir .. "/" .. name)
      if body ~= nil then
        local slug = name:gsub("%.md$", "")
        local title = body:match("^#%s+(.-)\n") or slug
        entries[#entries + 1] = {slug = slug, title = title, body = body,
                                 plain = section.plain, section = section.title}
        links.page[slug] = slug
        local number = name:match("^(%d%d%d%l?)%-")
        if section.dir:match("^issues") and number ~= nil then
          links.issue[number] = slug
        end
        local stem = name:match("^%d%d%d%-(.*)%.info%.md$")
        if stem ~= nil then
          links.stem[stem] = slug
          links.stem[name:gsub("%.info%.md$", "")] = slug
        end
      end
    end
    if #entries > 0 then
      pages[#pages + 1] = {title = section.title, entries = entries}
    end
  end
  -- The README is a page too, linked from the front, and it links into docs/.
  local readme = read_file(root .. "/README.md")
  links.page["README"] = "README"
  local copying = read_file(root .. "/COPYING.md")
  links.page["COPYING"] = "COPYING"

  local status = status_of_issues(root)

  -- The contents rail, identical on every page, with the current one marked.
  local function contents_for(current)
    local out = {"<nav id='contents'>",
      "<h1>supcom-derivative-clone</h1>",
      "<p class='tagline'>a factory war on dunes where nothing is out of range</p>",
      "<input id='filter' placeholder='filter&hellip;' autocomplete='off'>",
      "<a href='index.html'" .. ((current == "index") and " class='here'" or "") ..
        ">the front page</a>",
      "<a href='README.html'" .. ((current == "README") and " class='here'" or "") ..
        ">the game design</a>"}
    for _, section in ipairs(pages) do
      out[#out + 1] = "<section><h2>" .. section.title .. "</h2>"
      for _, entry in ipairs(section.entries) do
        local index = entry.slug:match("^(%d%d%d%l?)")
        -- Strip the leading index and dash from a title, so the rail reads as
        -- names. Not with a character class: Lua patterns are bytes, and a class
        -- holding an em-dash matches one of its three bytes and leaves the rest,
        -- which corrupts the page's UTF-8.
        local label = entry.title:gsub("^%d%d%d%l?%s*", "")
        label = label:gsub("^\226\128\148%s*", "")
        label = label:gsub("^%-%s*", "")
        out[#out + 1] = string.format(
          "<a href='%s.html'%s>%s%s</a>", entry.slug,
          (current == entry.slug) and " class='here'" or "",
          index and ("<span class='index'>" .. index .. "</span>") or "",
          escape(label))
      end
      out[#out + 1] = "</section>"
    end
    out[#out + 1] = "</nav>"
    return table.concat(out, "\n")
  end

  local FILTER_SCRIPT = [[
<script>
// Filtering the contents. There are more than a hundred pages here and scrolling
// a list of a hundred things to find one is not navigation.
var box = document.getElementById('filter');
box.addEventListener('input', function () {
  var want = box.value.toLowerCase();
  var rail = document.getElementById('contents');
  rail.querySelectorAll('section').forEach(function (section) {
    var shown = 0;
    section.querySelectorAll('a').forEach(function (link) {
      var match = link.textContent.toLowerCase().indexOf(want) !== -1;
      link.style.display = match ? '' : 'none';
      if (match) { shown++; }
    });
    section.style.display = shown ? '' : 'none';
  });
});
</script>
]]

  local function write_page(slug, title, body_html)
    local handle = io.open(out_dir .. "/" .. slug .. ".html", "w")
    if handle == nil then
      error("cannot write " .. out_dir .. "/" .. slug .. ".html -- does docs/HTML exist?")
    end
    handle:write("<!doctype html><html lang='en'><head><meta charset='utf-8'>")
    handle:write("<meta name='viewport' content='width=device-width,initial-scale=1'>")
    handle:write("<title>" .. escape(title) .. " -- supcom-derivative-clone</title>")
    handle:write("<style>" .. M.PALETTE .. M.STYLE .. "</style></head><body>")
    handle:write("<div id='shell'>")
    handle:write(contents_for(slug))
    handle:write("<main id='page'>")
    handle:write(body_html)
    handle:write("<footer>Generated from the Markdown by <code>" ..
      "017-the-documentation-becomes-html.lua</code>. The Markdown is the data; " ..
      "this is a view of it. Do not edit these pages -- edit the documents and " ..
      "run <code>./build-documentation</code>.</footer>")
    handle:write("</main></div>" .. FILTER_SCRIPT .. "</body></html>")
    handle:close()
  end

  local written = 0
  for _, section in ipairs(pages) do
    for _, entry in ipairs(section.entries) do
      local html
      if entry.plain then
        -- notes/ holds the vision, which is prose rather than Markdown and whose
        -- line breaks are the author's. It is shown as written.
        html = "<h1>" .. escape(entry.slug) .. "</h1><pre><code>" ..
               escape(entry.body) .. "</code></pre>"
      else
        html = render(entry.body, links, report, entry.slug)
        -- An issue wears its tracker status as a badge on its heading.
        local number = entry.slug:match("^(%d%d%d%l?)%-")
        if number ~= nil and status[number] ~= nil and entry.section ~= "the design" then
          local state = status[number]
          local class = state:match("built") and "built"
                        or (state:match("progress") or state:match("part")) and "part" or "none"
          html = html:gsub("</h1>", " <span class='badge " .. class .. "'>" ..
                           escape(state) .. "</span></h1>", 1)
        end
      end
      write_page(entry.slug, entry.title, html)
      written = written + 1
    end
  end

  if readme ~= nil then
    write_page("README", "The game design", render(readme, links, report, "README"))
    written = written + 1
  end
  if copying ~= nil then
    write_page("COPYING", "Copying", render(copying, links, report, "COPYING"))
    written = written + 1
  end

  -- The front page: the two changes, one toy, and where to start.
  local front = {}
  front[#front + 1] = "<h1>supcom-derivative-clone</h1>"
  front[#front + 1] = "<p>Take a large-scale real-time strategy game and change two things. " ..
    "<strong>Nothing is out of range</strong> -- a gun fires at anything it can see, and " ..
    "what it can see is decided by the dunes between them. And <strong>units stop " ..
    "listening once they leave the factory</strong> -- a player lays a production line, " ..
    "draws its route in the sand once, and watches.</p>"
  front[#front + 1] = "<h2>The ground</h2>"
  front[#front + 1] = TOYS.sightline
  front[#front + 1] = "<h2>Where to start</h2>"
  front[#front + 1] = "<ul>" ..
    "<li><a href='vision.html'>The vision</a> -- where all of this came from, in the " ..
    "author's own words.</li>" ..
    "<li><a href='README.html'>The game design</a> -- the whole design on one page, " ..
    "and nothing about how it is built.</li>" ..
    "<li><a href='001-what-this-game-is.html'>What this game is</a> -- the two changes, " ..
    "everything that follows from them, and the vocabulary.</li>" ..
    "<li><a href='015-roadmap.html'>The roadmap</a> -- nine phases, which are clusters " ..
    "of functionality rather than a schedule.</li>" ..
    "<li><a href='016-open-questions.html'>Open questions</a> -- every unresolved " ..
    "decision, with its working ruling marked as one.</li>" ..
    "<li><a href='014-the-tests-come-first.html'>The tests come first</a> -- the " ..
    "contract between the tests and the source that does not exist yet.</li>" ..
    "</ul>"
  front[#front + 1] = "<h2>Everything else</h2>"
  front[#front + 1] = "<p>Down the left. Every page here is reachable from every " ..
    "other, every issue number is a link, and the filter at the top of the rail " ..
    "searches all of it.</p>"

  write_page("index", "supcom-derivative-clone", table.concat(front, "\n"))
  written = written + 1

  if #report > 0 then
    table.sort(report)
    error("the documentation has " .. #report .. " unresolved reference(s):\n  " ..
          table.concat(report, "\n  "))
  end

  return written, out_dir
end
-- }}}

-- {{{ the command line
-- Run as a program: --dir names the project root. Loaded as a module (no --dir),
-- it only exports.
local arguments = {...}
for index = 1, #arguments do
  if arguments[index] == "--dir" then
    local root = arguments[index + 1]
    if root == nil then
      io.stderr:write("--dir needs a path\n")
      os.exit(1)
    end
    local ok, written, where = pcall(M.build, root)
    if not ok then
      io.stderr:write(tostring(written), "\n")
      os.exit(1)
    end
    print(string.format("%d pages written to %s", written, where))
    print("open " .. where .. "/index.html")
    os.exit(0)
  end
end
-- }}}

return M
