-- 096-symbol-sweep.lua
--
-- Writes one companion page per blueprint, from the blueprint's own
-- declarations and the ledger's reverse index. Nobody edits these; they are
-- rebuilt, and the header of each one says so.
--
-- For a general reader: the project's rule is that a thing is written once. A
-- page describing a blueprint's interface, written by hand, would be the same
-- information twice, and the second copy is always the one that goes stale. So
-- this generates them. What a companion page adds that the blueprint does not
-- already say is the direction nobody can see from inside one file: what
-- consumes this. Change a number here and that list is what breaks.

local DIR = "/mnt/mtwo/programming/ai-stuff/six-sided-dice-layer-cake"
if arg and arg[1] then DIR = arg[1] end

local units      = dofile(DIR .. "/src/091-units.lua")
local expression = dofile(DIR .. "/src/092-expression.lua")
local ledger     = dofile(DIR .. "/src/094-ledger.lua")

local M = {}

-- {{{ local function shown()
-- A resolved value in the unit its author declared it in. An unresolved one --
-- because it reaches into a blueprint nobody has written yet -- says so rather
-- than printing nothing, because a blank in a table reads as zero.
local function shown(L, name)
  local q = L.value[name]
  if not q then return "unresolved" end
  local d = L.decl[name]
  local ok, s = pcall(units.format, q, d.unit, 6)
  if ok then return s end
  return units.format(q)
end
-- }}}

-- {{{ local function sorted_copy()
local function sorted_copy(t)
  local out = {}
  for i = 1, #t do out[i] = t[i] end
  table.sort(out)
  return out
end
-- }}}

-- {{{ local function consumes()
-- Every symbol this blueprint's derivations and constraints reach for, that it
-- did not declare itself, with the blueprint that owns each. This is the answer
-- to the question a reader most often has: what do I have to understand before
-- this file makes sense?
local function consumes(L, bp)
  local mine, want, seen = {}, {}, {}
  for _, s in ipairs(bp.symbols) do mine[s.name] = true end
  local function add(n)
    if mine[n] or seen[n] then return end
    seen[n] = true
    want[#want + 1] = n
  end
  for _, s in ipairs(bp.symbols) do
    if s.tree then
      for _, n in ipairs(expression.refs(s.tree)) do add(n) end
    end
  end
  for _, c in ipairs(bp.constraints) do
    if c.rel then
      for _, n in ipairs(expression.refs(c.rel.lhs)) do add(n) end
      for _, n in ipairs(expression.refs(c.rel.rhs)) do add(n) end
    end
  end
  table.sort(want)
  return want
end
-- }}}

-- {{{ local function page()
local function page(L, bp)
  local out = {}
  local function w(fmt, ...)
    out[#out + 1] = select("#", ...) > 0 and fmt:format(...) or fmt
  end

  w("# %s-%s — info", bp.number, (bp.file:gsub("^%d+%a?%-", ""):gsub("%.md$", "")))
  w("")
  w("*Generated by `096` from the declarations in `%s`. Do not edit this page;", bp.file)
  w("edit the blueprint and run the sweep again.*")
  w("")
  w("**%s** — phase %d.", bp.title, bp.phase)
  if bp.issues and #bp.issues > 0 then
    w("Described by %s.", "`" .. table.concat(bp.issues, "`, `") .. "`")
  end
  w("")

  -- what it publishes
  w("## What it publishes")
  w("")
  if #bp.symbols == 0 then
    w("Nothing. This blueprint declares no symbols of its own, which is unusual")
    w("and is either deliberate — a view over other people's numbers — or a")
    w("blueprint that has not been written yet.")
  else
    w("| symbol | unit | kind | value | meaning |")
    w("|---|---|---|---|---|")
    for _, s in ipairs(bp.symbols) do
      w("| `%s` | %s | %s | %s | %s |",
        s.name, s.unit, s.kind, shown(L, s.name), s.meaning)
    end
  end
  w("")

  -- what it consumes
  local want = consumes(L, bp)
  w("## What it consumes")
  w("")
  if #want == 0 then
    w("Nothing. Every number in this blueprint is chosen or measured here.")
  else
    w("| symbol | from | value | meaning |")
    w("|---|---|---|---|")
    for _, n in ipairs(want) do
      local d = L.decl[n]
      if d then
        w("| `%s` | `%s` | %s | %s |", n, d.blueprint.number, shown(L, n), d.meaning)
      else
        w("| `%s` | **nothing declares this** | — | — |", n)
      end
    end
  end
  w("")

  -- who consumes it
  w("## What consumes it")
  w("")
  local any = false
  local lines = {}
  for _, s in ipairs(bp.symbols) do
    local u = sorted_copy(L.used_by[s.name] or {})
    if #u > 0 then
      any = true
      lines[#lines + 1] = ("| `%s` | %s |"):format(s.name, "`" .. table.concat(u, "`, `") .. "`")
    end
  end
  if any then
    w("Change one of these and the blueprints beside it are what break.")
    w("")
    w("| symbol | read by |")
    w("|---|---|")
    for _, l in ipairs(lines) do w(l) end
  else
    w("Nothing yet reads anything this blueprint publishes.")
  end
  w("")

  -- constraints
  w("## What it asserts")
  w("")
  if #bp.constraints == 0 then
    w("Nothing. This blueprint publishes numbers and checks none of them.")
  else
    w("| tag | relation | because |")
    w("|---|---|---|")
    for _, c in ipairs(bp.constraints) do
      w("| `%s` | `%s` | %s |", c.tag, c.relation, c.reason)
    end
  end
  w("")

  if #bp.drawings > 0 then
    w("## What it draws")
    w("")
    for _, d in ipairs(bp.drawings) do
      local names = {}
      for _, r in ipairs(d.refs) do names[#names + 1] = "`" .. r.name .. "`" end
      w("- **%s** — %s", d.caption,
        #names > 0 and ("dimensions " .. table.concat(names, ", ")) or "no dimensions called out")
    end
    w("")
  end

  return table.concat(out, "\n") .. "\n"
end
-- }}}

-- {{{ function M.run()
-- Rewrite the companion page beside every blueprint, and report which
-- blueprints are thin.
--
-- Pass `dry` in the options to work out everything and write nothing, which is
-- how to see what a change would do to two hundred pages before doing it.
function M.run(dir, opts)
  dir = dir or DIR
  opts = opts or {}
  local L = ledger.load(dir)
  local written, thin = {}, {}

  for _, bp in ipairs(L.blueprints) do
    local path = dir .. "/src/" .. bp.file:gsub("%.md$", ".info.md")
    local body = page(L, bp)
    if not opts.dry then
      local fh = assert(io.open(path, "w"))
      fh:write(body)
      fh:close()
    end
    written[#written + 1] = path

    -- Four ways for a blueprint to be thin, reported together so that
    -- thinness is visible here rather than discovered by whoever tries to
    -- build from it.
    local reasons = {}
    if #bp.symbols == 0 then reasons[#reasons + 1] = "declares nothing" end
    if #bp.constraints == 0 then reasons[#reasons + 1] = "asserts nothing" end
    if #bp.drawings == 0 then reasons[#reasons + 1] = "draws nothing" end
    local unread = 0
    for _, s in ipairs(bp.symbols) do
      if #(L.used_by[s.name] or {}) == 0 then unread = unread + 1 end
    end
    if #bp.symbols > 0 and unread == #bp.symbols then
      reasons[#reasons + 1] = "nothing reads it"
    end
    if #reasons > 0 then
      thin[#thin + 1] = { bp = bp, why = table.concat(reasons, ", ") }
    end
  end

  return { ledger = L, written = written, thin = thin, dry = opts.dry }
end
-- }}}

-- {{{ function M.report()
-- The coverage report: how many pages were written, and the four ways a
-- blueprint can be thin -- declaring nothing, asserting nothing, drawing
-- nothing, or publishing only symbols nothing reads.
function M.report(R, out)
  out = out or io.stdout
  local function say(fmt, ...)
    out:write(select("#", ...) > 0 and fmt:format(...) or fmt, "\n")
  end
  say("")
  say("  companion pages: %d %s", #R.written, R.dry and "would be written" or "written")
  if #R.thin > 0 then
    say("")
    say("  COVERAGE -- blueprints that are thin, and how")
    for _, t in ipairs(R.thin) do
      say("    %-4s %-38s %s", t.bp.number, t.bp.title, t.why)
    end
  end
  say("")
  return 0
end
-- }}}

if arg and arg[0] and arg[0]:match("096%-symbol%-sweep%.lua$") then
  local dry = false
  for i = 1, 8 do if arg[i] == "--dry" then dry = true end end
  os.exit(M.report(M.run(DIR, { dry = dry })))
end

return M
