-- 097-spec-report.lua
--
-- Produces the three documents whose content is entirely derived: the
-- specification sheet, the bill of materials, and a full listing of every
-- number in the machine with its name, its unit, its derivation and its reason.
--
-- For a general reader: the first two are for other people and the third is for
-- whoever is working on the design. The third is the one with nothing else like
-- it -- over a thousand quantities, each with the expression that produced it
-- and the sentence saying what it is, which is what the whole notation was for.
--
-- Nothing here invents a number. A template names symbols and the generator
-- substitutes; a name that does not resolve is an error and not a blank,
-- because the failure mode of a summary document is a figure that appears only
-- in it.

local DIR = "/mnt/mtwo/programming/ai-stuff/six-sided-dice-layer-cake"
if arg and arg[1] then DIR = arg[1] end

local units  = dofile(DIR .. "/src/091-units.lua")
local ledger = dofile(DIR .. "/src/094-ledger.lua")

local M = {}

-- {{{ local function shown()
-- A resolved value in a named unit, or in the unit its author declared it in.
-- A quantity printed in base units is correct and unreadable: a cube reported as
-- 0.06 m when every drawing says millimetres helps nobody.
local function shown(L, name, unit, digits)
  local q = L.value[name]
  if not q then return nil, ("%s does not resolve"):format(name) end
  local d = L.decl[name]
  local ok, s = pcall(units.format, q, unit or d.unit, digits or 4)
  if not ok then
    return nil, ("%s cannot be expressed in %s"):format(name, unit or d.unit)
  end
  return s
end
-- }}}

-- {{{ local function render()
-- Substitute {name} and {name:unit} in a template. An unresolved name raises
-- rather than leaving a gap, which is 089's C-089-1 enforced by the generator
-- that fills it.
local function render(L, text, problems)
  return (text:gsub("{([%w_]+):?([%w_%^%*/%(%)%-]*)}", function(name, unit)
    local s, err = shown(L, name, unit ~= "" and unit or nil)
    if not s then
      problems[#problems + 1] = err
      return "<<" .. name .. ">>"
    end
    return s
  end))
end
-- }}}

-- The specification sheet. One page, and every figure in braces is a symbol
-- name that has to resolve.
local SHEET = [[
# Specification

*Generated by `097` from the blueprint set. Every figure resolves to a symbol
declared in `src/`; nothing here is entered by hand. Regenerate rather than edit.*

**All figures are for the reference model in `078` at its reference context and
batch.** `078` has the surface of what else fits; `080` has the sensitivity.

## Physical

| | |
|---|---|
| edge | {L_cube:mm} |
| volume | {V_cube:cm^3} |
| mass, wet | {m_cube:kg} |
| mounting | four points on one face's corner blocks (`019`) |

## Power and cooling

| | |
|---|---|
| input | {V_supply:V} at {I_supply:A} |
| dissipation, design point | {P_heat:W} |
| dissipation, idle with a model resident | {P_idle:W} |
| coolant | water, {Q_total:L/min} at {dp_system:bar} |
| inlet | {T_coolant_in:K} |
| junction, hottest point, worst-served face | {T_j_peak:K} |
| margin to the silicon's limit | {margin_thermal:K} |

## Memory and compute

| | |
|---|---|
| usable capacity | {C_core_usable:GB} |
| aggregate read bandwidth | {B_core:TB/s} |
| arithmetic, eight-bit | {ops_machine:Tflop/s} |
| storage lines | five populated, {B_feed:TB/s} aggregate |
| model load | {t_load_relay:ms} |

## Output

| | |
|---|---|
| pane | {C_pane_mb:MB}, {n_pane_bit:bit} conductors |
| whole core, bonded grade | {t_core_out:us} |
| against a fast network interface | {ratio_net:1} times |

## Performance

| | |
|---|---|
| tokens a second, one sequence | {tok_s_single:1/s} |
| tokens a second, aggregate at the design batch | {tok_s_agg:1/s} |
| prompt tokens a second | {tok_s_prefill:1/s} |
| largest model resident | {C_weights:GB} of weights |
| memory bandwidth against an accelerator with stacked memory | {gain_bw:1} times |
| capacity against the same | {gain_cap:1} times |

**Past the capacity figure the machine refuses rather than degrading** (`059`).
A shorter context is offered instead; streaming is not.

## Life

| | |
|---|---|
| target | {n_yr_target:1} years, continuous |
| implied annual replacement rate | {f_repl_annual:1} |

## What this is not

No operating system. No memory protection and no privilege levels. Not a
general-purpose processor — the instruction set in `043` is what a matrix engine
needs to be fed and nothing more. No training beyond low-rank adaptation
(`076a`). Capacity is unremarkable next to the bandwidth; the bandwidth is the
point. **No field-serviceable parts**: service means replacing the cube (`019`).
]]

local BOM = [[
# Bill of materials

*Generated by `097`. Every quantity is derived from a geometry and a density or a
count; the cost figures are relative units so that ratios mean something and
prices do not.*

## Inside the cube

| | count | note |
|---|---|---|
| compute dies | {n_die:1} | {A_die:mm^2} each, logic node |
| memory tiers | {n_tier:1} | {A_core_side:mm^2} each, array node |
| cooling laminae | {n_tier:1} | copper–molybdenum |
| face cold plates | {n_face:1} | silicon, {n_uchan:1} channels each |
| face interposers | {n_face:1} | glass core |
| edge rails | {n_edge:1} | stainless |
| corner blocks | {n_corner:1} | four ported, four blank |
| bonds | {n_bond_cube:1} | the reason the spares exist |

## Silicon, by node

| | |
|---|---|
| logic | {A_si_logic:mm^2} |
| array | {A_si_array:mm^2} |
| passive | {A_si_passive:mm^2} |
| total | {A_si_total:mm^2} |
| by mass | {m_si_cube:kg} of {m_cube:kg} |

## The loop, and consumables

{n_part_loop:1} components outside the cube. {n_consumable:1} consumables, at
{V_consume_yr:mm^3} of fluid a year against a {V_reservoir:mm^3} reservoir.

## Where the cost is

| | |
|---|---|
| silicon, at known-good prices | {f_cost_si:1} |
| yield | {f_cost_yield:1} |
| assembly | {f_cost_assy:1} |

**Memory tiers are two thirds of the silicon bill** — a tier is large enough that
only {y_die_tier:1} of them come off a wafer good. Assembly yield is
{y_cube:1}, which is better than the bare arithmetic threatens because of the
four mitigations in `083`.

**Making the tiers smaller would save more than any assembly improvement**, and
nothing in the design has been asked whether a tier has to be one piece.

*No price is given. There is no volume, no supplier and no year, so a number
would be fiction. What survives is the structure.*
]]

-- {{{ local function full_listing()
-- Every number in the machine, with what produced it and what it is for. The
-- document this project's notation exists to make possible.
local function full_listing(L)
  local out = {}
  local function w(fmt, ...)
    out[#out + 1] = select("#", ...) > 0 and fmt:format(...) or fmt
  end
  w("# Every number in the machine")
  w("")
  w("*Generated by `097`. One row per symbol: what it is called, what it is")
  w("measured in, where it came from, what it comes to, and why it exists.*")
  w("")

  -- grouped by the blueprint that declares them, in blueprint order
  local by_bp, order = {}, {}
  for _, name in ipairs(L.order) do
    local d = L.decl[name]
    local k = d.blueprint.number
    if not by_bp[k] then by_bp[k] = { bp = d.blueprint, rows = {} }; order[#order + 1] = k end
    by_bp[k].rows[#by_bp[k].rows + 1] = d
  end
  table.sort(order)

  for _, k in ipairs(order) do
    local g = by_bp[k]
    w("## %s — %s", g.bp.number, g.bp.title)
    w("")
    w("| symbol | unit | kind | value | from | meaning |")
    w("|---|---|---|---|---|---|")
    for _, d in ipairs(g.rows) do
      local v = shown(L, d.name) or "unresolved"
      local from = (d.kind == "derived") and ("`" .. d.expr .. "`") or "—"
      w("| `%s` | %s | %s | %s | %s | %s |",
        d.name, d.unit, d.kind, v, from, d.meaning)
    end
    w("")
  end
  return table.concat(out, "\n") .. "\n"
end
-- }}}

-- {{{ function M.run()
function M.run(dir, opts)
  dir = dir or DIR
  opts = opts or {}
  local L = ledger.load(dir)
  local problems = {}

  local docs = {
    { path = dir .. "/docs/089-specification.md", body = render(L, SHEET, problems) },
    { path = dir .. "/docs/088-bill-of-materials.md", body = render(L, BOM, problems) },
    { path = dir .. "/docs/101-every-number.md", body = full_listing(L) },
  }
  if not opts.dry then
    for _, d in ipairs(docs) do
      local fh = assert(io.open(d.path, "w"))
      fh:write(d.body)
      fh:close()
    end
  end
  return { ledger = L, docs = docs, problems = problems, dry = opts.dry }
end
-- }}}

-- {{{ function M.report()
function M.report(R, out)
  out = out or io.stdout
  local function say(fmt, ...)
    out:write(select("#", ...) > 0 and fmt:format(...) or fmt, "\n")
  end
  say("")
  for _, d in ipairs(R.docs) do
    say("  %s  %s", R.dry and "would write" or "wrote      ", d.path:match("[^/]+$"))
  end
  if #R.problems > 0 then
    say("")
    say("  TEMPLATE -- names that did not resolve")
    say("  (a figure on a generated sheet must exist as a symbol somewhere;")
    say("  a blank here is a number that would appear only on the sheet)")
    for _, p in ipairs(R.problems) do say("    %s", p) end
    say("")
    return 1
  end
  say("")
  return 0
end
-- }}}

if arg and arg[0] and arg[0]:match("097%-spec%-report%.lua$") then
  local dry = false
  for i = 1, 8 do if arg[i] == "--dry" then dry = true end end
  os.exit(M.report(M.run(DIR, { dry = dry })))
end

return M
