#!/bin/bash
# =============================================================================
# init-project.sh - start a new project, and give it a workspace it can't
#                   escape from.
# =============================================================================
#
# WHAT THIS IS, IN PLAIN TERMS
#
# This builds two things.
#
# The first is an ordinary project folder on disk, with the standard
# documentation skeleton already laid out - docs, notes, issues, and the rest.
# Nothing clever. It sits in the monorepo like every other project.
#
# The second is a sandbox: a copy of that folder living in RAM, which an AI
# agent gets turned loose inside. The containment here is real, not a
# convention. It uses a Linux mount namespace to hand the agent a private view
# of the filesystem, assembled from scratch, in which the SSH keys, the other
# sixty-odd projects, and the rest of the home directory do not exist. Not
# "permission denied" - absent, the way a room you never built has no door.
# Anything the agent wrecks in there is discarded by rebooting the machine.
#
# The point of all this is to make `--dangerously-skip-permissions` an ordinary
# thing to type rather than a gamble.
#
# WHAT IT DELIBERATELY DOES NOT DO
#
# It does not contain the network. The agent has to reach the Anthropic API in
# order to think at all, so the wire stays open, and an agent that wants to
# send your source code somewhere still can. This walls off the disk. Treat the
# network as unguarded, because it is.
#
# It also does not, yet, carry work back out of the sandbox on commit. That
# half depends on an unsettled question about how the monorepo's branches
# should be arranged, and is marked below as a seam rather than guessed at.
# Until then the sandbox is a one-way copy and RAM is volatile, which is the
# single most important thing the generated CLAUDE.md tells the agent.
#
# USAGE
#
#   init-project.sh <name>                    create a project and its sandbox
#   init-project.sh --refresh <name>          rebuild the sandbox for a project
#   init-project.sh --writable <path> <name>  bind an ignored path read-write
#   init-project.sh --dir <path> <name>       operate on a different monorepo
#   init-project.sh --help
#
# Running it twice is safe. Running it twice is, in fact, how you use it: it
# reconciles whatever is on disk with whatever it expects to find, and only
# refuses when reconciling would destroy work it can see.
# =============================================================================

set -o errexit
set -o nounset
set -o pipefail

# --- Configuration -----------------------------------------------------------
# DIR is the monorepo root. Everything else in this script is expressed
# relative to it, so the script may be invoked from anywhere, and pointed at a
# different tree with --dir for testing without touching the real one.
DIR="/mnt/mtwo/programming/ai-stuff"

# Where sandboxes are staged. Deliberately NOT /tmp/<project>/, because that
# path already means something else in this repo's conventions (the per-project
# RAM scratch tier). Colliding with it would make two unrelated ideas share a
# name, and the confusion would be permanent.
SANDBOX_ROOT="/tmp/claude-sandbox"

# The agent binary and its home-directory state. These live on the same disk as
# $HOME because /home/ritz is a symlink to /mnt/mtwo - see the note in
# compose_bwrap_arguments() for why that fact drives the entire mount layout.
AGENT_HOME="/mnt/mtwo"
AGENT_BINARY_DIR="${AGENT_HOME}/programs/claude-code"

# Ignored paths that are never bound into the sandbox, whatever .gitignore
# says about them. Binding these would either defeat the sandbox (.git) or be
# pointless (tmp/ is already scratch space, and the sandbox deserves its own).
declare -a NEVER_BIND=(".git/" "tmp/" ".claude/")

# Marker pair delimiting the generated section of a project's CLAUDE.md.
# Regeneration replaces what lies between them and leaves everything else
# alone, so a human's own notes in that file survive re-runs.
NOTICE_BEGIN="<!-- BEGIN SANDBOX NOTICE - generated by init-project.sh -->"
NOTICE_END="<!-- END SANDBOX NOTICE -->"

# --- Runtime state -----------------------------------------------------------
PROJECT_NAME=""
PROJECT_PATH=""
SANDBOX_PATH=""
SANDBOX_PROJECT_PATH=""
OBJECT_LINK_PATH=""
REFRESH_ONLY="no"
UNSAVED_WORK=""

# The branch the sandbox works on. Defaults to the trunk, because a sandbox is
# an execution environment rather than a maturity level: work done inside it is
# ordinary work, and it belongs on the branch it would have belonged on anyway.
# Branch when you actually want to experiment, the same as you would outside.
SANDBOX_BRANCH="master"
declare -a WRITABLE_PATHS=()
declare -a IGNORED_PATHS=()

# Where this script actually is, resolved through any symlinks. The generated
# launcher needs to call back here to rebuild the sandbox after a reboot, and
# guessing the location from DIR would be wrong the moment anyone runs the
# script from somewhere other than the monorepo it is pointed at.
SELF_PATH="$(readlink -f "${BASH_SOURCE[0]}")"

# {{{ print_usage()
print_usage() {
    cat <<'USAGE'
init-project.sh - create a project and a sandbox it cannot escape

  init-project.sh <name>
      Create ai-stuff/<name> with the standard skeleton, then provision a
      RAM-backed sandbox for it and write a launcher.

  init-project.sh --refresh <name>
      Leave the project alone; rebuild the sandbox and launcher from current
      disk state. Refuses if the existing sandbox holds work not on disk.

  init-project.sh --writable <path> ... <name>
      Bind an ignored path read-write instead of read-only. Repeatable. The
      path is relative to the project root. Use sparingly: every writable bind
      is a hole in the wall, and a write through it reaches the real disk.

  init-project.sh --dir <path> <name>
      Operate against a different monorepo root. For testing.

  init-project.sh --help

After it runs, enter the sandbox with:
      <project>/scripts/enter-sandbox.sh

Work inside the sandbox lives in RAM and does not survive a reboot.
USAGE
}
# }}}

# {{{ fail()
# Every failure path in this script funnels through here. The repo's standing
# rule is that a broken thing should say so and stop, rather than quietly doing
# something approximate - so there are no fallbacks below this line, only exits.
fail() {
    printf 'init-project: %s\n' "$1" >&2
    exit 1
}
# }}}

# {{{ require_tools()
# Checked up front rather than discovered halfway through provisioning, because
# a half-built sandbox is worse than no sandbox: it looks ready and isn't.
require_tools() {
    local tool
    for tool in bwrap git rsync; do
        command -v "$tool" >/dev/null 2>&1 \
            || fail "required tool not found: ${tool}"
    done

    # Unprivileged user namespaces are what let bwrap build a mount namespace
    # without root. If the kernel has them switched off, the containment this
    # script promises is simply unavailable, and pretending otherwise would be
    # the most dangerous thing it could do.
    local namespace_limit
    namespace_limit=$(sysctl -n user.max_user_namespaces 2>/dev/null || echo 0)
    if [ "${namespace_limit}" -lt 1 ]; then
        fail "unprivileged user namespaces are disabled; bwrap cannot isolate anything"
    fi
}
# }}}

# {{{ parse_arguments()
parse_arguments() {
    while [ $# -gt 0 ]; do
        case "$1" in
            --help|-h)
                print_usage
                exit 0
                ;;
            --branch)
                [ $# -ge 2 ] || fail "--branch needs a branch name"
                SANDBOX_BRANCH="$2"
                shift 2
                ;;
            --refresh)
                # Refresh means "the project exists and is fine; rebuild only
                # the disposable half". Distinguishing this from creation keeps
                # skeleton-writing out of the hot path you run every day.
                REFRESH_ONLY="yes"
                shift
                ;;
            --writable)
                [ $# -ge 2 ] || fail "--writable needs a path"
                WRITABLE_PATHS+=("$2")
                shift 2
                ;;
            --dir)
                [ $# -ge 2 ] || fail "--dir needs a path"
                DIR="$2"
                shift 2
                ;;
            -*)
                fail "unknown option: $1"
                ;;
            *)
                [ -z "${PROJECT_NAME}" ] || fail "more than one project name given: ${PROJECT_NAME}, $1"
                PROJECT_NAME="$1"
                shift
                ;;
        esac
    done

    [ -n "${PROJECT_NAME}" ] || { print_usage; exit 1; }

    # A project name has to be a single path component. Anything with a slash
    # or a leading dot would either escape the monorepo root or hide itself,
    # and both of those are bugs wearing a name's clothing.
    case "${PROJECT_NAME}" in
        */*|.*) fail "project name must be a plain directory name: ${PROJECT_NAME}" ;;
    esac

    [ -d "${DIR}" ] || fail "monorepo root does not exist: ${DIR}"

    PROJECT_PATH="${DIR}/${PROJECT_NAME}"
    SANDBOX_PATH="${SANDBOX_ROOT}/${PROJECT_NAME}"
    SANDBOX_PROJECT_PATH="${SANDBOX_PATH}/${PROJECT_NAME}"

    # Where the borrowed object store is reached from, and this is subtle
    # enough to be worth spelling out.
    #
    # The sandbox repository borrows the real object store through an
    # `alternates` file holding an absolute path. Inside the namespace the
    # sandbox is mounted *at* the monorepo's own path, so the obvious path -
    # <monorepo>/.git/objects - would resolve to the sandbox's own tiny store
    # rather than the real one, and the borrowing would quietly become
    # self-referential. The alternate therefore has to live somewhere the
    # sandbox mount does not cover.
    #
    # It also has to resolve identically outside the namespace, because the
    # carry-back runs on the host and reads this repository. So: a symlink on
    # the host, a read-only bind mount at the same path inside. One path, valid
    # in both worlds, pointing at the same objects either way.
    OBJECT_LINK_PATH="${AGENT_HOME}/.sandbox-objects/$(basename "${DIR}")"
}
# }}}

# {{{ create_project_skeleton()
# The standard folder set. mkdir -p throughout, so an existing project gains
# any directories it is missing and loses nothing it already has - which is
# what makes re-running this safe on a project that has been worked in.
create_project_skeleton() {
    local target="$1"

    local subdirectory
    for subdirectory in docs notes src libs assets issues issues/completed scripts; do
        mkdir -p "${target}/${subdirectory}"
    done

    # The intent directories from the repo's conventions. They are meant to be
    # written to casually and read from at random, so they exist from birth
    # rather than being created the first time someone remembers them.
    for subdirectory in input output desire faith strategems; do
        mkdir -p "${target}/${subdirectory}"
    done

    if [ ! -f "${target}/docs/table-of-contents.md" ]; then
        cat > "${target}/docs/table-of-contents.md" <<EOF
# ${PROJECT_NAME} - Table of Contents

Every document in docs/ and notes/ belongs somewhere in this tree. Source code
and issue files do not; they have their own indexes.

## Vision
- notes/vision - the founding description. Written first, read most.

## Documentation
- docs/table-of-contents.md - this file.

## Phases
Phases group related functionality, not calendar time. It is normal for the
last issue completed in a project to belong to phase 1.
EOF
    fi
}
# }}}

# {{{ link_ram_directories()
# The two-tier scratch convention: /tmp/<name>/tmp for things that get executed,
# /dev/shm/<name> for things that get written and read but never run. The
# project reaches both through a single tmp/ symlink in its root, so nothing in
# the project ever has to name an absolute path outside itself.
link_ram_directories() {
    local exec_tier="/tmp/${PROJECT_NAME}"
    local artifact_tier="/dev/shm/${PROJECT_NAME}"

    mkdir -p "${exec_tier}/tmp"
    mkdir -p "${artifact_tier}"

    # ln -sfn rather than plain ln -s: without -n, pointing a symlink at a
    # directory that already exists as a symlink creates a link *inside* it,
    # and you end up with tmp/tmp/tmp after enough re-runs.
    ln -sfn "${exec_tier}" "${PROJECT_PATH}/tmp"
    ln -sfn "${artifact_tier}" "${exec_tier}/shared-memory"
}
# }}}

# {{{ write_project_gitignore()
# Only ever adds lines, and only ones that are missing. A .gitignore is a file
# people edit by hand, so rewriting it wholesale would throw away decisions
# somebody made on purpose.
write_project_gitignore() {
    local gitignore="$1/.gitignore"

    # Created only when absent, never touched when present. An unconditional
    # `touch` here bumped the modification time on every run, which the
    # unsaved-work check downstream then read as a genuine difference between
    # disk and sandbox - so the script refused to refresh a project it had
    # itself just marked as changed.
    if [ ! -f "${gitignore}" ]; then
        : > "${gitignore}"
    fi

    local -a wanted=(
        "tmp"
        "scripts/enter-sandbox.sh"
    )

    local entry
    for entry in "${wanted[@]}"; do
        if ! grep -Fxq "${entry}" "${gitignore}"; then
            printf '%s\n' "${entry}" >> "${gitignore}"
        fi
    done
}
# }}}

# {{{ collect_ignored_paths()
# Asks git which paths are ignored, rather than parsing .gitignore.
#
# This matters more than it looks. The monorepo's ignore file is 270 lines of
# patterns with negations, and each project layers its own on top. Git's
# matcher implements all of that - precedence, negation, directory-only
# patterns, the lot - and any hand-rolled version would agree with it right
# up until the day it didn't, silently, on a path that mattered.
#
#   --others          only untracked files (tracked files are ours by definition)
#   --ignored         only the ones an ignore rule matched
#   --exclude-standard  honour .gitignore, .git/info/exclude, and core.excludesFile
#   --directory       collapse a fully-ignored directory to one entry, so a
#                     4GB cache folder is one bind rather than 40,000 of them
collect_ignored_paths() {
    IGNORED_PATHS=()

    # A project directory that git doesn't know about yet has nothing ignored
    # in it, and asking would just produce an error about being outside a
    # repository. Not a failure - simply a project with no escapes.
    git -C "${PROJECT_PATH}" rev-parse --git-dir >/dev/null 2>&1 || return 0

    local -a raw=()
    local -a collapsed=()
    mapfile -t collapsed < <(git -C "${PROJECT_PATH}" ls-files \
        --others --ignored --exclude-standard --directory)

    # Re-expand directories that were collapsed by accident rather than by rule.
    #
    # `--directory` folds a directory into a single entry whenever every
    # untracked file inside it happens to be ignored. That looks identical in
    # the output to a directory an ignore rule genuinely names, but it means
    # something entirely different: `node_modules/` is ignored because a rule
    # says so, whereas `scripts/` collapsed only because the one untracked file
    # in it - the generated launcher - is ignored. Binding the second kind
    # wholesale would mount a live source directory read-only and make the
    # project unwritable in the place work actually happens.
    #
    # `git check-ignore` answers which kind we have: it matches a path against
    # the rules directly, so it succeeds for the first kind and fails for the
    # second. Where it fails, we descend and take the individual files instead.
    local entry
    for entry in ${collapsed[@]+"${collapsed[@]}"}; do
        if [ "${entry}" = "${entry%/}" ]; then
            raw+=("${entry}")
        elif git -C "${PROJECT_PATH}" check-ignore -q "${entry}"; then
            raw+=("${entry}")
        else
            local -a expanded=()
            mapfile -t expanded < <(git -C "${PROJECT_PATH}" ls-files \
                --others --ignored --exclude-standard -- "${entry}")
            raw+=(${expanded[@]+"${expanded[@]}"})
        fi
    done

    local candidate skip parent
    for candidate in "${raw[@]}"; do
        [ -n "${candidate}" ] || continue

        skip="no"

        # Drop anything on the never-bind list. These are either the sandbox's
        # own escape hatch (.git) or scratch space the sandbox should own a
        # private copy of (tmp, .claude).
        #
        # Both sides are stripped of trailing slashes before comparing, because
        # git only appends one when the entry is a real directory. The project's
        # tmp/ is a symlink to the RAM tier, so git reports it as bare `tmp` -
        # and a naive match against "tmp/" lets it straight through, which
        # produced a read-only bind over the one directory that must be
        # writable. Normalise, then compare.
        local blocked blocked_bare candidate_bare
        candidate_bare="${candidate%/}"
        for blocked in "${NEVER_BIND[@]}"; do
            blocked_bare="${blocked%/}"
            case "${candidate_bare}" in
                "${blocked_bare}"|"${blocked_bare}"/*) skip="yes" ;;
            esac
        done

        # Drop anything already covered by a directory we accepted. git lists
        # both `.claude/` and `.claude/settings.local.json`; binding the file
        # after the directory would be redundant at best and would shadow part
        # of the directory bind at worst. This relies on git emitting parents
        # before their children, which it does because the output is sorted.
        # An exact repeat is also possible, and arrives by a different route:
        # git's --directory output lists a collapsed directory *and* the
        # ignored files inside it, so re-expanding the directory yields entries
        # the raw list already contained.
        for parent in ${IGNORED_PATHS[@]+"${IGNORED_PATHS[@]}"}; do
            if [ "${parent%/}" = "${candidate_bare}" ]; then
                skip="yes"
            fi
            case "${parent}" in
                */)
                    if [ "${candidate#"${parent}"}" != "${candidate}" ]; then
                        skip="yes"
                    fi
                    ;;
            esac
        done

        if [ "${skip}" = "yes" ]; then
            continue
        fi

        # A path git reports but that isn't actually on disk would make bwrap
        # abort at launch. Better to notice here, where there's a human reading.
        [ -e "${PROJECT_PATH}/${candidate}" ] || continue

        IGNORED_PATHS+=("${candidate}")
    done
}
# }}}

# {{{ is_writable_path()
# Was this ignored path promoted to a read-write bind by --writable?
#
# Comparison strips trailing slashes from both sides, so the caller may write
# --writable big-assets or --writable big-assets/ and mean the same thing. Git
# emits the trailing slash only for directories, and asking a human to match
# that convention exactly would make the flag silently do nothing when they
# guessed wrong - the worst possible failure for a flag that opens a hole in a
# wall, because it fails in the safe direction and so never gets noticed.
is_writable_path() {
    local query="${1%/}"
    local writable
    for writable in ${WRITABLE_PATHS[@]+"${WRITABLE_PATHS[@]}"}; do
        if [ "${writable%/}" = "${query}" ]; then
            return 0
        fi
    done
    return 1
}
# }}}

# {{{ sandbox_has_unsaved_work()
# Answers: does the sandbox contain anything the real project doesn't?
#
# Returns success (0) when there IS unsaved work, so the caller can refuse to
# clobber it. The comparison runs sandbox-to-disk with rsync in dry-run
# itemising mode; any line of output means some file differs or is missing on
# the disk side, which is exactly the condition where re-provisioning would
# destroy something.
#
# This is the crude version, and it is honest about being crude: it cannot
# distinguish "work in progress" from "build output". Once the commit-and-carry
# -back mechanism exists, this should become a `git status` check instead, which
# knows the difference.
sandbox_has_unsaved_work() {
    [ -d "${SANDBOX_PATH}" ] || return 1

    # --checksum compares content rather than size-and-timestamp. Timestamps
    # are the wrong signal for this question: copying a tree, regenerating a
    # file, or simply touching one all move the clock without changing a single
    # byte, and every one of those would otherwise read as unsaved work.
    #
    # The grep then discards attribute-only differences. In rsync's itemised
    # output the first character says what will happen to the file, and a '.'
    # there means "nothing - only metadata differs". Real work shows up as
    # '>' (content to send) or '*' (a message such as a deletion), and those
    # are the only lines worth stopping for.
    # The comparison must ignore exactly what the copy ignores, or it reports
    # differences that are artefacts of the sandbox's own construction. Entering
    # the sandbox leaves empty mountpoint directories behind wherever a bound
    # path was grafted on - bwrap has to create somewhere to mount onto - and
    # those look like new directories to anything comparing the two trees.
    # They are not work; nobody made them on purpose.
    local -a exclusions=(--exclude '.git/' --exclude 'tmp')
    local ignored
    for ignored in ${IGNORED_PATHS[@]+"${IGNORED_PATHS[@]}"}; do
        exclusions+=(--exclude "/${ignored}")
    done

    # The files this script generates are excluded, because they differ from
    # disk by construction - the sandbox holds a freshly written copy and the
    # disk holds whatever was last committed. Flagging those would mean every
    # refresh refuses, which would train whoever runs it to ignore the warning
    # and so destroy the one case it exists to catch.
    #
    # The cost is narrow and worth stating: an edit made inside the sandbox to
    # one of these four files, outside its generated region, is not protected
    # by this check.
    exclusions+=(
        --exclude '/CLAUDE.md'
        --exclude '/.gitignore'
        --exclude '/scripts/enter-sandbox.sh'
        --exclude '/docs/table-of-contents.md'
    )

    UNSAVED_WORK=$(rsync --archive --checksum --itemize-changes --dry-run \
        "${exclusions[@]}" \
        "${SANDBOX_PROJECT_PATH}/" "${PROJECT_PATH}/" \
        | grep -v '^\.' \
        | grep -v '^cd' \
        | head -20)

    # The second grep drops bare directory creations. Git does not track empty
    # directories, so the skeleton's folders never travel to disk and would be
    # reported as new on every single refresh. A directory holding anything
    # worth keeping shows up as its own file line anyway, so nothing is missed
    # by ignoring the folder itself.

    # Commits are the other kind of unsaved work, and the more valuable kind.
    # A sandbox holding commits the real repository has never seen would lose
    # them entirely on refresh, and unlike edited files they leave no trace on
    # disk to recover from.
    #
    # The comparison is against the real repository's branch, read live - not
    # against the sandbox's own origin ref, which was captured when the sandbox
    # was cloned and does not move when the carry-back advances the real branch.
    # Using the stale ref reported work as uncarried immediately after it had
    # been carried, which is the kind of false alarm that gets a safety check
    # ignored.
    if [ -d "${SANDBOX_PATH}/.git" ]; then
        local real_head uncarried
        real_head=$(git -C "${DIR}" rev-parse --verify --quiet "${SANDBOX_BRANCH}" || echo "")
        if [ -n "${real_head}" ]; then
            uncarried=$(git -C "${SANDBOX_PATH}" log --oneline \
                "${real_head}..HEAD" 2>/dev/null | head -10)
            if [ -n "${uncarried}" ]; then
                UNSAVED_WORK="${UNSAVED_WORK}"$'\n'"commits not yet carried back:"$'\n'"${uncarried}"
            fi
        fi
    fi

    [ -n "${UNSAVED_WORK}" ]
}
# }}}

# {{{ check_sandbox_capacity()
# /tmp is a tmpfs, which means it is RAM wearing a filesystem's clothing. A
# project bigger than free memory does not "run slowly" - it fills RAM until
# something gets killed. Refusing here is much kinder than discovering it later.
check_sandbox_capacity() {
    local project_kilobytes available_kilobytes
    project_kilobytes=$(du -sk --exclude=.git --exclude=tmp "${PROJECT_PATH}" 2>/dev/null | cut -f1)
    available_kilobytes=$(df -k --output=avail /tmp | tail -1 | tr -d ' ')

    # The doubling is not superstition: rsync writes new files alongside old
    # ones before renaming, so a refresh can transiently hold two copies.
    if [ "$((project_kilobytes * 2))" -gt "${available_kilobytes}" ]; then
        fail "project is $((project_kilobytes / 1024))MB but only $((available_kilobytes / 1024))MB is free in /tmp;
       exclude the bulky directories via .gitignore so they become read-only
       binds instead of copies, or the sandbox will exhaust RAM"
    fi
}
# }}}

# {{{ provision_sandbox()
# Copies the project into RAM. Idempotent in the useful sense: run it on a
# fresh machine and it builds the sandbox, run it on a live one and it
# reconciles - unless reconciling would eat something, in which case it stops.
provision_sandbox() {
    if sandbox_has_unsaved_work; then
        # Naming the files is worth more than naming the problem. Refreshing
        # destroys whatever is listed here, so the decision of whether that
        # matters belongs to whoever recognises the filenames.
        fail "the sandbox holds work that is not on disk. Refusing to overwrite it.

${UNSAVED_WORK}

       (paths are relative to ${SANDBOX_PATH})
       Copy anything worth keeping into ${PROJECT_PATH},
       or delete the sandbox to discard it, then run this again."
    fi

    check_sandbox_capacity

    # The sandbox is a real git repository, built in three moves.
    #
    # 1. `git clone --shared` writes a repository whose object store is a
    #    one-line pointer at the real one rather than a copy of it. A 4GB
    #    history becomes a 108KB clone in about eight milliseconds. New objects
    #    the agent creates go into the sandbox's own store, in RAM, so the
    #    borrowed one can be mounted read-only and committing still works -
    #    the read path and the write path are physically different directories.
    #
    # 2. Sparse checkout populates only this project's directory. The monorepo
    #    tracks nearly five gigabytes; one project is a few megabytes. Cone mode
    #    also brings the repository root's own files, which is wanted - the root
    #    .gitignore has to be present for git to agree with us about what is
    #    ignored. A project that does not exist on the branch yet is fine here;
    #    it simply checks out nothing, and step 3 supplies the files.
    #
    # 3. rsync overlays the project's exact current state from disk, including
    #    work that was never committed. Without this the sandbox would start
    #    from the last commit and silently discard whatever was in progress.
    rm -rf "${SANDBOX_PATH}"
    mkdir -p "$(dirname "${SANDBOX_PATH}")"

    git clone --shared --no-checkout --quiet "${DIR}" "${SANDBOX_PATH}"

    # Redirect the borrowed store to the dual-valid path. See the note in
    # parse_arguments for why the path git wrote here cannot be used as-is.
    mkdir -p "$(dirname "${OBJECT_LINK_PATH}")"
    ln -sfn "${DIR}/.git/objects" "${OBJECT_LINK_PATH}"
    printf '%s\n' "${OBJECT_LINK_PATH}" \
        > "${SANDBOX_PATH}/.git/objects/info/alternates"

    git -C "${SANDBOX_PATH}" sparse-checkout set --cone "${PROJECT_NAME}"

    # A branch that exists is checked out; one that does not is created from
    # the trunk. Either way the sandbox lands on a named branch rather than a
    # detached head, so the carry-back has something to fetch by name.
    if git -C "${SANDBOX_PATH}" rev-parse --verify --quiet \
        "refs/remotes/origin/${SANDBOX_BRANCH}" >/dev/null; then
        git -C "${SANDBOX_PATH}" checkout --quiet "${SANDBOX_BRANCH}"
    else
        git -C "${SANDBOX_PATH}" checkout --quiet -b "${SANDBOX_BRANCH}" \
            "refs/remotes/origin/master"
    fi

    # The ignored paths are excluded because they get bound in at launch rather
    # than copied - that is the whole point of reading .gitignore. .git is
    # excluded because the sandbox has its own now, and overwriting it with the
    # real repository's would replace a small private store with a pointer to
    # somebody else's.
    local -a exclusions=(--exclude '/.git/' --exclude '/tmp')
    local ignored
    for ignored in ${IGNORED_PATHS[@]+"${IGNORED_PATHS[@]}"}; do
        exclusions+=(--exclude "/${ignored}")
    done

    mkdir -p "${SANDBOX_PATH}/${PROJECT_NAME}"
    rsync --archive --delete "${exclusions[@]}" \
        "${PROJECT_PATH}/" "${SANDBOX_PATH}/${PROJECT_NAME}/"

    # Inside the sandbox, tmp/ is a plain directory rather than the usual
    # symlink out to /tmp and /dev/shm.
    #
    # The convention exists to keep scratch data off spinning disk and in RAM.
    # In here the entire project is already in RAM, so the symlink would buy
    # nothing - and it would cost something real: its target lives outside the
    # project, so it would either dangle inside the mount namespace or have to
    # be punched through the wall to work. A directory has neither problem.
    rm -rf "${SANDBOX_PROJECT_PATH}/tmp"
    mkdir -p "${SANDBOX_PROJECT_PATH}/tmp/shared-memory"
}
# }}}

# {{{ write_sandbox_notice()
# Writes the block of CLAUDE.md that tells an agent where it is standing.
#
# Appended to an existing file, created if there isn't one, and replaced in
# place between its markers on every re-run - so the warning stays accurate as
# the mount layout changes, without any hand-written notes above it being lost.
write_sandbox_notice() {
    # Written into the sandbox, not onto the disk. The real project directory
    # has exactly one writer - the carry-back - and adding a second would put
    # an untracked copy of a tracked file in its way. It reaches disk the same
    # way everything else does: by being committed.
    local claude_md="${SANDBOX_PROJECT_PATH}/CLAUDE.md"
    local notice_body
    local escapes_description=""

    if [ "${#IGNORED_PATHS[@]}" -gt 0 ]; then
        local ignored access
        for ignored in "${IGNORED_PATHS[@]}"; do
            if is_writable_path "${ignored}"; then
                access="READ-WRITE, reaches the real disk"
            else
                access="read-only"
            fi
            escapes_description+="- \`${ignored}\` - ${access}"$'\n'
        done
    else
        escapes_description="- (none yet - nothing in this project is gitignored)"$'\n'
    fi

    notice_body=$(cat <<EOF
${NOTICE_BEGIN}

## Where you are

You are running inside a sandbox. This directory looks like
\`${PROJECT_PATH}\` and reports that path in every tool, but it is not that
directory. It is a copy held in RAM at \`${SANDBOX_PROJECT_PATH}\`, presented
at the real path through a Linux mount namespace.

This is an execution environment, not a scratch pad. The work you do here is
the real work, on the real branch (\`${SANDBOX_BRANCH}\`). You are sandboxed
so that mistakes are cheap, not because what you produce is provisional.

**Uncommitted work is lost when the machine reboots or loses power.**
The RAM holding this directory is not backed by disk. There is no autosave and
no crash recovery. A power cut at hour six costs six hours of uncommitted work.

**Committing is what makes work durable.** This is a real git repository. When
you commit, a watcher outside the sandbox notices within seconds and carries
the commit into the real repository on disk, where a reboot cannot reach it.
Commit whenever a piece of work stands on its own, and say so plainly when you
are holding work that isn't committed yet.

## What exists and what doesn't

The rest of the home directory is not hidden from you, it is absent. SSH keys,
browser profiles, shell history, other projects' files - none of these are
mounted into this namespace, so reads of them fail with "no such file" rather
than a permission error. Do not interpret that as a bug or try to work around
it. It is the wall, and it is working.

One precise exception, so you are not misled: this repository borrows the real
object store read-only, so other projects' *committed history* is readable
through git even though their files are not on disk. You cannot write to it.
Reading another project's history to answer a question is fine; treat it as
reference material, not as your working tree.

The system directories (\`/usr\`, \`/etc\`) are mounted read-only. Writes there
will fail. Do not attempt to install system packages; the failure is by design.

These paths are bound in from the real filesystem rather than copied, because
they are gitignored and possibly large:

${escapes_description}
Read-only binds behave like the system directories: reads work, writes fail.
A bind marked READ-WRITE is a genuine hole - anything written through it lands
on the real disk and survives, which also means it can genuinely be destroyed.

## What is not contained

The network. You can reach the internet, and so could anything you run. The
sandbox constrains the filesystem only. Apply the same care to network actions
you would apply outside it - pushing to remotes, calling APIs, sending data
anywhere - because none of those are undone by a reboot.

## How work leaves here

You never push, and you have no route to the real repository - that is
deliberate, and it is what keeps the wall standing. The traffic goes the other
way: a watcher on the outside reads this repository and pulls your commits into
the real one. Committing is the entire interface. Nothing else you do carries
work out.

If the real working tree happens to have uncommitted edits when your commit
lands, the watcher still saves the commit to disk immediately but leaves the
visible directory alone until the human tidies up. Your work is never at risk
in that case; it just isn't visible yet.

## Consequences worth knowing

Conversation transcripts are deliberately bound out to the real disk, so they
survive. The session-end backup hook, however, cannot see the other projects it
normally writes into, so it will do nothing here; run the transcript backup from
outside the sandbox afterwards if you want the archived copy.

${NOTICE_END}
EOF
)

    # Three cases, and they differ in what must be preserved:
    #   no file          -> create one containing just the notice
    #   file, no markers -> append; whatever is already there is a human's
    #   file, markers    -> replace between markers, keeping text either side
    if [ ! -f "${claude_md}" ]; then
        printf '# %s\n\n%s\n' "${PROJECT_NAME}" "${notice_body}" > "${claude_md}"
    elif ! grep -Fq "${NOTICE_BEGIN}" "${claude_md}"; then
        printf '\n%s\n' "${notice_body}" >> "${claude_md}"
    else
        local rebuilt="${claude_md}.rebuilding"
        awk -v begin="${NOTICE_BEGIN}" -v end="${NOTICE_END}" -v body="${notice_body}" '
            $0 == begin { print body; inside = 1; next }
            $0 == end   { inside = 0; next }
            !inside     { print }
        ' "${claude_md}" > "${rebuilt}"
        mv "${rebuilt}" "${claude_md}"
    fi
}
# }}}

# {{{ compose_bwrap_arguments()
# Emits the mount plan, one argument per line, for embedding in the launcher.
#
# THE ORDERING RULE, which is the only thing you need to understand to modify
# this safely: bwrap applies these in sequence onto a stack, and a later mount
# shadows an earlier one at the same path. Reorder them and you get either an
# empty sandbox or a wide-open one, with no error either way.
#
# The layout exploits one local fact: /home/ritz is a symlink to /mnt/mtwo, so
# the home directory and the data disk are the same object. That means a single
# tmpfs over /mnt/mtwo blanks the entire home in one stroke - every project,
# every dotfile - and everything the agent needs is then bound back explicitly.
# Deny-by-default, obtained for free, rather than by enumerating what to hide.
compose_bwrap_arguments() {
    cat <<EOF
    --unshare-user
    --unshare-ipc
    --unshare-pid
    --unshare-uts
    --unshare-cgroup
    --die-with-parent
EOF
    # Note the absence of --unshare-net. The agent must reach the API to
    # function, so the network namespace is deliberately shared. See the
    # "what is not contained" section of the generated CLAUDE.md.
    #
    # Note also the absence of --new-session. It would block terminal input
    # injection, which is a real attack, but it calls setsid() and so detaches
    # the controlling terminal - which breaks Ctrl-C and job control in an
    # interactive TUI. Interactivity wins here; revisit for batch runs.

    cat <<EOF
    --ro-bind /usr /usr
    --ro-bind /etc /etc
    --symlink usr/lib /lib
    --symlink usr/lib /lib64
    --symlink usr/bin /bin
    --symlink usr/bin /sbin
    --proc /proc
    --dev /dev
    --tmpfs /run
    --tmpfs /var/tmp
    --tmpfs /tmp
    --tmpfs /dev/shm
EOF
    # /tmp gets a fresh tmpfs rather than the host's. The host /tmp holds every
    # other project's sandbox, and leaving it visible would let an agent in one
    # sandbox rewrite the contents of another - undoing the isolation by the
    # side door. The sandbox bind below reads its source from the host, so
    # blanking /tmp in here costs nothing.

    # The blanking stroke, and the recreation of the home symlink on top of it.
    # /home lives on the root filesystem and holds only the symlink, so a tmpfs
    # plus one --symlink reproduces it exactly.
    cat <<EOF
    --tmpfs ${AGENT_HOME}
    --tmpfs /home
    --symlink ${AGENT_HOME} /home/ritz
EOF

    # The agent binary: bound read-only rather than copied, because it is 486MB
    # and copying it would spend a twentieth of available RAM on a file that
    # never changes during a session.
    cat <<EOF
    --ro-bind ${AGENT_BINARY_DIR} ${AGENT_BINARY_DIR}
EOF

    # Agent state, split by whether corrupting it would matter.
    #
    # Read-only: instructions, settings, skills, plugins. The agent reads these
    # and has no business rewriting them, and a mangled global CLAUDE.md would
    # follow you into every future session on the machine.
    #
    # Read-write: credentials, project registry, transcripts. All three must be
    # writable for the agent to work at all - tokens refresh, the registry
    # records state, transcripts append. The transcript binding is the one
    # deliberate leak in the design: it lets a session's record survive the
    # reboot that erases everything else, which is the point of keeping records.
    #
    # The -try suffix on the optional ones means "bind this if it exists" -
    # without it, a machine lacking plugins/ fails at launch instead of running.
    cat <<EOF
    --ro-bind-try ${AGENT_HOME}/.claude/CLAUDE.md ${AGENT_HOME}/.claude/CLAUDE.md
    --ro-bind-try ${AGENT_HOME}/.claude/settings.json ${AGENT_HOME}/.claude/settings.json
    --ro-bind-try ${AGENT_HOME}/.claude/skills ${AGENT_HOME}/.claude/skills
    --ro-bind-try ${AGENT_HOME}/.claude/plugins ${AGENT_HOME}/.claude/plugins
    --bind-try ${AGENT_HOME}/.claude/.credentials.json ${AGENT_HOME}/.claude/.credentials.json
    --bind-try ${AGENT_HOME}/.claude.json ${AGENT_HOME}/.claude.json
    --bind-try ${AGENT_HOME}/.claude/projects ${AGENT_HOME}/.claude/projects
    --tmpfs ${AGENT_HOME}/.claude/shell-snapshots
    --tmpfs ${AGENT_HOME}/.claude/session-env
EOF

    # The work itself, bound at the real monorepo path so that every absolute
    # path in the project's own documentation continues to resolve, and so git
    # finds its repository root exactly where it expects to.
    #
    # What appears at that path is a repository containing only this project,
    # so a reach for a neighbouring project's files fails rather than quietly
    # succeeding. The borrowed object store is mounted read-only at the
    # separate path the alternates file names.
    cat <<EOF
    --bind ${SANDBOX_PATH} ${DIR}
    --ro-bind ${DIR}/.git/objects ${OBJECT_LINK_PATH}
    --ro-bind-try ${AGENT_HOME}/.gitconfig ${AGENT_HOME}/.gitconfig
EOF

    # The gitignored escapes, mounted on top of the sandbox bind. Read-only
    # unless explicitly promoted, because a read-only bind gives the whole
    # benefit being sought - not copying something huge - at none of the risk.
    local ignored access
    for ignored in ${IGNORED_PATHS[@]+"${IGNORED_PATHS[@]}"}; do
        if is_writable_path "${ignored}"; then
            access="--bind"
        else
            access="--ro-bind"
        fi
        printf '    %s %s %s\n' "${access}" \
            "${PROJECT_PATH}/${ignored%/}" "${PROJECT_PATH}/${ignored%/}"
    done
}
# }}}

# {{{ generate_launcher()
# Writes the script that actually enters the sandbox.
#
# The launcher is a build artifact, not source: it is gitignored, it hardcodes
# absolute paths for this machine, and it is replaced wholesale on every run of
# init-project.sh. To change how the sandbox is mounted, change
# compose_bwrap_arguments() and re-run - never edit the launcher, because the
# edit will vanish the next time anybody refreshes the project.
generate_launcher() {
    local launcher="${PROJECT_PATH}/scripts/enter-sandbox.sh"
    local mount_plan mount_plan_continued
    mount_plan=$(compose_bwrap_arguments)

    # Append a line-continuation backslash to every line of the mount plan, so
    # the whole thing can be dropped into a single bwrap invocation in the
    # generated launcher. This is done out here, in ordinary shell, rather than
    # inside the heredoc below - a heredoc body expands like a double-quoted
    # string, where $'\n' is not special and the substitution would silently
    # produce the literal characters instead of a newline.
    mount_plan_continued=$(printf '%s\n' "${mount_plan}" | sed 's/$/ \\/')

    # The rebuild-after-reboot call has to carry the --writable choices with it.
    # Without them a reboot would quietly demote every read-write bind back to
    # read-only, and the first sign of it would be a build failing for reasons
    # that have nothing to do with the build - the worst kind of bug, because
    # the cause is a machine restart hours earlier.
    local writable_flags="" writable
    for writable in ${WRITABLE_PATHS[@]+"${WRITABLE_PATHS[@]}"}; do
        writable_flags+=" --writable '${writable}'"
    done

    cat > "${launcher}" <<EOF
#!/bin/bash
# =============================================================================
# enter-sandbox.sh - GENERATED FILE, DO NOT EDIT
# =============================================================================
# Opens an agent session inside the RAM-backed sandbox for '${PROJECT_NAME}'.
#
# Regenerate with:  ${SELF_PATH} --refresh ${PROJECT_NAME}
# Edits to this file are lost on the next refresh.
#
# The sandbox presents itself at ${PROJECT_PATH}
# but actually lives at ${SANDBOX_PATH}, in RAM.
# Nothing written inside survives a reboot.
# =============================================================================

set -o errexit
set -o nounset

SANDBOX_PATH="${SANDBOX_PATH}"
PROJECT_PATH="${PROJECT_PATH}"
INIT_SCRIPT="${SELF_PATH}"
MONOREPO_DIR="${DIR}"

# A reboot wipes /tmp, so the sandbox this launcher was built for may simply
# not be there. Rebuilding it is the correct response - that is what makes the
# whole arrangement survivable across reboots without any save mechanism, and
# it is why losing the sandbox costs only the uncommitted work inside it.
if [ ! -d "\${SANDBOX_PATH}" ]; then
    printf 'sandbox is gone (rebooted?) - rebuilding from disk\n' >&2
    eval "\"\${INIT_SCRIPT}\" --dir \"\${MONOREPO_DIR}\"${writable_flags} --refresh \"${PROJECT_NAME}\""
fi

# The watcher is what makes committing meaningful in here. It runs out on this
# side of the wall, reads the sandbox repository, and copies every commit into
# the real one - so work stops being at the mercy of the power supply the
# moment it is committed. The sandbox is never told about it and has no route
# to it; that asymmetry is the point.
CARRY_BACK="\${INIT_SCRIPT%/*}/carry-back.sh"
WATCHER_LOG="/dev/shm/${PROJECT_NAME}/carry-back.log"
mkdir -p "/dev/shm/${PROJECT_NAME}"

"\${CARRY_BACK}" --dir "\${MONOREPO_DIR}" --interval 5 "${PROJECT_NAME}" \\
    >> "\${WATCHER_LOG}" 2>&1 &
WATCHER_PID=\$!
printf 'carrying commits to disk every 5s; log: %s\n' "\${WATCHER_LOG}" >&2

# Not exec'd, because there is tidying to do afterwards. The trap covers the
# session being killed rather than exited; without it a stopped session would
# leave a watcher polling a sandbox nobody is using.
trap 'kill "\${WATCHER_PID}" 2>/dev/null || true' EXIT INT TERM

bwrap \\
${mount_plan_continued}
    --chdir "\${PROJECT_PATH}" \\
    --setenv HOME "/home/ritz" \\
    --setenv CLAUDE_SANDBOX "${PROJECT_NAME}" \\
    "${AGENT_BINARY_DIR}/claude" --dangerously-skip-permissions "\$@" || true

# A commit made in the last few seconds of a session may not have been polled
# yet. Catching up once on the way out closes that window, which would
# otherwise be the most likely moment to lose work - the end of a session is
# exactly when the last commit gets made.
kill "\${WATCHER_PID}" 2>/dev/null || true
"\${CARRY_BACK}" --dir "\${MONOREPO_DIR}" --once "${PROJECT_NAME}"
EOF

    chmod +x "${launcher}"
}
# }}}

# {{{ report()
report() {
    printf '\n'
    printf '  project   %s\n' "${PROJECT_PATH}"
    printf '  sandbox   %s  (RAM - lost on reboot)\n' "${SANDBOX_PATH}"
    printf '  enter     %s/scripts/enter-sandbox.sh\n' "${PROJECT_PATH}"

    if [ "${#IGNORED_PATHS[@]}" -gt 0 ]; then
        printf '\n  bound in from the real disk instead of copied:\n'
        local ignored access
        for ignored in "${IGNORED_PATHS[@]}"; do
            if is_writable_path "${ignored}"; then
                access="READ-WRITE"
            else
                access="read-only"
            fi
            printf '    %-40s %s\n' "${ignored}" "${access}"
        done
    fi

    printf '\n  not contained: the network. Commits and pushes from inside\n'
    printf '  the sandbox reach the real world and are not undone by reboot.\n\n'
}
# }}}

# {{{ main()
main() {
    parse_arguments "$@"
    require_tools

    if [ "${REFRESH_ONLY}" = "yes" ]; then
        [ -d "${PROJECT_PATH}" ] || fail "no such project to refresh: ${PROJECT_PATH}"
    fi

    # On disk, only what git does not track: somewhere to keep the launcher,
    # and the scratch symlinks. Everything git tracks is written into the
    # sandbox further down, and arrives here later by being committed. Two
    # writers on one tracked file is the bug this ordering exists to avoid.
    mkdir -p "${PROJECT_PATH}/scripts"
    link_ram_directories

    # The ignored-path list feeds both the copy step (as exclusions) and the
    # launcher (as binds), so it is gathered before either of them runs.
    collect_ignored_paths
    provision_sandbox

    # Everything from here writes into the sandbox. mkdir -p and the marker
    # block make each of these safe on a project that already has content.
    create_project_skeleton "${SANDBOX_PROJECT_PATH}"
    write_project_gitignore "${SANDBOX_PROJECT_PATH}"
    write_sandbox_notice

    # The launcher is the exception that proves the rule: it is gitignored, so
    # writing it to disk cannot collide with anything, and it has to live on
    # disk because its whole job is to rebuild a sandbox that no longer exists.
    generate_launcher
    mkdir -p "${SANDBOX_PROJECT_PATH}/scripts"
    rsync --archive "${PROJECT_PATH}/scripts/enter-sandbox.sh" \
        "${SANDBOX_PROJECT_PATH}/scripts/enter-sandbox.sh"

    report
}
# }}}

main "$@"
