--[[
Path Smoothing for A* Paths

Removes redundant waypoints from paths generated by A* algorithm.
Uses line-of-sight checks to skip intermediate points while
preserving path validity (no shortcuts through obstacles).

Smoothing Methods:
- smooth_path: Iterative, finds farthest visible point
- smooth_greedy: Binary search for farthest visible, more aggressive
- remove_collinear: Fast, removes only direction-preserving points

Usage:
    local smooth = require("runtime.pathfinding.smooth")

    -- Basic smoothing
    local smoothed = smooth.smooth_path(path, grid, can_pass)

    -- Fast collinearity removal
    local smoothed = smooth.remove_collinear(path)
]]

local smooth = {}

-- {{{ has_line_of_sight
-- Checks if there's a clear line between two grid points.
-- Uses Bresenham's line algorithm to check all tiles along the line.
--
-- @param grid Pathing grid (for bounds checking)
-- @param x1, y1 Start point (grid coordinates)
-- @param x2, y2 End point (grid coordinates)
-- @param can_pass Function(x, y) -> boolean for passability
-- @return boolean true if all tiles along line are passable
local function has_line_of_sight(grid, x1, y1, x2, y2, can_pass)
    -- Bresenham's line algorithm
    local dx = math.abs(x2 - x1)
    local dy = math.abs(y2 - y1)
    local sx = x1 < x2 and 1 or -1
    local sy = y1 < y2 and 1 or -1
    local err = dx - dy

    local x, y = x1, y1

    while true do
        -- Check current cell
        if not can_pass(x, y) then
            return false
        end

        -- Reached destination
        if x == x2 and y == y2 then
            return true
        end

        local e2 = 2 * err

        if e2 > -dy then
            err = err - dy
            x = x + sx
        end

        if e2 < dx then
            err = err + dx
            y = y + sy
        end
    end
end
-- }}}

-- {{{ are_collinear
-- Checks if three points are collinear (on the same line).
-- Uses cross product which is zero for collinear points.
--
-- @param p1, p2, p3 Points with x, y fields
-- @return boolean true if points are collinear
local function are_collinear(p1, p2, p3)
    -- Cross product: (p2-p1) x (p3-p1)
    -- If zero, points are collinear
    local cross = (p2.x - p1.x) * (p3.y - p1.y) - (p2.y - p1.y) * (p3.x - p1.x)
    return cross == 0
end
-- }}}

-- {{{ smooth.smooth_path
-- Removes redundant waypoints from a path using line-of-sight checks.
-- Iteratively finds the farthest visible point from each position.
--
-- @param path Array of {x, y} waypoints from A*
-- @param grid Pathing grid
-- @param can_pass Function(x, y) -> boolean, defaults to grid.walkable check
-- @return Smoothed path with fewer waypoints
function smooth.smooth_path(path, grid, can_pass)
    if not path or #path <= 2 then
        return path  -- Nothing to smooth
    end

    -- Default can_pass uses grid walkability
    can_pass = can_pass or function(x, y)
        local row = grid.cells[y]
        local cell = row and row[x]
        return cell and cell.walkable
    end

    local smoothed = { path[1] }  -- Always keep start
    local current_idx = 1

    while current_idx < #path do
        -- Try to skip as many waypoints as possible
        local farthest_visible = current_idx + 1

        for i = current_idx + 2, #path do
            local from = path[current_idx]
            local to = path[i]

            if has_line_of_sight(grid, from.x, from.y, to.x, to.y, can_pass) then
                farthest_visible = i
            else
                -- Can't see past this point, stop looking
                -- The previous visible point is the farthest we can reach
                break
            end
        end

        -- Add the farthest visible point
        smoothed[#smoothed + 1] = path[farthest_visible]
        current_idx = farthest_visible
    end

    return smoothed
end
-- }}}

-- {{{ smooth.smooth_greedy
-- More aggressive smoothing using binary search.
-- Always tries to skip to goal first, falls back to binary search.
--
-- @param path Array of {x, y} waypoints from A*
-- @param grid Pathing grid
-- @param can_pass Function(x, y) -> boolean
-- @return Smoothed path with minimal waypoints
function smooth.smooth_greedy(path, grid, can_pass)
    if not path or #path <= 2 then
        return path
    end

    can_pass = can_pass or function(x, y)
        local row = grid.cells[y]
        local cell = row and row[x]
        return cell and cell.walkable
    end

    local smoothed = { path[1] }
    local current_idx = 1

    while current_idx < #path do
        local from = path[current_idx]

        -- Try direct line to goal first
        if has_line_of_sight(grid, from.x, from.y, path[#path].x, path[#path].y, can_pass) then
            smoothed[#smoothed + 1] = path[#path]
            break
        end

        -- Binary search for farthest visible point
        local lo, hi = current_idx + 1, #path
        local best = current_idx + 1

        while lo <= hi do
            local mid = math.floor((lo + hi) / 2)
            local to = path[mid]

            if has_line_of_sight(grid, from.x, from.y, to.x, to.y, can_pass) then
                best = mid
                lo = mid + 1
            else
                hi = mid - 1
            end
        end

        smoothed[#smoothed + 1] = path[best]
        current_idx = best
    end

    return smoothed
end
-- }}}

-- {{{ smooth.remove_collinear
-- Removes waypoints that are collinear with their neighbors.
-- Faster than line-of-sight but less aggressive.
-- Does NOT check obstacles - only removes direction-preserving points.
--
-- @param path Array of {x, y} waypoints
-- @return Path with collinear points removed
function smooth.remove_collinear(path)
    if not path or #path <= 2 then
        return path
    end

    local smoothed = { path[1] }

    for i = 2, #path - 1 do
        local prev = smoothed[#smoothed]
        local curr = path[i]
        local next = path[i + 1]

        -- Keep point only if it changes direction
        if not are_collinear(prev, curr, next) then
            smoothed[#smoothed + 1] = curr
        end
    end

    -- Always keep the goal
    smoothed[#smoothed + 1] = path[#path]

    return smoothed
end
-- }}}

-- {{{ smooth.smooth_path_for_movement
-- Convenience function that applies both collinearity and LOS smoothing.
-- Best balance of speed and smoothness for typical use.
--
-- @param path Array of {x, y} waypoints
-- @param grid Pathing grid
-- @param can_pass Function(x, y) -> boolean
-- @return Fully smoothed path
function smooth.smooth_path_for_movement(path, grid, can_pass)
    if not path or #path <= 2 then
        return path
    end

    -- First pass: remove collinear points (fast)
    local pass1 = smooth.remove_collinear(path)

    -- Second pass: LOS-based smoothing
    local pass2 = smooth.smooth_path(pass1, grid, can_pass)

    return pass2
end
-- }}}

-- {{{ smooth.path_stats
-- Returns statistics about path smoothing effectiveness.
--
-- @param original Original path
-- @param smoothed Smoothed path
-- @return Table with original_count, smoothed_count, reduction_percent
function smooth.path_stats(original, smoothed)
    local orig_count = original and #original or 0
    local smooth_count = smoothed and #smoothed or 0
    local reduction = 0

    if orig_count > 0 then
        reduction = (1 - smooth_count / orig_count) * 100
    end

    return {
        original_count = orig_count,
        smoothed_count = smooth_count,
        reduction_percent = reduction,
    }
end
-- }}}

-- {{{ smooth.get_line_tiles
-- Returns all tiles along a line between two points.
-- Useful for debugging or visualization.
--
-- @param x1, y1 Start point
-- @param x2, y2 End point
-- @return Array of {x, y} tiles along the line
function smooth.get_line_tiles(x1, y1, x2, y2)
    local tiles = {}
    local dx = math.abs(x2 - x1)
    local dy = math.abs(y2 - y1)
    local sx = x1 < x2 and 1 or -1
    local sy = y1 < y2 and 1 or -1
    local err = dx - dy

    local x, y = x1, y1

    while true do
        tiles[#tiles + 1] = { x = x, y = y }

        if x == x2 and y == y2 then
            break
        end

        local e2 = 2 * err

        if e2 > -dy then
            err = err - dy
            x = x + sx
        end

        if e2 < dx then
            err = err + dx
            y = y + sy
        end
    end

    return tiles
end
-- }}}

-- {{{ Exports
smooth.has_line_of_sight = has_line_of_sight
smooth.are_collinear = are_collinear
-- }}}

return smooth
