#!/usr/bin/env luajit
-- measure-authorship.lua - How much of this repository's conversation did the
-- person write, and how much did the machine?
--
-- In plain terms: every conversation that built the repository is saved as a
-- transcript. This reads all of them, counts the characters the person typed
-- and the characters the model wrote, and reports the two totals and their
-- ratio. Pasted material counts as the person's (pasting something means you
-- read it and chose it), except a pasted error or log, which was the machine's
-- output being handed back. Messages the tool generated on its own -- warm-ups,
-- command output, notifications -- belong to neither side and are reported
-- apart, so every rule can be checked rather than trusted.
--
-- The same conversation is often saved in several places (two projects' folders,
-- a day file and a date-range file, one early conversation at five levels of
-- detail), so turns are matched by their content and counted once.
--
-- The unit is characters on both sides: the transcripts record no token counts,
-- and characters counted the same way on both sides keep the ratio honest.
--
-- It then reads the repository's own tracked files and sorts them into piles:
-- notes (hand-written, so they join the person's side), source code, and
-- documents (issue files included), leaving out generated copies, inputs and
-- outputs, and setting aside code that belongs to someone else. The four
-- headline figures are: human-written text, machine-written text, source code
-- in the tree, documents in the tree.
--
-- Usage:
--   measure-authorship.lua                 -- terminal summary
--   measure-authorship.lua --json          -- machine-readable
--   measure-authorship.lua --largest [N]   -- the N biggest files in each pile
--   measure-authorship.lua --dir=/path     -- measure another checkout (any position)
--   measure-authorship.lua --workers=N     -- how many parallel workers (default: CPU count)
--   measure-authorship.lua --worker LIST OUT        -- internal: transcripts share
--   measure-authorship.lua --count-worker LIST OUT  -- internal: repository share
--
-- See measure-authorship.info.md for the counting rules as a table, and
-- delta-version/issues/059-measure-human-and-machine-authorship.md for why.

-- {{{ DIR Configuration
-- DIR is the repository being measured. The script's own home (for its RAM
-- scratch space and the shared RAM-tier library) is found from where the script
-- itself lives, so --dir can point at a fixture tree in a test without moving
-- the scratch space there.
local DIR = "/mnt/mtwo/programming/ai-stuff"
local WORKER_COUNT = nil
local mode_arguments = {}
for _, argument in ipairs(arg) do
    local dir_value = argument:match("^%-%-dir=(.+)$")
    local workers_value = argument:match("^%-%-workers=(%d+)$")
    if dir_value then
        DIR = dir_value
    elseif workers_value then
        WORKER_COUNT = tonumber(workers_value)
    else
        mode_arguments[#mode_arguments + 1] = argument
    end
end
local SCRIPT_PATH = arg[0]
local PROJECT_HOME = SCRIPT_PATH:match("^(.*)/scripts/[^/]+$")
    or "/mnt/mtwo/programming/ai-stuff/delta-version"
local MONOREPO_HOME = PROJECT_HOME:match("^(.*)/[^/]+$")
local RAM_TIER_LIBRARY = MONOREPO_HOME .. "/scripts/libs/ensure-ram-tiers"
-- }}}

local bit = require("bit")

-- {{{ Configuration
local config = {
    -- The exporter separates every turn with a line of exactly eighty dashes.
    separator = string.rep("-", 80),

    -- Conversation boundaries: the chain of preceding turns that keys each
    -- turn restarts here, so a conversation keys the same way wherever it sits.
    -- The second capture of the summary header is the session id; an id that
    -- begins "agent-" is a sub-agent, whose "user" is the main model.
    boundaries = {
        "^# Conversation Summary:",
        "^## 📜 Conversation",
        "^Printing conversation:",
    },

    -- User turns the tool wrote on its own, matched on the turn's opening.
    -- Credited to nobody; reported as "system".
    system_openings = {
        "^Warmup$",
        "^Caveat: The messages below were generated by the user while running local commands",
        "^<local%-command%-stdout>",
        "^<local%-command%-stderr>",
        "^<local%-command%-caveat>",
        "^<task%-notification>",
        "^<bash%-stdout>",
        "^<bash%-stderr>",
        "^<bash%-notification>",
        "^%[Request interrupted by user",
        -- A skill's instructions, loaded into the conversation by the tool.
        -- Most announce themselves with their directory; a few open straight
        -- on their own heading or first sentence and are listed by name.
        "^Base directory for this skill:",
        "^# [%w%-]+[%w%- ]* Skill ",
        "^Approach this as the design lead at a small studio",
        -- Not listed here: "Hello computer, all is well." It opens 56 turns,
        -- most of them templated prompts carrying an issue file, and was
        -- first taken for a script's greeting. The owner answered (issue 059):
        -- only they ever type it. A template the owner wrote is the owner's
        -- writing, so those turns are the person's.
    },

    -- User turns the model wrote: its own summary of a session it is
    -- continuing after compaction, and messages sent by another model session.
    machine_openings = {
        "^This session is being continued from a previous conversation",
        "^Another Claude session sent a message:",
        "^<agent%-message",
    },

    -- Only one thing moves a user turn out of the person's column wholesale:
    -- a session id beginning "agent-", which is the tool's own mark of a
    -- sub-agent, whose prompts the main model wrote.
    --
    -- Decided against: treating every other session in a `<date>_agent-<n>.md`
    -- file as a script's `claude -p` run and setting its prompts aside. The
    -- file name is the exporter's label, not evidence of who typed; the only
    -- other sign was the "Hello computer, all is well." greeting, and the
    -- owner says only they type it. With no independent evidence of a
    -- script, those prompts count as the person's.

    -- Wrappers around something the person did type: the typed part inside is
    -- human, the wrapper and anything else in the turn is system.
    typed_inside = {
        { open = "<command%-args>", close = "</command%-args>", whole = "^<command%-name>" },
        { open = "<user%-memory%-input>", close = "</user%-memory%-input>", whole = "^<user%-memory%-input>" },
        { open = "<bash%-input>", close = "</bash%-input>", whole = "^<bash%-input>" },
    },

    -- Pasted-log recognition. A block with any strong signature is a log; a
    -- block where at least half the non-empty lines look like log lines is a
    -- log. Everything else is prose.
    strong_signatures = {
        "Traceback %(most recent call last%)",
        "stack traceback:",
        "^%s*at [%w%.<>_$]+ %(.-:%d+:%d+%)",
        "^%s*[Ee]rror: .-[%w_%-%.]+%.%a+:%d+",
        "^%S+%.%a+:%d+:%d*:? ?[Ee]rror",
        "^luajit: ",
        "^lua: ",
    },
    log_line_shapes = {
        "[%w_%-%./]+%.%a%a?%a?%a?:%d+:",          -- path.ext:123:
        "^%s*%[?%d%d%d%d%-%d%d%-%d%d[ T]%d%d:%d%d", -- leading timestamp
        "^%s*%[?%d%d:%d%d:%d%d",                    -- leading clock time
        "^%s*%[?%u%u%u%u?%u?%]?:? ",                -- [ERROR] WARN INFO DEBUG
        "^%s*%^+%s*$",                              -- compiler caret line
        "^%s*%$ ",                                  -- shell prompt
        "^[%w_%-]+@[%w_%-]+[: ~]",                  -- user@host prompt
        "^%s*[Ee]rror:",                            -- (not bare "Error", which
        "^%s*ERROR",                                --  opens ordinary sentences)
        "^%s*[Ww]arning:",
        "^%s*FAIL",
        "^%s*%d+ | ",                               -- numbered source excerpt
        "^%s*#%$ ",                                 -- nvcc's echoed command lines
        "^%s*%-%-[%w][%w%-]+",                      -- a line of command flags
        "[%w%._]+=%S+.-[%w%._]+=%S+",               -- two key=value pairs (structured logs)
        "^%s*[%a][%w]*_[%w_]+: ",                   -- snake_case_logger: message
        "%d%d%d%d/%d%d/%d%d",                       -- slash-dated timestamp
        "^%s*/[%w%._%-/]+%s*$",                     -- a bare absolute path
        "%S%(%d+%): [ew]%a+",                       -- file.h(79): error / warning
        "^%s*%d+ errors? ",                         -- "4 errors detected in ..."
        "^%s*[%w_%-]+ warning :",                   -- "nvcc warning : ..."
    },
    log_line_levels = { ERROR = true, WARN = true, WARNING = true, INFO = true,
                        DEBUG = true, FATAL = true, TRACE = true, NOTE = true },

    -- Pasted program output that is not an error: a pipeline's status lines,
    -- a box-drawn report, a directory listing, the model's own words quoted
    -- back. The owner's answer (issue 059): "ideally, no [it shouldn't count
    -- as theirs], but good luck recognizing it." These shapes join the log
    -- shapes under the same half-the-block rule and the same spreading, so a
    -- sentence or a question the person wrote around the output stays theirs.
    output_line_shapes = {
        "\226[\148\149]",                           -- box drawing, U+2500-257F
        "\226\150[\128-\159]",                      -- shade/bar blocks, U+2580-259F
        "%[[=#>%.%- ]*[=#][=#>%.%- ]*%]",           -- [=====>    ] progress bar
        "%(%d+%.?%d*%%%)",                          -- (53.1%)
        "%d+/%d+ %a",                               -- 4200/7904 poems
        "^%s*>%s",                                  -- a quoted line ("> ...")
        "^%s*>$",
        "^%s*%[[%w_%-]+@[^%]]+%][%$#]",             -- [ritz@kuvalu dir]$ prompt
        "^%s*[\226\240][\128-\191]+%s",             -- emoji-led status (✅ 📝 🖼)
        "%S   +%S.-%S   +%S",                       -- columns aligned by spaces
        "^%s*%.?%.?/?[%w%._%-]+/[%w%._%-/]*%s*$",   -- a bare relative path
    },
}
-- }}}

-- {{{ Repository rules
-- The second half of the measure reads the repository's own files -- only
-- those git tracks, so scratch space, build products and anything ignored are
-- out -- and sorts each into one of three piles, counted with the same
-- character rule as the transcripts:
--
--   notes   -- anything under a notes/ folder. The owner's rule: notes are
--              written by hand, so they join the person's side. Counted
--              wherever the folder sits, even under input/ (words-pdf keeps
--              its poems at input/notes/).
--   docs    -- documents, issue files included: every markdown file, and
--              plain-text files under docs/ or issues/ or named README.
--   source  -- program source: the extensions below, a few build files known
--              by name, and extension-less files that open with a #! line.
--
-- Left out entirely, in this order (the first rule that matches decides):
--   vendored   -- someone else's work (see below); counted apart, for the record
--   llm-transcripts/ -- the conversations, measured by the first half
--   docs/HTML/ -- a generated copy of the docs; counting it would count them twice
--   notes/     -- (not left out: taken here, before the next rule)
--   input/, output/ -- what a project reads and what it produces
--   backups/, archives/ -- copies, the same rule the project census uses
--   source/    -- an upstream clone kept by the upstream-patch system
--
-- A file whose exact contents appear more than once (a copy kept in two
-- places) is counted once, in the most personal pile it landed in:
-- notes, then docs, then source.
--
-- What "someone else's work" means follows the repository's COPYRIGHT file,
-- whose rule is: walk up to the nearest licence file, and read the file's own
-- header too. So:
--   * a directory holding a licence file that names a copyright holder other
--     than the owner (or carries a permissive grant such as MIT's "Permission
--     is hereby granted") is vendored, with everything under it;
--   * a source file whose first lines carry such a notice is vendored;
--   * the repository's top-level libs/ is vendored: the census already calls
--     it the shared third-party shelf.
-- Not the rule: "every libs/ folder is vendored". Most projects' libs/ hold
-- code written here (vulkan-compute, sd-image-parts, the shared scripts/libs/),
-- so the evidence-based rule above is used instead.
local repo_rules = {
    skipped_segments = { input = true, output = true, backups = true,
                         archives = true, archive = true, source = true },
    vendored_top_level = { libs = true },
    -- Folders package managers fill with other people's code, wherever they sit.
    vendored_segments = { luarocks = true, node_modules = true, vendor = true,
                          third_party = true, ["third-party"] = true,
                          ["site-packages"] = true },
    doc_extensions = { md = true, markdown = true },
    doc_text_folders = { docs = true, issues = true },
    source_extensions = {
        lua = true, fnl = true, c = true, h = true, cc = true, cpp = true, cxx = true,
        hpp = true, hh = true, sh = true, bash = true, zsh = true, py = true,
        rs = true, js = true, mjs = true, ts = true, go = true, java = true,
        kt = true, cs = true, rb = true, pl = true, php = true, zig = true,
        nim = true, s = true, S = true, asm = true, glsl = true, vert = true,
        frag = true, comp = true, wgsl = true, hlsl = true, cl = true, cu = true,
        html = true, css = true, awk = true, sql = true, el = true, scm = true,
        lisp = true, hs = true, ml = true, swift = true, cmake = true, mk = true,
        vim = true, j = true,
    },
    source_names = { Makefile = true, makefile = true, ["CMakeLists.txt"] = true,
                     Dockerfile = true, ["meson.build"] = true },
    licence_file = { "^[Ll][Ii][Cc][Ee][Nn][CcSs][Ee]", "^[Cc][Oo][Pp][Yy][Ii][Nn][Gg]" },
    -- A notice line holding any of these is not a foreign claim: the owner's
    -- own name, the FSF's copyright on the GNU licence text itself, and the
    -- fill-in-the-blanks template at the end of that text.
    not_foreign = { "gabrilend", "Free Software Foundation", "<year>", "<name of author>" },
    foreign_notices = {
        "[Cc]opyright%s*%(?[Cc]?%)?%s*%d%d%d%d",
        "[Cc]opyright%s*%([Cc]%)%s*%S",
        "©%s*%d%d%d%d",
        "Permission is hereby granted",
        "Licensed under the Apache",
        "The MIT License",
        "Created/distributed by",
    },
    header_lines = 60,
}
-- }}}

-- {{{ Utility Functions

-- {{{ local function read_command()
local function read_command(command)
    local pipe = io.popen(command)
    if not pipe then error("could not run: " .. command, 0) end
    local lines = {}
    for line in pipe:lines() do
        if line ~= "" then lines[#lines + 1] = line end
    end
    pipe:close()
    return lines
end
-- }}}

-- {{{ local function read_whole()
local function read_whole(path)
    local handle = io.open(path, "rb")
    if not handle then error("cannot read " .. path, 0) end
    local text = handle:read("*a")
    handle:close()
    return text
end
-- }}}

-- {{{ local function normalise()
-- One space for every run of whitespace, none at the ends. The exporter wraps
-- lines at its own width, and a wrap must not change what is counted or keyed.
local function normalise(text)
    return (text:gsub("%s+", " "):gsub("^ ", ""):gsub(" $", ""))
end
-- }}}

-- {{{ local function characters()
-- Characters in normalised text: UTF-8 code points, which is the byte count
-- less the continuation bytes (0x80-0xBF) that carry multi-byte characters.
local function characters(text)
    local normalised = normalise(text)
    local _, continuations = normalised:gsub("[\128-\191]", "")
    return #normalised - continuations
end
-- }}}

-- {{{ local function hash64()
-- A 64-bit key as sixteen hex digits: two 32-bit FNV-1a passes with different
-- starting values. Workers hand keys to the merger as hashes rather than whole
-- texts; at a few tens of thousands of turns, a 64-bit collision is not a
-- practical concern (a 32-bit one would be, at about one chance in a hundred).
local function hash64(text)
    local low, high = 0x811c9dc5, 0x050c5d1f
    for index = 1, #text do
        local byte = text:byte(index)
        low = bit.tobit(bit.bxor(low, byte) * 16777619)
        high = bit.tobit(bit.bxor(high, byte) * 16777619)
    end
    return bit.tohex(high) .. bit.tohex(low)
end
-- }}}

-- }}}

-- {{{ Classifying a user turn

-- {{{ local function matches_any()
local function matches_any(text, patterns)
    for _, pattern in ipairs(patterns) do
        if text:find(pattern) then return true end
    end
    return false
end
-- }}}

-- {{{ local function is_log_line()
-- A line shaped like a log line or like pasted program output. Program-output
-- shapes are exact enough to decide alone; the log shapes include one loose
-- shape (a short capital word) that needs the level check below.
local function is_log_line(line)
    if matches_any(line, config.output_line_shapes) then return true end
    if not matches_any(line, config.log_line_shapes) then return false end
    -- The bracketed-level shape is loose (any short capital word); only real
    -- log levels count, so an ordinary shouted word in prose is not a log.
    local level = line:match("^%s*%[?(%u%u%u%u?%u?%u?%u?)%]?:? ")
    if level and not line:find("[%w_%-%./]+%.%a+:%d+:") and not line:find("^%s*%[?%d") then
        return config.log_line_levels[level] == true
    end
    return true
end
-- }}}

-- {{{ local function blocks_of()
-- A user turn as blocks: each fenced code block is one block, and so is each
-- run of lines between blank lines outside a fence.
local function blocks_of(text)
    local blocks, current, fenced = {}, {}, false
    local function close_block()
        if #current > 0 then blocks[#blocks + 1] = current end
        current = {}
    end
    for line in (text .. "\n"):gmatch("([^\n]*)\n") do
        if line:match("^%s*```") then
            if fenced then
                current[#current + 1] = line
                close_block()
                fenced = false
            else
                close_block()
                current[#current + 1] = line
                fenced = true
            end
        elseif not fenced and line:match("^%s*$") then
            close_block()
        else
            current[#current + 1] = line
        end
    end
    close_block()
    return blocks
end
-- }}}

-- {{{ local function is_pasted_log()
-- Two paths to "log": a strong signature anywhere in the block, or half or more
-- of its non-empty lines shaped like log lines. A block of prose that mentions
-- an error in passing fails both and stays the person's.
local function is_pasted_log(block)
    local lines, log_like = 0, 0
    for _, line in ipairs(block) do
        if not line:match("^%s*```") and not line:match("^%s*$") then
            if matches_any(line, config.strong_signatures) then return true end
            lines = lines + 1
            if is_log_line(line) then log_like = log_like + 1 end
        end
    end
    return lines > 0 and log_like * 2 >= lines
end
-- }}}

-- {{{ local function reads_as_prose()
-- Does a block contain a sentence? Three paths to yes:
--   it ends in a question mark ("Why?", "Any idea?") -- logs report, people ask
--   it holds six plain words in a row
--   something ends a sentence (". " or a final ".", "?", "!", ":") after a run
--   of at least three ordinary words
local function reads_as_prose(block)
    local text = normalise(table.concat(block, " "))
    if text:find("%a%?$") then return true end
    -- Six plain words in a row is someone talking, punctuated or not; a log
    -- line breaks its words with =, :, /, quotes or digits long before six.
    if text:find("%a+ %a+ %a+ %a+ %a+ %a+") then return true end
    if not text:find("%a+ %a+ %a+") then return false end
    return text:find("[%.%?!:] ") ~= nil or text:find("[%.%?!:]$") ~= nil
end
-- }}}

-- {{{ local function split_typed()
-- Human prose of a turn into typed characters and pasted-log characters.
--
-- The exporter re-wraps long lines and sets the pieces apart with blank lines,
-- so one pasted log line can arrive as several paragraphs whose later pieces
-- ("from", "runner.vram=...") look like nothing on their own. A log therefore
-- spreads to its neighbours, by two rules applied until nothing changes:
--   a block right after a log that is not a sentence -> log (a wrapped tail)
--   a short block (under 60 characters) between two  -> log (a label inside
--   log blocks                                          the dump, "The output
--                                                       was:", say)
-- A sentence outside a log's span stops the spread, so "the output looked like
-- this:" before a log, and the question after it, stay the person's; so does
-- a full paragraph between two quoted excerpts, which is the person replying.
-- The cost: a short remark between two pasted logs is set aside with them.
local function split_typed(text)
    local blocks = blocks_of(text)
    local is_log = {}
    for index, block in ipairs(blocks) do is_log[index] = is_pasted_log(block) end
    local changed = true
    while changed do
        changed = false
        for index = 2, #blocks do
            if not is_log[index] and is_log[index - 1] then
                -- Only a short label counts as inside a dump; a paragraph
                -- between two quoted excerpts is the person replying to them.
                local sandwiched = is_log[index + 1] == true
                    and characters(table.concat(blocks[index], " ")) < 60
                if sandwiched or not reads_as_prose(blocks[index]) then
                    is_log[index] = true
                    changed = true
                end
            end
        end
    end

    local typed, pasted = 0, 0
    for index, block in ipairs(blocks) do
        local size = characters(table.concat(block, "\n"))
        if is_log[index] then
            -- The person's lead-in sometimes shares the paragraph with the
            -- paste ("...available context space.time=2025-11-16..."). The
            -- lines before the first log-shaped line stay theirs when they
            -- read as a sentence; otherwise the whole block is the paste.
            local lead = {}
            for _, line in ipairs(block) do
                if is_log_line(line) or matches_any(line, config.strong_signatures) then break end
                lead[#lead + 1] = line
            end
            local kept = (#lead > 0 and #lead < #block and reads_as_prose(lead))
                and characters(table.concat(lead, "\n")) or 0
            typed = typed + kept
            pasted = pasted + size - kept
        else
            typed = typed + size
        end
    end
    return typed, pasted
end
-- }}}

-- {{{ local function classify_user_turn()
-- Returns the turn's characters as { human, machine, pasted, system }.
-- Who sat in the user's chair decides the first split (see ORIGINS below);
-- in a session the person typed into, the paths are, in order:
--   the model's own words        -> all machine (a compaction summary, a
--                                   message from another model session)
--   a tool-generated turn        -> all system
--   a wrapper around typed text  -> the typed part human (less pasted logs),
--                                   the rest system
--   anything else                -> human, less pasted logs
-- Any <system-reminder> spans are cut out first and counted as system.
local ORIGINS = {
    subagent = function(text, counts) counts.machine = characters(text); return true end,
    person   = function() return false end,
}
local function classify_user_turn(text, origin)
    local counts = { human = 0, machine = 0, pasted = 0, system = 0 }
    if ORIGINS[origin](text, counts) then return counts end

    local reminders = 0
    text = text:gsub("<system%-reminder>.-</system%-reminder>", function(span)
        reminders = reminders + characters(span)
        return " "
    end)
    counts.system = reminders

    local opening = normalise(text)
    if matches_any(opening, config.machine_openings) then
        counts.machine = characters(text)
        return counts
    end
    if matches_any(opening, config.system_openings) then
        counts.system = counts.system + characters(text)
        return counts
    end
    for _, wrapper in ipairs(config.typed_inside) do
        if opening:find(wrapper.whole) then
            local inside = text:match(wrapper.open .. "(.-)" .. wrapper.close) or ""
            local typed, pasted = split_typed(inside)
            counts.human, counts.pasted = typed, pasted
            counts.system = counts.system + characters(text) - characters(inside)
            return counts
        end
    end
    counts.human, counts.pasted = split_typed(text)
    return counts
end
-- }}}

-- }}}

-- Every worker's last line. The shell's `wait` reports success even when a
-- worker died part-way, so a missing last line is the only honest signal
-- that a share was not finished -- and an unfinished share would quietly
-- shrink every total.
local WORKER_FINISHED = "#finished"

-- {{{ local function records_of()
-- A worker's output, line by line, without its closing line.
local function records_of(output)
    local next_line = io.lines(output)
    return function()
        local line = next_line()
        if line == WORKER_FINISHED then return nil end
        return line
    end
end
-- }}}

-- {{{ Parsing transcripts (the worker's job)

-- {{{ local function parse_transcript()
-- Walks one transcript and calls emit(record) once per turn instance. A turn
-- instance is one user turn in one place in one file, with every assistant
-- response that follows it before the next user turn summed onto it (the
-- exporter splits long responses into "(continued)" parts across separators).
--
-- Each user turn is keyed by its own normalised text and the two user turns
-- before it in the same conversation. Every copy of a conversation, in any
-- file, at any level of detail, produces the same keys; the same "continue"
-- in two conversations does not. The key carries its origin's initial, so a
-- model-written prompt is never merged with a person's message.
local function parse_transcript(path, emit)
    local text = read_whole(path)
    local role, lines = nil, {}
    local origin = "person"
    local previous, before_previous = "", ""
    local instance = nil   -- the open turn instance, until the next user turn

    local function close_instance()
        if instance then emit(instance) end
        instance = nil
    end

    -- Two origins: a session id "agent-…" is a sub-agent wherever it is
    -- saved; every other session is the person's (see the note in the configuration on
    -- why an agent-named file is not evidence of a script).
    local function start_conversation(session_id)
        close_instance()
        origin = session_id:match("^agent%-") and "subagent" or "person"
        previous, before_previous = "", ""
    end

    -- {{{ local function flush()
    local function flush()
        local body = table.concat(lines, "\n")
        lines = {}
        if role == "user" then
            local normalised = normalise(body)
            -- An empty user turn is an export artifact, not a message; some
            -- renderings keep it and some drop it, so it stays out of the chain.
            if normalised == "" then return end
            close_instance()
            local key = hash64(origin:sub(1, 1) .. "\1" .. before_previous .. "\1" ..
                               previous .. "\1" .. normalised)
            before_previous, previous = previous, normalised
            local counts = classify_user_turn(body, origin)
            instance = { key = key, human = counts.human, machine = counts.machine,
                         pasted = counts.pasted, system = counts.system, answer = 0 }
        elseif role == "assistant" then
            local size = characters(body)
            if size == 0 then return end
            if not instance then
                -- A response with no user turn before it in this conversation
                -- (a continuation that opens a file): keyed by its own text.
                instance = { key = hash64("O\1" .. normalise(body)), human = 0,
                             machine = 0, pasted = 0, system = 0, answer = 0 }
            end
            instance.answer = instance.answer + size
        end
    end
    -- }}}

    for line in (text .. "\n"):gmatch("([^\n]*)\n") do
        local session = line:match("^# Conversation Summary:%s*(%S*)")
        if session then
            flush(); role = nil
            start_conversation(session)
        elseif line:match("^### User Request %d+") then
            flush(); role = "user"
        elseif line:match("^### Assistant Response %d+") then
            flush(); role = "assistant"
        elseif line == config.separator then
            flush(); role = nil
        elseif matches_any(line, config.boundaries) then
            -- A conversation heading ends the open turn even without a
            -- separator before it: the recursive exports (v1..v5) start each
            -- embedded conversation straight after the last response, and
            -- that response would otherwise swallow the next conversation.
            flush(); role = nil
            start_conversation("")
        elseif role then
            lines[#lines + 1] = line
        end
    end
    flush()
    close_instance()
end
-- }}}

-- {{{ local function run_worker()
-- One worker: reads its share of file paths, parses each, and writes one
-- tab-separated record per turn instance to its output file:
--   key  human  machine  pasted  system  answer
local function run_worker(list_path, out_path)
    local out = assert(io.open(out_path, "wb"))
    local function emit(record)
        out:write(string.format("%s\t%d\t%d\t%d\t%d\t%d\n", record.key, record.human,
            record.machine, record.pasted, record.system, record.answer))
    end
    for path in io.lines(list_path) do
        parse_transcript(path, emit)
    end
    out:write(WORKER_FINISHED, "\n")
    out:close()
end
-- }}}

-- }}}

-- {{{ Counting the repository's files

-- {{{ local function names_someone_else()
-- Does this text (a licence file, or a source file's opening lines) carry a
-- notice that someone other than the owner holds the rights? Line by line: a
-- line matching a foreign-notice shape counts unless it also carries one of
-- the not-foreign marks.
local function names_someone_else(text, line_limit)
    local seen = 0
    for line in (text .. "\n"):gmatch("([^\n]*)\n") do
        seen = seen + 1
        if line_limit and seen > line_limit then break end
        if matches_any(line, repo_rules.foreign_notices) then
            local ours = false
            for _, mark in ipairs(repo_rules.not_foreign) do
                if line:find(mark, 1, true) then ours = true; break end
            end
            if not ours then return true end
        end
    end
    return false
end
-- }}}

-- {{{ local function tracked_files()
-- Every path git tracks, relative to DIR. Read NUL-separated so that names
-- git would otherwise quote (spaces, accents) arrive exactly as they are.
local function tracked_files()
    local pipe = io.popen(string.format("git -C %q ls-files -z", DIR))
    if not pipe then error("could not list tracked files in " .. DIR, 0) end
    local listing = pipe:read("*a")
    pipe:close()
    local files = {}
    for path in listing:gmatch("([^%z]+)%z") do files[#files + 1] = path end
    return files
end
-- }}}

-- {{{ local function vendored_directories()
-- The folders the COPYRIGHT rule hands to someone else: each one holding a
-- tracked licence file that names another rights holder. The repository's
-- own root licence is the owner's by definition and is not read.
--
-- Also a web page saved from a browser, which is someone else's page: the
-- browser writes "Title.html" beside a "Title_files/" folder of its parts, so
-- a tracked path inside an "X_files/" folder marks that folder and the X.html
-- beside it. (Keyed in the same table; a file key is matched exactly.)
local function vendored_directories(files)
    local vendored = {}
    for _, path in ipairs(files) do
        local page_folder, page_name = path:match("^(.-)([^/]+)_files/")
        if page_folder then
            vendored[page_folder .. page_name .. "_files"] = true
            vendored[page_folder .. page_name .. ".html"] = true
        end
        local folder, name = path:match("^(.*)/([^/]+)$")
        if folder and matches_any(name, repo_rules.licence_file) then
            local handle = io.open(DIR .. "/" .. path, "rb")
            if handle then
                local text = handle:read("*a")
                handle:close()
                if names_someone_else(text) then vendored[folder] = true end
            end
        end
    end
    return vendored
end
-- }}}

-- {{{ local function classify_path()
-- Which pile a tracked path belongs to, from its path alone, or nil when it is
-- left out. "maybe_source" is an extension-less file that becomes source only
-- if it opens with #!, which the worker checks. The order is the order in the
-- Repository rules comment above; each branch notes what it decides.
local function classify_path(path, vendored)
    local segments = {}
    for segment in path:gmatch("[^/]+") do segments[#segments + 1] = segment end
    local name = segments[#segments]

    -- someone else's work: under a vendored folder, the top-level shelf, or
    -- a package manager's folder
    if repo_rules.vendored_top_level[segments[1]] and #segments > 1 then return "vendored" end
    if vendored[path] then return "vendored" end   -- a saved page's own .html
    for depth = 1, #segments - 1 do
        if vendored[table.concat(segments, "/", 1, depth)] then return "vendored" end
        if repo_rules.vendored_segments[segments[depth]] then return "vendored" end
    end

    -- a .bak file is a copy of something counted elsewhere
    if name:find(".bak", 1, true) then return nil end

    local in_notes, skipped, in_doc_folder = false, false, false
    for depth = 1, #segments - 1 do
        local segment = segments[depth]
        -- the conversations (and their backup folders, llm-transcripts-backup/),
        -- and the generated HTML copy of the docs: never
        if segment:find("^llm%-transcripts") then return nil end
        if segment == "HTML" and segments[depth - 1] == "docs" then return nil end
        if segment == "notes" then in_notes = true end
        if repo_rules.skipped_segments[segment] then skipped = true end
        if repo_rules.doc_text_folders[segment] then in_doc_folder = true end
    end
    -- notes win over input/ (hand-written poems kept as a project's input)
    if in_notes then return "notes" end
    if skipped then return nil end

    local extension = name:match("%.([^%./]+)$")
    if extension and repo_rules.doc_extensions[extension:lower()] then return "docs" end
    if extension == "txt" and (in_doc_folder or name:match("^README")) then return "docs" end
    if repo_rules.source_names[name] then return "source" end
    if extension and repo_rules.source_extensions[extension] then return "source" end
    -- a leading dot is a hidden file, not an extension-less script
    if not extension and not name:match("^%.") then return "maybe_source" end
    return nil
end
-- }}}

-- {{{ local function count_file()
-- One file's pile, content hash and character count, or nil when reading it
-- shows it does not belong after all. Four late decisions need the contents:
--   a NUL byte in the first 8 KB -> binary, left out
--   extension-less without #!   -> not a script, left out
--   a document holding exported conversation turns -> left out
--   source with a foreign notice in its opening lines -> vendored
local function count_file(category, path)
    local handle = io.open(DIR .. "/" .. path, "rb")
    if not handle then return nil end   -- a tracked file deleted from disk
    local text = handle:read("*a")
    handle:close()
    -- A tracked path that reads as nothing is a directory: git records a
    -- nested repository (a gitlink) or a symlink to a folder as one entry.
    -- Its contents are some other repository's, so it is left out.
    if text == nil then return nil end
    if text:sub(1, 8192):find("%z") then return nil end
    if category == "maybe_source" then
        if text:sub(1, 2) ~= "#!" then return nil end
        category = "source"
    end
    -- A document or note holding exported conversation turns is transcript
    -- material filed somewhere else (a README that swallowed a backup pack, a
    -- notes/conversations/ record). The transcript half measures conversations
    -- turn by turn; counting the file here too would count them twice.
    if (category == "docs" or category == "notes")
        and text:find("\n### User Request %d") and text:find("\n### Assistant Response %d") then
        return nil
    end
    if category == "source" and names_someone_else(text, repo_rules.header_lines) then
        category = "vendored"
    end
    return category, hash64(text), characters(text)
end
-- }}}

-- {{{ local function run_count_worker()
-- One worker's share of the repository: reads "pile<TAB>path" lines, writes
--   pile  content-hash  characters  path
local function run_count_worker(list_path, out_path)
    local out = assert(io.open(out_path, "wb"))
    for line in io.lines(list_path) do
        local category, path = line:match("^([%w_]+)\t(.+)$")
        local final, hash, size = count_file(category, path)
        if final then
            out:write(string.format("%s\t%s\t%d\t%s\n", final, hash, size, path))
        end
    end
    out:write(WORKER_FINISHED, "\n")
    out:close()
end
-- }}}

-- }}}

-- {{{ Measuring (the parent's job)

-- {{{ local function transcript_files()
-- Every markdown file in any llm-transcripts/ folder, skipping git's own
-- store, the transcript keepers' .patches/ records, and .bak copies.
local function transcript_files()
    return read_command(string.format(
        "find %q -path '*/.git' -prune -o -path '*/.patches' -prune -o " ..
        "-path '*/llm-transcripts/*' -type f -name '*.md' -print | sort", DIR))
end
-- }}}

-- {{{ local function scratch_directory()
-- A fresh folder in the RAM tier for this run's worker lists and outputs.
-- The shared library rebuilds the tier first, since a reboot empties RAM.
local function scratch_directory()
    local ensured = os.execute(string.format(
        "bash -c 'source %q && ensure_ram_tiers %q' >&2", RAM_TIER_LIBRARY, PROJECT_HOME))
    if ensured ~= 0 and ensured ~= true then
        error("could not prepare the RAM tier for " .. PROJECT_HOME, 0)
    end
    local base = PROJECT_HOME .. "/tmp/shared-memory/measure-authorship"
    os.execute(string.format("mkdir -p %q", base))
    return read_command(string.format("mktemp -d %q", base .. "/run.XXXXXX"))[1]
end
-- }}}

-- {{{ local function run_in_parallel()
-- Deals the work lines round-robin into one share per worker, starts every
-- worker at once in the background (the given worker mode: --worker for
-- transcripts, --count-worker for the repository's files), waits for all of
-- them, and returns their output paths. Processes, because LuaJIT has no
-- threads; round-robin, because the lines arrive sorted by path and a few
-- very large files sit together.
local function run_in_parallel(work, worker_mode)
    local count = WORKER_COUNT or tonumber(read_command("nproc")[1])
    if count < 1 then error("need at least one worker", 0) end
    if count > #work then count = math.max(1, #work) end

    local scratch = scratch_directory()
    local shares, outputs, commands = {}, {}, {}
    for index = 1, count do
        shares[index] = assert(io.open(string.format("%s/share-%d.list", scratch, index), "wb"))
        outputs[index] = string.format("%s/share-%d.records", scratch, index)
    end
    for index, line in ipairs(work) do
        shares[(index - 1) % count + 1]:write(line, "\n")
    end
    for index = 1, count do
        shares[index]:close()
        commands[index] = string.format("luajit %q %s --dir=%q %q %q &", SCRIPT_PATH,
            worker_mode, DIR, string.format("%s/share-%d.list", scratch, index), outputs[index])
    end
    local status = os.execute(table.concat(commands, " ") .. " wait")
    if status ~= 0 and status ~= true then error("a worker failed", 0) end
    for _, output in ipairs(outputs) do
        local handle = io.open(output, "rb")
        if not handle then error("a worker wrote nothing: " .. output, 0) end
        local text = handle:read("*a")
        handle:close()
        if text:sub(-#WORKER_FINISHED - 1) ~= WORKER_FINISHED .. "\n" then
            error("a worker stopped before finishing its share (" .. output .. ")", 0)
        end
    end
    return outputs, scratch
end
-- }}}

-- {{{ local function merge()
-- Folds every worker's records by key. The person's side of a turn is the
-- same in every copy, so the first copy's is kept; the machine's answer
-- differs between renderings at different levels of detail, so the longest
-- is kept. Returns the totals.
local function merge(outputs, files_seen)
    local turns = {}
    local instances = 0
    for _, output in ipairs(outputs) do
        for line in records_of(output) do
            local key, human, machine, pasted, system, answer =
                line:match("^(%x+)\t(%d+)\t(%d+)\t(%d+)\t(%d+)\t(%d+)$")
            if not key then error("malformed worker record: " .. line, 0) end
            instances = instances + 1
            local turn = turns[key]
            if not turn then
                turns[key] = { human = tonumber(human), machine = tonumber(machine),
                               pasted = tonumber(pasted), system = tonumber(system),
                               answer = tonumber(answer) }
            elseif tonumber(answer) > turn.answer then
                turn.answer = tonumber(answer)
            end
        end
    end

    local totals = { human_characters = 0, machine_characters = 0,
                     excluded_paste_characters = 0, system_characters = 0,
                     turns_counted = 0, turn_copies_seen = instances,
                     transcripts_counted = files_seen }
    for _, turn in pairs(turns) do
        totals.turns_counted = totals.turns_counted + 1
        totals.human_characters = totals.human_characters + turn.human
        totals.machine_characters = totals.machine_characters + turn.machine + turn.answer
        totals.excluded_paste_characters = totals.excluded_paste_characters + turn.pasted
        totals.system_characters = totals.system_characters + turn.system
    end
    totals.machine_units = totals.machine_characters
    totals.machine_unit_name = "characters"
    -- Machine characters per human character. With nothing typed there is no
    -- ratio to state; zero says "nothing measured" rather than dividing by it.
    totals.ratio = totals.human_characters > 0
        and totals.machine_characters / totals.human_characters or 0
    return totals
end
-- }}}

-- {{{ local function merge_files()
-- Folds the workers' file records into pile totals. A content hash seen more
-- than once is one file kept in several places: counted once, in the most
-- personal pile any copy landed in (notes, then docs, then source, then
-- vendored). Returns the totals and every kept file, for the largest listing.
local PILE_RANK = { notes = 1, docs = 2, source = 3, vendored = 4 }
local function merge_files(outputs)
    local by_hash = {}
    local copies = 0
    for _, output in ipairs(outputs) do
        for line in records_of(output) do
            local pile, hash, size, path = line:match("^(%a+)\t(%x+)\t(%d+)\t(.+)$")
            if not pile or not PILE_RANK[pile] then error("malformed file record: " .. line, 0) end
            local kept = by_hash[hash]
            if kept then
                copies = copies + 1
                -- keep the more personal pile; on a tie, the earlier path, so
                -- the answer does not depend on which worker finished first
                if PILE_RANK[pile] < PILE_RANK[kept.pile]
                    or (PILE_RANK[pile] == PILE_RANK[kept.pile] and path < kept.path) then
                    kept.pile, kept.path = pile, path
                end
            else
                by_hash[hash] = { pile = pile, size = tonumber(size), path = path }
            end
        end
    end

    local totals = { notes_characters = 0, docs_characters = 0, source_characters = 0,
                     vendored_characters = 0, repo_files_counted = 0,
                     repo_duplicate_files = copies }
    local kept_files = {}
    for _, file in pairs(by_hash) do
        totals[file.pile .. "_characters"] = totals[file.pile .. "_characters"] + file.size
        totals.repo_files_counted = totals.repo_files_counted + 1
        kept_files[#kept_files + 1] = file
    end
    return totals, kept_files
end
-- }}}

-- {{{ local function measure_repository()
-- The repository half: list what git tracks, decide each path's pile, count
-- the files in parallel, merge.
local function measure_repository()
    local files = tracked_files()
    if #files == 0 then error("git tracks no files under " .. DIR, 0) end
    local vendored = vendored_directories(files)
    local work = {}
    for _, path in ipairs(files) do
        local pile = classify_path(path, vendored)
        if pile then work[#work + 1] = pile .. "\t" .. path end
    end
    local outputs, scratch = run_in_parallel(work, "--count-worker")
    local totals, kept_files = merge_files(outputs)
    os.execute(string.format("rm -r %q", scratch))
    return totals, kept_files
end
-- }}}

-- {{{ local function measure()
-- Both halves, and the four headline figures built from them:
--   human_written_total   = the person's transcript characters + notes
--   machine_written_total = the model's transcript characters
--   source_characters, docs_characters = the repository's piles
local function measure()
    local files = transcript_files()
    if #files == 0 then error("no transcripts found under " .. DIR, 0) end
    local outputs, scratch = run_in_parallel(files, "--worker")
    local totals = merge(outputs, #files)
    os.execute(string.format("rm -r %q", scratch))

    local repository, kept_files = measure_repository()
    for field, value in pairs(repository) do totals[field] = value end
    totals.human_written_total = totals.human_characters + totals.notes_characters
    totals.machine_written_total = totals.machine_characters
    return totals, kept_files
end
-- }}}

-- }}}

-- {{{ Rendering

-- {{{ local function with_commas()
local function with_commas(n)
    local grouped = tostring(n):reverse():gsub("(%d%d%d)", "%1,"):reverse()
    return (grouped:gsub("^,", ""))
end
-- }}}

-- {{{ local function render_terminal()
local function render_terminal(totals)
    local function row(label, value)
        print(string.format("  %-28s %14s characters", label, with_commas(value)))
    end
    print("The four figures:")
    row("human-written text", totals.human_written_total)
    row("machine-written text", totals.machine_written_total)
    row("source code in the tree", totals.source_characters)
    row("documents in the tree", totals.docs_characters)
    print("")
    print(string.format("From %d transcripts, %s distinct turns (%s copies seen):",
        totals.transcripts_counted, with_commas(totals.turns_counted),
        with_commas(totals.turn_copies_seen)))
    row("typed in conversation", totals.human_characters)
    row("written by the model", totals.machine_characters)
    print(string.format("  %-28s %14.2f", "machine per person (chat)", totals.ratio))
    row("set aside: pasted output", totals.excluded_paste_characters)
    row("set aside: tool-generated", totals.system_characters)
    print("")
    print(string.format("From %s tracked files (%s duplicate copies counted once):",
        with_commas(totals.repo_files_counted), with_commas(totals.repo_duplicate_files)))
    row("notes (the person's)", totals.notes_characters)
    row("set aside: vendored", totals.vendored_characters)
end
-- }}}

-- {{{ local function render_largest()
-- The biggest files in each pile, for checking that the rules put things
-- where they belong.
local function render_largest(kept_files, how_many)
    local piles = { "notes", "docs", "source", "vendored" }
    for _, pile in ipairs(piles) do
        local members = {}
        for _, file in ipairs(kept_files) do
            if file.pile == pile then members[#members + 1] = file end
        end
        table.sort(members, function(a, b) return a.size > b.size end)
        print(pile .. ":")
        for index = 1, math.min(how_many, #members) do
            print(string.format("  %12s  %s", with_commas(members[index].size), members[index].path))
        end
    end
end
-- }}}

-- {{{ local function render_json()
local function render_json(totals)
    local fields = { "human_written_total", "machine_written_total",
                     "source_characters", "docs_characters", "notes_characters",
                     "human_characters", "machine_units", "machine_unit_name", "ratio",
                     "transcripts_counted", "excluded_paste_characters",
                     "system_characters", "turns_counted", "turn_copies_seen",
                     "vendored_characters", "repo_files_counted", "repo_duplicate_files" }
    print("{")
    for index, field in ipairs(fields) do
        local value = totals[field]
        local shown = type(value) == "string" and string.format("%q", value)
            or (field == "ratio" and string.format("%.4f", value) or tostring(value))
        print(string.format('  "%s": %s%s', field, shown, index < #fields and "," or ""))
    end
    print("}")
end
-- }}}

-- }}}

-- {{{ Entry
local function main()
    local mode = mode_arguments[1] or "--terminal"
    local modes = {
        ["--worker"] = function()
            run_worker(mode_arguments[2], mode_arguments[3])
        end,
        ["--count-worker"] = function()
            run_count_worker(mode_arguments[2], mode_arguments[3])
        end,
        ["--terminal"] = function() render_terminal((measure())) end,
        ["--json"] = function() render_json((measure())) end,
        ["--largest"] = function()
            local _, kept_files = measure_repository()
            render_largest(kept_files, tonumber(mode_arguments[2]) or 15)
        end,
    }
    local run = modes[mode]
    if not run then
        io.stderr:write("unknown mode: " .. mode .. "\nexpected --terminal or --json\n")
        os.exit(2)
    end
    run()
end

local ok, failure = xpcall(main, function(message)
    if type(message) == "string" and not message:match("^[^\n]*:%d+:") then
        return message
    end
    return debug.traceback(message, 2)
end)
if not ok then
    io.stderr:write("measure-authorship: " .. tostring(failure) .. "\n")
    os.exit(1)
end
-- }}}
