#!/usr/bin/env luajit
-- 027-test-blob.lua
--
-- Packs a model, reads it back, and compares every tensor byte for byte. Also
-- checks that the reader refuses the things it must refuse -- a truncated
-- blob, a wrong version, something that is not a blob at all.
--
-- For a general: this proves that what goes into the model file comes back
-- out unchanged, and that a damaged file is caught rather than believed.
--
-- The refusals matter as much as the round trip. A reader that accepts a
-- broken blob does not fail -- it hands the arithmetic somebody else's
-- numbers, and the machine merely thinks badly forever, and nobody suspects
-- the right thing.
--
-- usage:
--   luajit 027-test-blob.lua [--dir ROOT]

-- {{{ DIR -- the project root, hard-coded, overridable by --dir
local DIR = "/mnt/mtwo/programming/ai-stuff/every-software-image-able"
-- }}}

-- {{{ local function say(text)
local function say(text)
  io.write(text, "\n")
  io.flush()
end
-- }}}

-- {{{ local function run_one(command)
local function run_one(command)
  local ok, _, code = os.execute(command)
  return (ok == true or ok == 0), code
end
-- }}}

-- {{{ local function capture(command)
local function capture(command)
  local pipe = io.popen(command .. " 2>&1")
  if not pipe then return "", false end
  local text = pipe:read("*a")
  local ok = pipe:close()
  return text, (ok == true or ok == 0)
end
-- }}}

-- {{{ local function pseudo_random(seed)
-- A generator seeded from one number, which is how the machine's own
-- randomness works (issue 104): the seed is carried, the stream is derived.
-- Used here so the same test produces the same bytes every run, and so a
-- comparison failure means something rather than being noise.
local function pseudo_random(seed)
  local state = seed
  return function()
    state = (state * 1103515245 + 12345) % 2147483648
    return state % 256
  end
end
-- }}}

-- {{{ local function write_description(path, tensors_wanted)
local function write_description(path, tensors_wanted)
  -- A model description small enough to test with and shaped like a real one.
  -- The data functions generate bytes from a seed rather than holding them,
  -- so the description stays small and the expected bytes stay recomputable.
  local lines = {
    "-- generated by 027-test-blob.lua; a small model shaped like a real one",
    "local function bytes_from(seed)",
    "  return function(count)",
    "    local state, parts = seed, {}",
    "    for _ = 1, count do",
    "      state = (state * 1103515245 + 12345) % 2147483648",
    "      parts[#parts + 1] = string.char(state % 256)",
    "    end",
    "    return table.concat(parts)",
    "  end",
    "end",
    "",
    "return {",
    "  shape = { layers = 4, hidden = 64, heads = 4, head_width = 16,",
    "            kv_heads = 2, feedforward = 176, vocabulary = 32, context = 128 },",
    "  tensors = {",
  }

  for _, tensor in ipairs(tensors_wanted) do
    lines[#lines + 1] = string.format(
      "    { name = %q, precision = %q, shape = { %s }, scale = %s, data = bytes_from(%d) },",
      tensor.name, tensor.precision, table.concat(tensor.shape, ", "),
      tostring(tensor.scale or 0), tensor.seed)
  end

  lines[#lines + 1] = "  },"
  lines[#lines + 1] = "  tokens = {"
  -- a vocabulary with the awkward cases in it: a space, a newline, a byte
  -- above 127, single letters. Tokenizers differ from each other exactly
  -- here, and a subtly wrong one produces a model that seems mildly stupid.
  local tokens = { "<end>", " ", "\n", "the", "a", "\xc3\xa9", "!", "th", "e", "in" }
  for _, token in ipairs(tokens) do
    lines[#lines + 1] = string.format("    %q,", token)
  end
  for slot = #tokens + 1, 32 do
    lines[#lines + 1] = string.format("    %q,", "t" .. slot)
  end
  lines[#lines + 1] = "  },"
  lines[#lines + 1] = "  merges = { {7, 8}, {3, 4}, {1, 2} },"
  lines[#lines + 1] = "}"

  local handle = io.open(path, "w")
  if not handle then return false end
  handle:write(table.concat(lines, "\n"), "\n")
  handle:close()
  return true
end
-- }}}

-- {{{ local function expected_bytes(seed, count)
local function expected_bytes(seed, count)
  local next_byte = pseudo_random(seed)
  local parts = {}
  for _ = 1, count do parts[#parts + 1] = string.char(next_byte()) end
  return table.concat(parts)
end
-- }}}

-- {{{ main
local index = 1
while index <= #arg do
  if arg[index] == "--dir" then index = index + 1 ; DIR = arg[index] end
  index = index + 1
end

run_one("mkdir -p /tmp/every-software-image-able")
run_one("mkdir -p /dev/shm/every-software-image-able")
run_one("ln -sfn /tmp/every-software-image-able " .. DIR .. "/tmp")
run_one("ln -sfn /dev/shm/every-software-image-able /tmp/every-software-image-able/shared-memory")
local work = DIR .. "/tmp/shared-memory/blob-test"
run_one("mkdir -p " .. work)

local format = dofile(DIR .. "/src/024-blob-format.lua")

-- one tensor per precision the format defines, so none of them goes untested.
local tensors_wanted = {
  { name = "embedding",      precision = "f32", shape = { 32, 64 },  seed = 11 },
  { name = "layer0.attn.q",  precision = "f16", shape = { 64, 64 },  seed = 22 },
  { name = "layer0.attn.k",  precision = "i8",  shape = { 64, 32 },  seed = 33, scale = 0.015625 },
  { name = "layer0.feedfwd", precision = "q40", shape = { 64, 176 }, seed = 44 },
  { name = "output.norm",    precision = "f32", shape = { 64 },      seed = 55 },
}

local description = work .. "/small-model.lua"
local blob = work .. "/small-model.blob"

say("")
say("  the blob, packed and read back")
say("  " .. string.rep("-", 58))
say("")

local passed, failed = 0, 0

-- {{{ local function check(what, ok, detail)
local function check(what, ok, detail)
  if ok then
    passed = passed + 1
    say(string.format("  %-46s ok", what))
  else
    failed = failed + 1
    say(string.format("  %-46s WRONG", what))
    if detail and detail ~= "" then
      for line in tostring(detail):gmatch("[^\n]+") do say("      " .. line) end
    end
  end
end
-- }}}

-- {{{ pack and read
write_description(description, tensors_wanted)

local pack_output, packed = capture("luajit " .. DIR .. "/src/025-pack-model.lua"
  .. " --from " .. description .. " --to " .. blob .. " --dir " .. DIR)
check("packs without complaint", packed, pack_output)

local read_output, readable = capture("luajit " .. DIR .. "/src/026-read-blob.lua "
  .. blob .. " --tensors --dir " .. DIR)
check("reads back without complaint", readable, read_output)

local found_count = select(2, read_output:gsub("bytes at", ""))
check("reader finds every tensor", found_count == #tensors_wanted,
      "found " .. found_count .. " of " .. #tensors_wanted)

check("no two tensors share a byte",
      read_output:find("no two tensors share a byte", 1, true) ~= nil,
      read_output:match("TENSORS SHARE BYTES:.*"))
-- }}}

-- {{{ every tensor's bytes, compared one at a time
local handle = io.open(blob, "rb")
local raw = handle and handle:read("*a") or ""
if handle then handle:close() end

-- walk the tensor table the way the engine will have to, rather than
-- trusting the packer's own idea of where things went. If these two ever
-- disagree, this test is the only thing that would notice.
local function u32_at(at)
  local a, b, c, d = raw:byte(at + 1, at + 4)
  if not d then return 0 end
  return a + b * 256 + c * 65536 + d * 16777216
end
local function u64_at(at) return u32_at(at) + u32_at(at + 4) * 4294967296 end

local field_at, cursor = {}, 0
for _, field in ipairs(format.HEADER) do
  field_at[field.name] = cursor
  cursor = cursor + field.size
end
local tensor_table = u64_at(field_at.tensor_table)
local entry_size = format.tensor_entry_size()
local data_offset_in_entry = format.NAME_BYTES + 4 + 4 + 32

local all_matched, mismatch_detail = true, nil
for index_of, wanted in ipairs(tensors_wanted) do
  local entry = tensor_table + (index_of - 1) * entry_size
  local offset = u64_at(entry + data_offset_in_entry)
  local bytes = u64_at(entry + data_offset_in_entry + 8)
  local found = raw:sub(offset + 1, offset + bytes)
  local expect = expected_bytes(wanted.seed, bytes)
  if found ~= expect then
    all_matched = false
    mismatch_detail = wanted.name .. " differs (" .. bytes .. " bytes at " .. offset .. ")"
    break
  end
end
check("every tensor's bytes survive the round trip", all_matched, mismatch_detail)

-- alignment is not decoration: a vectorised inner loop that must begin with
-- an unaligned step pays for it on every single row.
local aligned = true
for index_of = 1, #tensors_wanted do
  local entry = tensor_table + (index_of - 1) * entry_size
  if u64_at(entry + data_offset_in_entry) % 32 ~= 0 then aligned = false end
end
check("every tensor starts on a 32-byte boundary", aligned)
-- }}}

-- {{{ the refusals -- a reader that accepts a broken blob is worse than none
local truncated = work .. "/truncated.blob"
local out = io.open(truncated, "wb")
out:write(raw:sub(1, #raw - 64))
out:close()
local _, accepted_truncated = capture("luajit " .. DIR .. "/src/026-read-blob.lua "
  .. truncated .. " --dir " .. DIR)
check("refuses a truncated blob", not accepted_truncated)

local wrong_version = work .. "/wrong-version.blob"
out = io.open(wrong_version, "wb")
out:write(raw:sub(1, 4) .. string.char(99, 0, 0, 0) .. raw:sub(9))
out:close()
local _, accepted_version = capture("luajit " .. DIR .. "/src/026-read-blob.lua "
  .. wrong_version .. " --dir " .. DIR)
check("refuses a format version it does not know", not accepted_version)

local not_a_blob = work .. "/not-a-blob.bin"
out = io.open(not_a_blob, "wb")
out:write(string.rep("nonsense", 64))
out:close()
local _, accepted_rubbish = capture("luajit " .. DIR .. "/src/026-read-blob.lua "
  .. not_a_blob .. " --dir " .. DIR)
check("refuses something that is not a blob", not accepted_rubbish)
-- }}}

-- {{{ determinism -- same description, same bytes
local second = work .. "/small-model-again.blob"
capture("luajit " .. DIR .. "/src/025-pack-model.lua --from " .. description
        .. " --to " .. second .. " --dir " .. DIR)
local again = io.open(second, "rb")
local raw_again = again and again:read("*a") or ""
if again then again:close() end
check("the same description packs to the same bytes", raw == raw_again,
      "reproducibility is a build-time property, and it starts here")
-- }}}

say("")
say("  " .. string.rep("-", 58))
say("  " .. passed .. " of " .. (passed + failed) .. " as expected")
say("")

run_one("mkdir -p " .. DIR .. "/output")
local goodbye = io.open(DIR .. "/output/goodbye", "w")
if goodbye then
  goodbye:write("blob round trip: " .. passed .. " of " .. (passed + failed)
                .. " as expected\ngoodbye\n")
  goodbye:close()
end

os.exit(failed == 0 and 0 or 1)
-- }}}
