#!/usr/bin/env luajit
-- 036-make-fixture.lua
--
-- Packs a small model, runs a forward pass over it, and writes down exactly
-- what came out. That written-down answer is the fixture: the thing every
-- assembly implementation is measured against, on every architecture, forever.
--
-- For a general: this produces a known question and its known answer. Any
-- faster or more obscure version of the arithmetic is correct exactly when it
-- reproduces this answer, and no other test is needed to say so.
--
-- WHY THE WEIGHTS ARE RANDOM. A fixture does not need a model that says
-- anything sensible -- it needs one that is the same every time. Weights drawn
-- from a fixed seed are meaningless and perfectly reproducible, which is all
-- that is being asked of them. Real meaning arrives with a real model, and
-- nothing about this test changes when it does.
--
-- usage:
--   luajit 036-make-fixture.lua [--dir ROOT] [--tokens N]

-- {{{ DIR -- the project root, hard-coded, overridable by --dir
local DIR = "/mnt/mtwo/programming/ai-stuff/every-software-image-able"
-- }}}

local ffi = require("ffi")

-- {{{ local function say(text)
local function say(text)
  io.write(text, "\n")
  io.flush()
end
-- }}}

-- {{{ local function die(text)
local function die(text)
  io.stderr:write("036-make-fixture: ", text, "\n")
  os.exit(1)
end
-- }}}

-- {{{ local function run_one(command)
local function run_one(command)
  local ok, _, code = os.execute(command)
  return (ok == true or ok == 0), code
end
-- }}}

-- {{{ local function drawn_from(seed)
-- A generator seeded from one number -- the same arrangement the machine's own
-- randomness uses (issue 104). Numbers land in a small range around zero,
-- which keeps a forward pass from producing values too large to compare
-- meaningfully.
local function drawn_from(seed)
  local state = seed
  return function()
    state = (state * 1103515245 + 12345) % 2147483648
    return (state / 2147483648) * 0.2 - 0.1
  end
end
-- }}}

-- {{{ local function write_description(path, shape, tensors)
local function write_description(path, shape, tensors)
  -- The description is generated rather than written, and the weights are
  -- generated from a seed rather than stored, so the whole model is a page of
  -- text that expands to the same bytes every time.
  local lines = {
    "-- generated by 036-make-fixture.lua -- a model with no meaning and no",
    "-- variation. Weights are drawn from a seed so the same description",
    "-- always packs to the same bytes.",
    "local function weights_from(seed)",
    "  return function(count)",
    "    local ffi = require('ffi')",
    "    local state = seed",
    "    local numbers = ffi.new('float[?]', count / 4)",
    "    for index = 0, count / 4 - 1 do",
    "      state = (state * 1103515245 + 12345) % 2147483648",
    "      numbers[index] = (state / 2147483648) * 0.2 - 0.1",
    "    end",
    "    return ffi.string(numbers, count)",
    "  end",
    "end",
    "",
    "return {",
    string.format("  shape = { layers = %d, hidden = %d, heads = %d, head_width = %d,",
                  shape.layers, shape.hidden, shape.heads, shape.head_width),
    string.format("            kv_heads = %d, feedforward = %d, vocabulary = %d, context = %d },",
                  shape.kv_heads, shape.feedforward, shape.vocabulary, shape.context),
    "  tensors = {",
  }

  -- a different seed per tensor, so no two tensors hold the same numbers --
  -- an implementation that reads the wrong one then fails rather than
  -- coincidentally agreeing.
  for index, tensor in ipairs(tensors) do
    lines[#lines + 1] = string.format(
      "    { name = %q, precision = \"f32\", shape = { %s }, data = weights_from(%d) },",
      tensor.name, table.concat(tensor.shape, ", "), 1000 + index * 37)
  end

  lines[#lines + 1] = "  },"

  -- a vocabulary, so the blob is complete even though the fixture does not
  -- exercise the tokenizer. A blob missing a section is a blob that tests a
  -- reader less thoroughly than a real one would.
  lines[#lines + 1] = "  tokens = {"
  for slot = 1, shape.vocabulary do
    lines[#lines + 1] = string.format("    %q,", "t" .. slot)
  end
  lines[#lines + 1] = "  },"
  lines[#lines + 1] = "  merges = { {3, 4}, {5, 6} },"
  lines[#lines + 1] = "}"

  local handle = io.open(path, "w") or die("cannot write " .. path)
  handle:write(table.concat(lines, "\n"), "\n")
  handle:close()
end
-- }}}

-- {{{ main
local token_count = 4
local index = 1
while index <= #arg do
  if arg[index] == "--dir" then
    index = index + 1 ; DIR = arg[index] or die("missing value after --dir")
  elseif arg[index] == "--tokens" then
    index = index + 1 ; token_count = tonumber(arg[index]) or die("--tokens wants a number")
  else
    die("unknown option: " .. arg[index])
  end
  index = index + 1
end

run_one("mkdir -p /tmp/every-software-image-able")
run_one("mkdir -p /dev/shm/every-software-image-able")
run_one("ln -sfn /tmp/every-software-image-able " .. DIR .. "/tmp")
run_one("ln -sfn /dev/shm/every-software-image-able /tmp/every-software-image-able/shared-memory")
local work = DIR .. "/tmp/shared-memory/fixture"
run_one("mkdir -p " .. work)

local shapes = dofile(DIR .. "/src/034-model-shapes.lua")
local format = dofile(DIR .. "/src/024-blob-format.lua")
local reference = dofile(DIR .. "/src/035-reference-forward.lua")

local shape = shapes.SMALL
local tensors = shapes.tensors(shape)

local description = work .. "/fixture-model.lua"
local blob_path = work .. "/fixture-model.blob"

write_description(description, shape, tensors)

local packed = run_one("luajit " .. DIR .. "/src/025-pack-model.lua --from " .. description
                       .. " --to " .. blob_path .. " --dir " .. DIR .. " > /dev/null")
if not packed then die("the model would not pack") end

local handle = io.open(blob_path, "rb") or die("cannot read " .. blob_path)
local blob = handle:read("*a")
handle:close()

local model = reference.load(blob, format)
local cache = reference.new_cache(model.shape)

say("")
say("  a known question, and the answer it must always give")
say("  " .. string.rep("-", 58))
say("")
say(string.format("  model   %d layers of %d, %d heads of %d (%d for keys)",
                  shape.layers, shape.hidden, shape.heads, shape.head_width, shape.kv_heads))
say(string.format("          feedforward %d, vocabulary %d, context %d",
                  shape.feedforward, shape.vocabulary, shape.context))
say(string.format("          %d weights across %d tensors, %d bytes packed",
                  shapes.weight_count(shape), #tensors, #blob))
say(string.format("          a full cache would be %d bytes",
                  shapes.cache_bytes(shape, 4)))
say("")

-- a fixed sequence of tokens, chosen to be nothing in particular. Position
-- matters as much as the token does, so the same token appears twice.
local prompt = { 1, 7, 7, 3 }
while #prompt < token_count do prompt[#prompt + 1] = (#prompt * 5) % shape.vocabulary end

local lines = {
  "-- 036-fixture.lua -- generated; do not edit.",
  "--",
  "-- The answer a forward pass gives on this model with this prompt. Any",
  "-- other implementation of the same arithmetic is correct exactly when it",
  "-- reproduces these numbers, and is wrong otherwise -- including a faster",
  "-- one, including one written in a different architecture's instructions.",
  "--",
  "-- Regenerate with 036-make-fixture.lua. If the numbers move, something",
  "-- changed in the arithmetic and the change was probably not intended.",
  "",
  "return {",
  string.format("  shape = { layers = %d, hidden = %d, heads = %d, head_width = %d,",
                shape.layers, shape.hidden, shape.heads, shape.head_width),
  string.format("            kv_heads = %d, feedforward = %d, vocabulary = %d, context = %d },",
                shape.kv_heads, shape.feedforward, shape.vocabulary, shape.context),
  "  prompt = { " .. table.concat(prompt, ", ") .. " },",
  "  logits = {",
}

for step, token in ipairs(prompt) do
  local position = step - 1
  local logits = reference.forward(model, cache, token, position)

  -- the whole row, not a summary. A fixture that records only a maximum
  -- passes an implementation that gets every other number wrong.
  local row = {}
  for slot = 0, shape.vocabulary - 1 do
    row[#row + 1] = string.format("%.9g", logits[slot])
  end

  lines[#lines + 1] = string.format("    -- token %d at position %d", token, position)
  lines[#lines + 1] = "    { " .. table.concat(row, ", ") .. " },"

  -- something readable to look at, since forty-eight numbers on a line are
  -- not something a person checks by eye.
  local best, best_slot = logits[0], 0
  for slot = 1, shape.vocabulary - 1 do
    if logits[slot] > best then best, best_slot = logits[slot], slot end
  end
  say(string.format("  step %d  token %-3d at position %d  ->  highest score %d (%.6f)",
                    step, token, position, best_slot, best))
end

lines[#lines + 1] = "  },"
lines[#lines + 1] = "}"

-- The fixture is kept rather than left in RAM. It is the one generated thing
-- in this project that must persist: an answer nobody can recompute without
-- the very implementation it exists to check.
run_one("mkdir -p " .. DIR .. "/assets")
local fixture_path = DIR .. "/assets/036-fixture.lua"
local out = io.open(fixture_path, "w") or die("cannot write " .. fixture_path)
out:write(table.concat(lines, "\n"), "\n")
out:close()

say("")
say("  model    " .. blob_path)
say("  fixture  " .. fixture_path)
say("")

run_one("mkdir -p " .. DIR .. "/output")
local goodbye = io.open(DIR .. "/output/goodbye", "w")
if goodbye then
  goodbye:write("fixture written: " .. #prompt .. " steps over "
                .. shape.vocabulary .. " scores each\ngoodbye\n")
  goodbye:close()
end
-- }}}
