#!/usr/bin/env luajit
-- analysis-gen.lua - writes the performance analysis's extra boxes and its map
--
-- In plain terms: the analysis times many variants of the same work, and
-- each variant is one station in one map, so a single program holds them
-- all and the host picks which to feed. This tool writes the variants
-- (nobody should type sixty near-identical functions) and the map that
-- places them, one station per variant, each with its own marked argument
-- and result.
--
-- The variants:
--   noop            returns its unit number: the cost of a task and nothing else
--   pose_fold       poses one unit, returns 4 bytes (the pose folded): the work,
--                   without the 2 KB result copy
--   pose_unit       poses one unit, returns the 2 KB pose (pose-boxes.c)
--   blob_N          fills and returns N bytes, no pose work: the cost of result size
--                   (16 bytes to 1 MB)
--   pose_chunk_K    poses K units, returns 4 bytes: the cost of task granularity
--                   (1 to 2048, the whole army in one task)
--   pose_chunk      poses 64 units, returns all 120 KB of poses (pose-boxes.c)
--
-- Usage:
--   luajit analysis-gen.lua boxes   the extra C, appended to pose-boxes.c's
--   luajit analysis-gen.lua map     the map
--   luajit analysis-gen.lua table   the host's variant table (C)

local BLOBS = { 16, 256, 2048, 16384, 65536, 122880, 262144, 524288, 1048576 }
local CHUNKS = { 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048 }

-- Every variant in station order: box name, request kind, result kind,
-- units per task, result C type.
local VARIANTS = {
    { box = "noop", request = "unit", result = "none", per = 1, type = "int" },
    { box = "pose_fold", request = "unit", result = "fold", per = 1, type = "int" },
    { box = "pose_unit", request = "unit", result = "pose", per = 1, type = "pose" },
}
for _, n in ipairs(BLOBS) do
    VARIANTS[#VARIANTS + 1] = { box = "make_blob_" .. n, request = "unit", result = "none", per = 1, type = "blob_" .. n }
end
for _, k in ipairs(CHUNKS) do
    VARIANTS[#VARIANTS + 1] = { box = "pose_chunk_" .. k, request = "chunk", result = "fold", per = k, type = "int" }
end
VARIANTS[#VARIANTS + 1] = { box = "pose_chunk", request = "chunk", result = "pose", per = 64, type = "chunk_pose" }

-- {{{ local function boxes
local function boxes()
    local out = {}
    local function w(s) out[#out + 1] = s end
    w("/* ---- generated by analysis-gen.lua: the analysis's variants ---- */")
    w("#include <string.h>")
    w("")
    w("/* {{{ static int fold_pose(const pose *p) */")
    w("/* A pose's 32-bit words XORed together: what every variant's checksum is")
    w(" * built from, so all of them can be compared with each other. */")
    w("static int fold_pose(const pose *p)")
    w("{")
    w("    const unsigned int *w = (const unsigned int *)p;")
    w("    unsigned int x = 0;")
    w("    for (unsigned long i = 0; i < sizeof(pose) / 4; i++) x ^= w[i];")
    w("    return (int)x;")
    w("}")
    w("/* }}} */")
    w("")
    w("/* A task and nothing else: the floor. */")
    w("int noop(pose_request r) { return r.unit; }")
    w("")
    w("/* The pose work, returning 4 bytes instead of 1920. */")
    w("int pose_fold(pose_request r) { pose p; pose_into(r.unit, r.time, &p); return fold_pose(&p); }")
    for _, n in ipairs(BLOBS) do
        w("")
        w(string.format("/* %d bytes, filled and returned: the cost of a result this size. */", n))
        w(string.format("typedef struct { char b[%d]; } blob_%d;", n, n))
        w(string.format("blob_%d make_blob_%d(pose_request r) { blob_%d b; memset(&b, r.unit & 255, sizeof b); return b; }", n, n, n))
    end
    for _, k in ipairs(CHUNKS) do
        w("")
        w(string.format("/* %d units posed per task, 4 bytes back. */", k))
        w(string.format("int pose_chunk_%d(chunk_request r)", k))
        w("{")
        w("    pose p;")
        w("    unsigned int x = 0;")
        w(string.format("    for (int u = 0; u < %d; u++) { pose_into(r.first + u, r.time, &p); x ^= (unsigned int)fold_pose(&p); }", k))
        w("    return (int)x;")
        w("}")
    end
    return table.concat(out, "\n")
end
-- }}}

-- {{{ local function map
-- One station per variant; station i takes argument i and gives result i.
local function map()
    local out = {}
    for i, v in ipairs(VARIANTS) do
        out[#out + 1] = string.format("station v%d (analysis-boxes.c:%s)", i - 1, v.box)
        out[#out + 1] = string.format("  in 0 - %d$", i - 1)
        out[#out + 1] = string.format("  out 0 - %d$", i - 1)
        out[#out + 1] = ""
    end
    return table.concat(out, "\n")
end
-- }}}

-- {{{ local function host_table
-- The host's table of variants, in station order, so argument and result i
-- are variant i.
local function host_table()
    local out = { "/* generated by analysis-gen.lua */", "static const variant VARIANTS[] = {" }
    for _, v in ipairs(VARIANTS) do
        out[#out + 1] = string.format('    { "%s", REQ_%s, RES_%s, %d, sizeof(%s) },',
            v.box, v.request:upper(), v.result:upper(), v.per, v.type)
    end
    out[#out + 1] = "};"
    out[#out + 1] = string.format("#define N_VARIANTS %d", #VARIANTS)
    return table.concat(out, "\n")
end
-- }}}

local what = arg[1]
if what == "boxes" then print(boxes())
elseif what == "map" then print(map())
elseif what == "table" then print(host_table())
else
    io.stderr:write("usage: analysis-gen.lua boxes|map|table\n")
    os.exit(64)
end
