#!/bin/bash
# =============================================================================
# Continual Co-operation - Dependency Installation Script
# Installs all external dependencies locally to this project
#
# This script orchestrates installation of:
#   - Effil (Lua multithreading library) - both Lua 5.x and LuaJIT versions
#   - Other dependencies as needed
#
# Usage: ./scripts/install-deps.sh [--clean] [--check]
# =============================================================================

set -euo pipefail

# {{{ Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
LIBS_DIR="${PROJECT_DIR}/libs"

# Effil configuration
EFFIL_VERSION="1.2.0"
EFFIL_REPO="https://github.com/effil/effil.git"
EFFIL_TAG="v${EFFIL_VERSION}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
# }}}

# {{{ check_dependencies
check_dependencies() {
    log_info "Checking system dependencies..."

    local missing=()

    command -v cmake &>/dev/null || missing+=("cmake")
    command -v git &>/dev/null || missing+=("git")
    command -v g++ &>/dev/null || command -v clang++ &>/dev/null || missing+=("g++ or clang++")

    # Check for at least one Lua version
    if ! command -v lua5.3 &>/dev/null && ! command -v luajit &>/dev/null; then
        missing+=("lua5.3 or luajit")
    fi

    if [[ ${#missing[@]} -gt 0 ]]; then
        log_error "Missing: ${missing[*]}"
        echo "Install with: sudo apt-get install cmake git g++ lua5.3 liblua5.3-dev luajit libluajit-5.1-dev"
        return 1
    fi

    log_info "All system dependencies found"
    return 0
}
# }}}

# {{{ install_effil
install_effil() {
    local lua_version="$1"
    local target_dir="$2"
    local lua_include="$3"

    log_info "Installing Effil for $lua_version to $target_dir..."

    # Check if already built
    if [[ -f "${target_dir}/build/effil.so" ]]; then
        log_info "Effil ($lua_version) already installed"
        return 0
    fi

    # Clone if needed
    if [[ ! -d "${target_dir}/.git" ]]; then
        log_info "Cloning Effil for $lua_version..."
        rm -rf "$target_dir"
        git clone --depth 1 --branch "$EFFIL_TAG" "$EFFIL_REPO" "$target_dir"
        cd "$target_dir"
        git submodule update --init --recursive
    fi

    # Build
    log_info "Building Effil ($lua_version)..."
    mkdir -p "${target_dir}/build"
    cd "${target_dir}/build"

    cmake .. \
        -DCMAKE_BUILD_TYPE=Release \
        -DLUA_INCLUDE_DIR="$lua_include"

    make -j"$(nproc)"

    log_info "Effil ($lua_version) built successfully"
    cd "$PROJECT_DIR"
}
# }}}

# {{{ install_all_effil_versions
install_all_effil_versions() {
    # Install for Lua 5.3
    if command -v lua5.3 &>/dev/null; then
        local lua53_include="/usr/include/lua5.3"
        [[ -d "$lua53_include" ]] && install_effil "lua53" "${LIBS_DIR}/effil" "$lua53_include"
    fi

    # Install for LuaJIT
    if command -v luajit &>/dev/null; then
        local luajit_include="/usr/include/luajit-2.1"
        [[ ! -d "$luajit_include" ]] && luajit_include="/usr/include/luajit-2.0"
        [[ -d "$luajit_include" ]] && install_effil "luajit" "${LIBS_DIR}/effil-jit" "$luajit_include"
    fi
}
# }}}

# {{{ create_lua_paths
create_lua_paths() {
    local paths_file="${LIBS_DIR}/paths.lua"

    log_info "Creating Lua paths configuration..."

    cat > "$paths_file" << 'EOF'
-- Auto-generated by install-deps.sh
-- Add this at the start of your Lua scripts:
--   dofile('libs/paths.lua')

local project_root = debug.getinfo(1, "S").source:match("@(.*/)")
if project_root then
    project_root = project_root:gsub("/libs/$", "")
else
    project_root = "."
end

-- Detect Lua version and set appropriate effil path
local is_luajit = type(jit) == "table"
local effil_path = is_luajit and "/libs/effil-jit/build/?.so" or "/libs/effil/build/?.so"

package.cpath = package.cpath .. ";" .. project_root .. effil_path
package.path = package.path .. ";" .. project_root .. "/libs/?.lua"
package.path = package.path .. ";" .. project_root .. "/src/?.lua"

return project_root
EOF

    log_info "Created: $paths_file"
}
# }}}

# {{{ verify_installation
verify_installation() {
    log_info "Verifying installation..."
    local ok=0

    cd "$PROJECT_DIR"

    # Test effil with Lua 5.3
    if [[ -f "${LIBS_DIR}/effil/build/effil.so" ]]; then
        if lua5.3 -e "package.cpath = './libs/effil/build/?.so;' .. package.cpath; local e = require('effil'); print('Effil (Lua5.3) OK')" 2>/dev/null; then
            log_info "Effil (Lua 5.3): OK"
        else
            log_warn "Effil (Lua 5.3): FAILED"
            ok=1
        fi
    fi

    # Test effil with LuaJIT
    if [[ -f "${LIBS_DIR}/effil-jit/build/effil.so" ]]; then
        if luajit -e "package.cpath = './libs/effil-jit/build/?.so;' .. package.cpath; local e = require('effil'); print('Effil (LuaJIT) OK')" 2>/dev/null; then
            log_info "Effil (LuaJIT): OK"
        else
            log_warn "Effil (LuaJIT): FAILED"
            ok=1
        fi
    fi

    return $ok
}
# }}}

# {{{ clean
clean() {
    log_info "Cleaning installed libraries..."
    rm -rf "${LIBS_DIR}/effil" "${LIBS_DIR}/effil-jit"
    log_info "Cleaned"
}
# }}}

# {{{ show_usage
show_usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --check    Check if dependencies are installed"
    echo "  --clean    Remove all installed native libraries"
    echo "  --help     Show this help"
}
# }}}

# {{{ main
main() {
    cd "$PROJECT_DIR"

    case "${1:-}" in
        --check)
            check_dependencies && verify_installation
            exit $?
            ;;
        --clean)
            clean
            exit 0
            ;;
        --help|-h)
            show_usage
            exit 0
            ;;
    esac

    echo ""
    echo -e "${CYAN}=== Continual Co-operation Dependency Installer ===${NC}"
    echo ""

    check_dependencies || exit 1

    install_all_effil_versions
    create_lua_paths
    verify_installation || true

    echo ""
    log_info "Installation complete!"
    echo ""
    echo "To use in your Lua scripts, add at the top:"
    echo "  dofile('libs/paths.lua')"
    echo ""
}

main "$@"
# }}}
